#ifndef STAN_MATH_PRIM_HPP
#define STAN_MATH_PRIM_HPP

#include <stan/math/prim/meta/contains_std_vector.hpp>
#include <stan/math/prim/meta/get.hpp>
#include <stan/math/prim/meta/index_type.hpp>
#include <stan/math/prim/meta/is_constant_struct.hpp>
#include <stan/math/prim/meta/is_vector.hpp>
#include <stan/math/prim/meta/length.hpp>
#include <stan/math/prim/meta/scalar_type.hpp>
#include <stan/math/prim/meta/value_type.hpp>
#include <stan/math/prim/meta/VectorBuilderHelper.hpp>

#include <stan/math/prim/err/check_matching_sizes.hpp>
#include <stan/math/prim/err/check_nonzero_size.hpp>
#include <stan/math/prim/err/check_ordered.hpp>

#ifdef STAN_OPENCL
#include <stan/math/prim/err/check_opencl.hpp>
#endif

#include <stan/math/prim/fun/array_builder.hpp>
#include <stan/math/prim/fun/common_type.hpp>
#include <stan/math/prim/fun/dot.hpp>
#include <stan/math/prim/fun/dot_self.hpp>
#include <stan/math/prim/fun/fill.hpp>
#include <stan/math/prim/fun/inverse_softmax.hpp>
#include <stan/math/prim/fun/log_sum_exp.hpp>
#include <stan/math/prim/fun/promote_elements.hpp>
#include <stan/math/prim/fun/promote_scalar.hpp>
#include <stan/math/prim/fun/promote_scalar_type.hpp>
#include <stan/math/prim/fun/rep_array.hpp>
#include <stan/math/prim/fun/scaled_add.hpp>
#include <stan/math/prim/fun/sort_asc.hpp>
#include <stan/math/prim/fun/sort_desc.hpp>
#include <stan/math/prim/fun/sub.hpp>
#include <stan/math/prim/fun/sum.hpp>
#include <stan/math/prim/fun/value_of.hpp>
#include <stan/math/prim/fun/value_of_rec.hpp>

#include <stan/math/prim/functor/coupled_ode_observer.hpp>
#include <stan/math/prim/functor/coupled_ode_system.hpp>
#include <stan/math/prim/functor/integrate_1d.hpp>
#include <stan/math/prim/functor/integrate_ode_rk45.hpp>
#include <stan/math/prim/functor/mpi_command.hpp>
#include <stan/math/prim/functor/mpi_distributed_apply.hpp>
#include <stan/math/prim/functor/mpi_cluster.hpp>

#include <stan/math/prim/scal.hpp>

#include <stan/math/prim/meta/get.hpp>
#include <stan/math/prim/meta/index_type.hpp>
#include <stan/math/prim/meta/is_vector.hpp>
#include <stan/math/prim/meta/length.hpp>

#include <stan/math/prim/meta/broadcast_array.hpp>
#include <stan/math/prim/meta/get.hpp>
#include <stan/math/prim/meta/index_type.hpp>
#include <stan/math/prim/meta/is_constant_struct.hpp>
#include <stan/math/prim/meta/is_vector.hpp>
#include <stan/math/prim/meta/is_vector_like.hpp>
#include <stan/math/prim/meta/length.hpp>
#include <stan/math/prim/meta/length_mvt.hpp>
#include <stan/math/prim/meta/operands_and_partials.hpp>
#include <stan/math/prim/meta/scalar_type.hpp>
#include <stan/math/prim/meta/seq_view.hpp>
#include <stan/math/prim/meta/value_type.hpp>
#include <stan/math/prim/meta/vector_seq_view.hpp>

#include <stan/math/prim/err/check_cholesky_factor.hpp>
#include <stan/math/prim/err/check_cholesky_factor_corr.hpp>
#include <stan/math/prim/err/check_column_index.hpp>
#include <stan/math/prim/err/check_corr_matrix.hpp>
#include <stan/math/prim/err/check_cov_matrix.hpp>
#include <stan/math/prim/err/check_finite.hpp>
#include <stan/math/prim/err/check_ldlt_factor.hpp>
#include <stan/math/prim/err/check_lower_triangular.hpp>
#include <stan/math/prim/err/check_matching_dims.hpp>
#include <stan/math/prim/err/check_multiplicable.hpp>
#include <stan/math/prim/err/check_ordered.hpp>
#include <stan/math/prim/err/check_pos_definite.hpp>
#include <stan/math/prim/err/check_pos_semidefinite.hpp>
#include <stan/math/prim/err/check_positive_ordered.hpp>
#include <stan/math/prim/err/check_range.hpp>
#include <stan/math/prim/err/check_row_index.hpp>
#include <stan/math/prim/err/check_simplex.hpp>
#include <stan/math/prim/err/check_spsd_matrix.hpp>
#include <stan/math/prim/err/check_square.hpp>
#include <stan/math/prim/err/check_std_vector_index.hpp>
#include <stan/math/prim/err/check_symmetric.hpp>
#include <stan/math/prim/err/check_unit_vector.hpp>
#include <stan/math/prim/err/check_vector.hpp>
#include <stan/math/prim/err/constraint_tolerance.hpp>
#include <stan/math/prim/err/validate_non_negative_index.hpp>

#include <stan/math/prim/fun/Eigen.hpp>
#include <stan/math/prim/fun/LDLT_factor.hpp>
#include <stan/math/prim/fun/Phi.hpp>
#include <stan/math/prim/fun/Phi_approx.hpp>
#include <stan/math/prim/fun/accumulator.hpp>
#include <stan/math/prim/fun/acos.hpp>
#include <stan/math/prim/fun/acosh.hpp>
#include <stan/math/prim/fun/add.hpp>
#include <stan/math/prim/fun/add_diag.hpp>
#include <stan/math/prim/fun/append_array.hpp>
#include <stan/math/prim/fun/append_col.hpp>
#include <stan/math/prim/fun/append_row.hpp>
#include <stan/math/prim/fun/asin.hpp>
#include <stan/math/prim/fun/asinh.hpp>
#include <stan/math/prim/fun/assign.hpp>
#include <stan/math/prim/fun/atan.hpp>
#include <stan/math/prim/fun/atanh.hpp>
#include <stan/math/prim/fun/autocorrelation.hpp>
#include <stan/math/prim/fun/autocovariance.hpp>
#include <stan/math/prim/fun/block.hpp>
#include <stan/math/prim/fun/cbrt.hpp>
#include <stan/math/prim/fun/ceil.hpp>
#include <stan/math/prim/fun/chol2inv.hpp>
#include <stan/math/prim/fun/cholesky_corr_constrain.hpp>
#include <stan/math/prim/fun/cholesky_corr_free.hpp>
#include <stan/math/prim/fun/cholesky_decompose.hpp>
#include <stan/math/prim/fun/cholesky_factor_constrain.hpp>
#include <stan/math/prim/fun/cholesky_factor_free.hpp>
#include <stan/math/prim/fun/col.hpp>
#include <stan/math/prim/fun/cols.hpp>
#include <stan/math/prim/fun/columns_dot_product.hpp>
#include <stan/math/prim/fun/columns_dot_self.hpp>
#include <stan/math/prim/fun/common_type.hpp>
#include <stan/math/prim/fun/corr_matrix_constrain.hpp>
#include <stan/math/prim/fun/corr_matrix_free.hpp>
#include <stan/math/prim/fun/cos.hpp>
#include <stan/math/prim/fun/cosh.hpp>
#include <stan/math/prim/fun/cov_exp_quad.hpp>
#include <stan/math/prim/fun/cov_matrix_constrain.hpp>
#include <stan/math/prim/fun/cov_matrix_constrain_lkj.hpp>
#include <stan/math/prim/fun/cov_matrix_free.hpp>
#include <stan/math/prim/fun/cov_matrix_free_lkj.hpp>
#include <stan/math/prim/fun/crossprod.hpp>
#include <stan/math/prim/fun/csr_extract_u.hpp>
#include <stan/math/prim/fun/csr_extract_v.hpp>
#include <stan/math/prim/fun/csr_extract_w.hpp>
#include <stan/math/prim/fun/csr_matrix_times_vector.hpp>
#include <stan/math/prim/fun/csr_to_dense_matrix.hpp>
#include <stan/math/prim/fun/csr_u_to_z.hpp>
#include <stan/math/prim/fun/cumulative_sum.hpp>
#include <stan/math/prim/fun/determinant.hpp>
#include <stan/math/prim/fun/diag_matrix.hpp>
#include <stan/math/prim/fun/diag_post_multiply.hpp>
#include <stan/math/prim/fun/diag_pre_multiply.hpp>
#include <stan/math/prim/fun/diagonal.hpp>
#include <stan/math/prim/fun/digamma.hpp>
#include <stan/math/prim/fun/dims.hpp>
#include <stan/math/prim/fun/distance.hpp>
#include <stan/math/prim/fun/divide.hpp>
#include <stan/math/prim/fun/dot_product.hpp>
#include <stan/math/prim/fun/dot_self.hpp>
#include <stan/math/prim/fun/eigenvalues_sym.hpp>
#include <stan/math/prim/fun/eigenvectors_sym.hpp>
#include <stan/math/prim/fun/elt_divide.hpp>
#include <stan/math/prim/fun/elt_multiply.hpp>
#include <stan/math/prim/fun/erf.hpp>
#include <stan/math/prim/fun/erfc.hpp>
#include <stan/math/prim/fun/exp.hpp>
#include <stan/math/prim/fun/exp2.hpp>
#include <stan/math/prim/fun/expm1.hpp>
#include <stan/math/prim/fun/fabs.hpp>
#include <stan/math/prim/fun/factor_U.hpp>
#include <stan/math/prim/fun/factor_cov_matrix.hpp>
#include <stan/math/prim/fun/fill.hpp>
#include <stan/math/prim/fun/floor.hpp>
#include <stan/math/prim/fun/get_base1.hpp>
#include <stan/math/prim/fun/get_base1_lhs.hpp>
#include <stan/math/prim/fun/get_lp.hpp>
#include <stan/math/prim/fun/gp_dot_prod_cov.hpp>
#include <stan/math/prim/fun/gp_matern52_cov.hpp>
#include <stan/math/prim/fun/gp_periodic_cov.hpp>
#include <stan/math/prim/fun/head.hpp>
#include <stan/math/prim/fun/initialize.hpp>
#include <stan/math/prim/fun/inv.hpp>
#include <stan/math/prim/fun/inv_Phi.hpp>
#include <stan/math/prim/fun/inv_cloglog.hpp>
#include <stan/math/prim/fun/inv_logit.hpp>
#include <stan/math/prim/fun/inv_sqrt.hpp>
#include <stan/math/prim/fun/inv_square.hpp>
#include <stan/math/prim/fun/inverse.hpp>
#include <stan/math/prim/fun/inverse_spd.hpp>
#include <stan/math/prim/fun/lgamma.hpp>
#include <stan/math/prim/fun/log.hpp>
#include <stan/math/prim/fun/log10.hpp>
#include <stan/math/prim/fun/log1m.hpp>
#include <stan/math/prim/fun/log1m_exp.hpp>
#include <stan/math/prim/fun/log1m_inv_logit.hpp>
#include <stan/math/prim/fun/log1p.hpp>
#include <stan/math/prim/fun/log1p_exp.hpp>
#include <stan/math/prim/fun/log2.hpp>
#include <stan/math/prim/fun/log_determinant.hpp>
#include <stan/math/prim/fun/log_determinant_ldlt.hpp>
#include <stan/math/prim/fun/log_determinant_spd.hpp>
#include <stan/math/prim/fun/log_inv_logit.hpp>
#include <stan/math/prim/fun/log_mix.hpp>
#include <stan/math/prim/fun/log_softmax.hpp>
#include <stan/math/prim/fun/log_sum_exp.hpp>
#include <stan/math/prim/fun/logit.hpp>
#include <stan/math/prim/fun/make_nu.hpp>
#include <stan/math/prim/fun/matrix_exp.hpp>
#include <stan/math/prim/fun/matrix_exp_multiply.hpp>
#include <stan/math/prim/fun/max.hpp>
#include <stan/math/prim/fun/mdivide_left.hpp>
#include <stan/math/prim/fun/mdivide_left_ldlt.hpp>
#include <stan/math/prim/fun/mdivide_left_spd.hpp>
#include <stan/math/prim/fun/mdivide_left_tri.hpp>
#include <stan/math/prim/fun/mdivide_left_tri_low.hpp>
#include <stan/math/prim/fun/mdivide_right.hpp>
#include <stan/math/prim/fun/mdivide_right_ldlt.hpp>
#include <stan/math/prim/fun/mdivide_right_spd.hpp>
#include <stan/math/prim/fun/mdivide_right_tri.hpp>
#include <stan/math/prim/fun/mdivide_right_tri_low.hpp>
#include <stan/math/prim/fun/mean.hpp>
#include <stan/math/prim/fun/min.hpp>
#include <stan/math/prim/fun/minus.hpp>
#include <stan/math/prim/fun/multiply.hpp>
#include <stan/math/prim/fun/multiply_lower_tri_self_transpose.hpp>
#include <stan/math/prim/fun/num_elements.hpp>
#include <stan/math/prim/fun/ordered_constrain.hpp>
#include <stan/math/prim/fun/ordered_free.hpp>
#include <stan/math/prim/fun/positive_ordered_constrain.hpp>
#include <stan/math/prim/fun/positive_ordered_free.hpp>
#include <stan/math/prim/fun/prod.hpp>
#include <stan/math/prim/fun/promote_common.hpp>
#include <stan/math/prim/fun/promote_elements.hpp>
#include <stan/math/prim/fun/promote_scalar.hpp>
#include <stan/math/prim/fun/promote_scalar_type.hpp>
#include <stan/math/prim/fun/qr_Q.hpp>
#include <stan/math/prim/fun/qr_R.hpp>
#include <stan/math/prim/fun/qr_thin_Q.hpp>
#include <stan/math/prim/fun/qr_thin_R.hpp>
#include <stan/math/prim/fun/quad_form.hpp>
#include <stan/math/prim/fun/quad_form_diag.hpp>
#include <stan/math/prim/fun/quad_form_sym.hpp>
#include <stan/math/prim/fun/rank.hpp>
#include <stan/math/prim/fun/read_corr_L.hpp>
#include <stan/math/prim/fun/read_corr_matrix.hpp>
#include <stan/math/prim/fun/read_cov_L.hpp>
#include <stan/math/prim/fun/read_cov_matrix.hpp>
#include <stan/math/prim/fun/rep_matrix.hpp>
#include <stan/math/prim/fun/rep_row_vector.hpp>
#include <stan/math/prim/fun/rep_vector.hpp>
#include <stan/math/prim/fun/resize.hpp>
#include <stan/math/prim/fun/round.hpp>
#include <stan/math/prim/fun/row.hpp>
#include <stan/math/prim/fun/rows.hpp>
#include <stan/math/prim/fun/rows_dot_product.hpp>
#include <stan/math/prim/fun/rows_dot_self.hpp>
#include <stan/math/prim/fun/scale_matrix_exp_multiply.hpp>
#include <stan/math/prim/fun/sd.hpp>
#include <stan/math/prim/fun/segment.hpp>
#include <stan/math/prim/fun/simplex_constrain.hpp>
#include <stan/math/prim/fun/simplex_free.hpp>
#include <stan/math/prim/fun/sin.hpp>
#include <stan/math/prim/fun/singular_values.hpp>
#include <stan/math/prim/fun/sinh.hpp>
#include <stan/math/prim/fun/size.hpp>
#include <stan/math/prim/fun/softmax.hpp>
#include <stan/math/prim/fun/sort_asc.hpp>
#include <stan/math/prim/fun/sort_desc.hpp>
#include <stan/math/prim/fun/sort_indices.hpp>
#include <stan/math/prim/fun/sort_indices_asc.hpp>
#include <stan/math/prim/fun/sort_indices_desc.hpp>
#include <stan/math/prim/fun/sqrt.hpp>
#include <stan/math/prim/fun/square.hpp>
#include <stan/math/prim/fun/squared_distance.hpp>
#include <stan/math/prim/fun/stan_print.hpp>
#include <stan/math/prim/fun/sub_col.hpp>
#include <stan/math/prim/fun/sub_row.hpp>
#include <stan/math/prim/fun/subtract.hpp>
#include <stan/math/prim/fun/sum.hpp>
#include <stan/math/prim/fun/tail.hpp>
#include <stan/math/prim/fun/tan.hpp>
#include <stan/math/prim/fun/tanh.hpp>
#include <stan/math/prim/fun/tcrossprod.hpp>
#include <stan/math/prim/fun/tgamma.hpp>
#include <stan/math/prim/fun/to_array_1d.hpp>
#include <stan/math/prim/fun/to_array_2d.hpp>
#include <stan/math/prim/fun/to_matrix.hpp>
#include <stan/math/prim/fun/to_row_vector.hpp>
#include <stan/math/prim/fun/to_vector.hpp>
#include <stan/math/prim/fun/trace.hpp>
#include <stan/math/prim/fun/trace_gen_inv_quad_form_ldlt.hpp>
#include <stan/math/prim/fun/trace_gen_quad_form.hpp>
#include <stan/math/prim/fun/trace_inv_quad_form_ldlt.hpp>
#include <stan/math/prim/fun/trace_quad_form.hpp>
#include <stan/math/prim/fun/transpose.hpp>
#include <stan/math/prim/fun/trigamma.hpp>
#include <stan/math/prim/fun/trunc.hpp>
#include <stan/math/prim/fun/typedefs.hpp>
#include <stan/math/prim/fun/unit_vector_constrain.hpp>
#include <stan/math/prim/fun/unit_vector_free.hpp>
#include <stan/math/prim/fun/value_of.hpp>
#include <stan/math/prim/fun/value_of_rec.hpp>
#include <stan/math/prim/fun/variance.hpp>
#include <stan/math/prim/fun/welford_covar_estimator.hpp>
#include <stan/math/prim/fun/welford_var_estimator.hpp>

#include <stan/math/prim/functor/finite_diff_gradient.hpp>
#include <stan/math/prim/functor/finite_diff_hessian.hpp>
#include <stan/math/prim/functor/map_rect.hpp>
#include <stan/math/prim/functor/map_rect_combine.hpp>
#include <stan/math/prim/functor/map_rect_concurrent.hpp>
#include <stan/math/prim/functor/map_rect_reduce.hpp>
#include <stan/math/prim/prob/bernoulli_logit_glm_log.hpp>
#include <stan/math/prim/prob/bernoulli_logit_glm_lpmf.hpp>
#include <stan/math/prim/prob/categorical_log.hpp>
#include <stan/math/prim/prob/categorical_logit_log.hpp>
#include <stan/math/prim/prob/categorical_logit_lpmf.hpp>
#include <stan/math/prim/prob/categorical_logit_rng.hpp>
#include <stan/math/prim/prob/categorical_lpmf.hpp>
#include <stan/math/prim/prob/categorical_rng.hpp>
#include <stan/math/prim/prob/dirichlet_log.hpp>
#include <stan/math/prim/prob/dirichlet_lpmf.hpp>
#include <stan/math/prim/prob/dirichlet_rng.hpp>
#include <stan/math/prim/prob/gaussian_dlm_obs_log.hpp>
#include <stan/math/prim/prob/gaussian_dlm_obs_lpdf.hpp>
#include <stan/math/prim/prob/inv_wishart_log.hpp>
#include <stan/math/prim/prob/inv_wishart_lpdf.hpp>
#include <stan/math/prim/prob/inv_wishart_rng.hpp>
#include <stan/math/prim/prob/lkj_corr_cholesky_log.hpp>
#include <stan/math/prim/prob/lkj_corr_cholesky_lpdf.hpp>
#include <stan/math/prim/prob/lkj_corr_cholesky_rng.hpp>
#include <stan/math/prim/prob/lkj_corr_log.hpp>
#include <stan/math/prim/prob/lkj_corr_lpdf.hpp>
#include <stan/math/prim/prob/lkj_corr_rng.hpp>
#include <stan/math/prim/prob/lkj_cov_log.hpp>
#include <stan/math/prim/prob/lkj_cov_lpdf.hpp>
#include <stan/math/prim/prob/matrix_normal_prec_log.hpp>
#include <stan/math/prim/prob/matrix_normal_prec_lpdf.hpp>
#include <stan/math/prim/prob/multi_gp_cholesky_log.hpp>
#include <stan/math/prim/prob/multi_gp_cholesky_lpdf.hpp>
#include <stan/math/prim/prob/multi_gp_log.hpp>
#include <stan/math/prim/prob/multi_gp_lpdf.hpp>
#include <stan/math/prim/prob/multi_normal_cholesky_log.hpp>
#include <stan/math/prim/prob/multi_normal_cholesky_lpdf.hpp>
#include <stan/math/prim/prob/multi_normal_cholesky_rng.hpp>
#include <stan/math/prim/prob/multi_normal_log.hpp>
#include <stan/math/prim/prob/multi_normal_lpdf.hpp>
#include <stan/math/prim/prob/multi_normal_prec_log.hpp>
#include <stan/math/prim/prob/multi_normal_prec_lpdf.hpp>
#include <stan/math/prim/prob/multi_normal_rng.hpp>
#include <stan/math/prim/prob/multi_student_t_log.hpp>
#include <stan/math/prim/prob/multi_student_t_lpdf.hpp>
#include <stan/math/prim/prob/multi_student_t_rng.hpp>
#include <stan/math/prim/prob/multinomial_log.hpp>
#include <stan/math/prim/prob/multinomial_lpmf.hpp>
#include <stan/math/prim/prob/multinomial_rng.hpp>
#include <stan/math/prim/prob/neg_binomial_2_log_glm_log.hpp>
#include <stan/math/prim/prob/neg_binomial_2_log_glm_lpmf.hpp>
#include <stan/math/prim/prob/normal_id_glm_log.hpp>
#include <stan/math/prim/prob/normal_id_glm_lpdf.hpp>
#include <stan/math/prim/prob/ordered_logistic_log.hpp>
#include <stan/math/prim/prob/ordered_logistic_lpmf.hpp>
#include <stan/math/prim/prob/ordered_logistic_rng.hpp>
#include <stan/math/prim/prob/ordered_probit_log.hpp>
#include <stan/math/prim/prob/ordered_probit_lpmf.hpp>
#include <stan/math/prim/prob/ordered_probit_rng.hpp>
#include <stan/math/prim/prob/poisson_log_glm_log.hpp>
#include <stan/math/prim/prob/poisson_log_glm_lpmf.hpp>
#include <stan/math/prim/prob/wishart_log.hpp>
#include <stan/math/prim/prob/wishart_lpdf.hpp>
#include <stan/math/prim/prob/wishart_rng.hpp>

#include <stan/math/prim/vectorize/apply_scalar_unary.hpp>

#include <stan/math/prim/arr.hpp>

#include <stan/math/version.hpp>

#include <stan/math/prim/meta/ad_promotable.hpp>
#include <stan/math/prim/meta/child_type.hpp>
#include <stan/math/prim/meta/contains_fvar.hpp>
#include <stan/math/prim/meta/contains_nonconstant_struct.hpp>
#include <stan/math/prim/meta/contains_std_vector.hpp>
#include <stan/math/prim/meta/contains_vector.hpp>
#include <stan/math/prim/meta/error_index.hpp>
#include <stan/math/prim/meta/get.hpp>
#include <stan/math/prim/meta/include_summand.hpp>
#include <stan/math/prim/meta/index_type.hpp>
#include <stan/math/prim/meta/is_constant.hpp>
#include <stan/math/prim/meta/is_constant_struct.hpp>
#include <stan/math/prim/meta/is_fvar.hpp>
#include <stan/math/prim/meta/is_var.hpp>
#include <stan/math/prim/meta/is_var_or_arithmetic.hpp>
#include <stan/math/prim/meta/is_vector.hpp>
#include <stan/math/prim/meta/is_vector_like.hpp>
#include <stan/math/prim/meta/length.hpp>
#include <stan/math/prim/meta/length_mvt.hpp>
#include <stan/math/prim/meta/likely.hpp>
#include <stan/math/prim/meta/max_size.hpp>
#include <stan/math/prim/meta/max_size_mvt.hpp>
#include <stan/math/prim/meta/operands_and_partials.hpp>
#include <stan/math/prim/meta/partials_return_type.hpp>
#include <stan/math/prim/meta/partials_type.hpp>
#include <stan/math/prim/meta/return_type.hpp>
#include <stan/math/prim/meta/scalar_seq_view.hpp>
#include <stan/math/prim/meta/scalar_type.hpp>
#include <stan/math/prim/meta/scalar_type_pre.hpp>
#include <stan/math/prim/meta/size_of.hpp>
#include <stan/math/prim/meta/value_type.hpp>
#include <stan/math/prim/meta/StdVectorBuilder.hpp>
#include <stan/math/prim/meta/VectorBuilder.hpp>

#include <stan/math/prim/err/check_2F1_converges.hpp>
#include <stan/math/prim/err/check_3F2_converges.hpp>
#include <stan/math/prim/err/check_bounded.hpp>
#include <stan/math/prim/err/check_consistent_size.hpp>
#include <stan/math/prim/err/check_consistent_sizes.hpp>
#include <stan/math/prim/err/check_finite.hpp>
#include <stan/math/prim/err/check_greater.hpp>
#include <stan/math/prim/err/check_greater_or_equal.hpp>
#include <stan/math/prim/err/check_less.hpp>
#include <stan/math/prim/err/check_less_or_equal.hpp>
#include <stan/math/prim/err/check_nonnegative.hpp>
#include <stan/math/prim/err/check_not_nan.hpp>
#include <stan/math/prim/err/check_positive.hpp>
#include <stan/math/prim/err/check_positive_finite.hpp>
#include <stan/math/prim/err/check_positive_size.hpp>
#include <stan/math/prim/err/check_size_match.hpp>
#include <stan/math/prim/err/domain_error.hpp>
#include <stan/math/prim/err/domain_error_vec.hpp>
#include <stan/math/prim/err/invalid_argument.hpp>
#include <stan/math/prim/err/invalid_argument_vec.hpp>
#include <stan/math/prim/err/out_of_range.hpp>

#include <stan/math/prim/fun/abs.hpp>
#include <stan/math/prim/fun/acosh.hpp>
#include <stan/math/prim/fun/asinh.hpp>
#include <stan/math/prim/fun/atanh.hpp>
#include <stan/math/prim/fun/as_bool.hpp>
#include <stan/math/prim/fun/bessel_first_kind.hpp>
#include <stan/math/prim/fun/bessel_second_kind.hpp>
#include <stan/math/prim/fun/binary_log_loss.hpp>
#include <stan/math/prim/fun/binomial_coefficient_log.hpp>
#include <stan/math/prim/fun/boost_policy.hpp>
#include <stan/math/prim/fun/cbrt.hpp>
#include <stan/math/prim/fun/choose.hpp>
#include <stan/math/prim/fun/common_type.hpp>
#include <stan/math/prim/fun/constants.hpp>
#include <stan/math/prim/fun/corr_constrain.hpp>
#include <stan/math/prim/fun/corr_free.hpp>
#include <stan/math/prim/fun/digamma.hpp>
#include <stan/math/prim/fun/distance.hpp>
#include <stan/math/prim/fun/divide.hpp>
#include <stan/math/prim/fun/erf.hpp>
#include <stan/math/prim/fun/erfc.hpp>
#include <stan/math/prim/fun/exp2.hpp>
#include <stan/math/prim/fun/exp.hpp>
#include <stan/math/prim/fun/expm1.hpp>
#include <stan/math/prim/fun/F32.hpp>
#include <stan/math/prim/fun/falling_factorial.hpp>
#include <stan/math/prim/fun/fdim.hpp>
#include <stan/math/prim/fun/fill.hpp>
#include <stan/math/prim/fun/fma.hpp>
#include <stan/math/prim/fun/fmax.hpp>
#include <stan/math/prim/fun/fmin.hpp>
#include <stan/math/prim/fun/gamma_p.hpp>
#include <stan/math/prim/fun/gamma_q.hpp>
#include <stan/math/prim/fun/grad_2F1.hpp>
#include <stan/math/prim/fun/grad_F32.hpp>
#include <stan/math/prim/fun/grad_inc_beta.hpp>
#include <stan/math/prim/fun/grad_reg_inc_beta.hpp>
#include <stan/math/prim/fun/grad_reg_inc_gamma.hpp>
#include <stan/math/prim/fun/grad_reg_lower_inc_gamma.hpp>
#include <stan/math/prim/fun/hypot.hpp>
#include <stan/math/prim/fun/ibeta.hpp>
#include <stan/math/prim/fun/identity_constrain.hpp>
#include <stan/math/prim/fun/identity_free.hpp>
#include <stan/math/prim/fun/if_else.hpp>
#include <stan/math/prim/fun/inc_beta.hpp>
#include <stan/math/prim/fun/int_step.hpp>
#include <stan/math/prim/fun/inv.hpp>
#include <stan/math/prim/fun/inv_cloglog.hpp>
#include <stan/math/prim/fun/inv_logit.hpp>
#include <stan/math/prim/fun/inv_Phi.hpp>
#include <stan/math/prim/fun/inv_sqrt.hpp>
#include <stan/math/prim/fun/inv_square.hpp>
#include <stan/math/prim/fun/is_inf.hpp>
#include <stan/math/prim/fun/is_nan.hpp>
#include <stan/math/prim/fun/is_uninitialized.hpp>
#include <stan/math/prim/fun/lb_constrain.hpp>
#include <stan/math/prim/fun/lb_free.hpp>
#include <stan/math/prim/fun/lbeta.hpp>
#include <stan/math/prim/fun/ldexp.hpp>
#include <stan/math/prim/fun/lgamma.hpp>
#include <stan/math/prim/fun/lmgamma.hpp>
#include <stan/math/prim/fun/locscale_constrain.hpp>
#include <stan/math/prim/fun/locscale_free.hpp>
#include <stan/math/prim/fun/log.hpp>
#include <stan/math/prim/fun/log1m.hpp>
#include <stan/math/prim/fun/log1m_exp.hpp>
#include <stan/math/prim/fun/log1m_inv_logit.hpp>
#include <stan/math/prim/fun/log1p.hpp>
#include <stan/math/prim/fun/log1p_exp.hpp>
#include <stan/math/prim/fun/log2.hpp>
#include <stan/math/prim/fun/log_diff_exp.hpp>
#include <stan/math/prim/fun/log_falling_factorial.hpp>
#include <stan/math/prim/fun/log_inv_logit.hpp>
#include <stan/math/prim/fun/log_inv_logit_diff.hpp>
#include <stan/math/prim/fun/log_mix.hpp>
#include <stan/math/prim/fun/log_modified_bessel_first_kind.hpp>
#include <stan/math/prim/fun/log_rising_factorial.hpp>
#include <stan/math/prim/fun/log_sum_exp.hpp>
#include <stan/math/prim/fun/logical_and.hpp>
#include <stan/math/prim/fun/logical_eq.hpp>
#include <stan/math/prim/fun/logical_gt.hpp>
#include <stan/math/prim/fun/logical_gte.hpp>
#include <stan/math/prim/fun/logical_lt.hpp>
#include <stan/math/prim/fun/logical_lte.hpp>
#include <stan/math/prim/fun/logical_negation.hpp>
#include <stan/math/prim/fun/logical_neq.hpp>
#include <stan/math/prim/fun/logical_or.hpp>
#include <stan/math/prim/fun/logit.hpp>
#include <stan/math/prim/fun/lub_constrain.hpp>
#include <stan/math/prim/fun/lub_free.hpp>
#include <stan/math/prim/fun/modified_bessel_first_kind.hpp>
#include <stan/math/prim/fun/modified_bessel_second_kind.hpp>
#include <stan/math/prim/fun/modulus.hpp>
#include <stan/math/prim/fun/multiply_log.hpp>
#include <stan/math/prim/fun/offset_multiplier_constrain.hpp>
#include <stan/math/prim/fun/offset_multiplier_free.hpp>
#include <stan/math/prim/fun/owens_t.hpp>
#include <stan/math/prim/fun/Phi.hpp>
#include <stan/math/prim/fun/Phi_approx.hpp>
#include <stan/math/prim/fun/positive_constrain.hpp>
#include <stan/math/prim/fun/positive_free.hpp>
#include <stan/math/prim/fun/primitive_value.hpp>
#include <stan/math/prim/fun/prob_constrain.hpp>
#include <stan/math/prim/fun/prob_free.hpp>
#include <stan/math/prim/fun/promote_elements.hpp>
#include <stan/math/prim/fun/promote_scalar.hpp>
#include <stan/math/prim/fun/promote_scalar_type.hpp>
#include <stan/math/prim/fun/rising_factorial.hpp>
#include <stan/math/prim/fun/round.hpp>
#include <stan/math/prim/fun/sign.hpp>
#include <stan/math/prim/fun/size_zero.hpp>
#include <stan/math/prim/fun/square.hpp>
#include <stan/math/prim/fun/squared_distance.hpp>
#include <stan/math/prim/fun/sqrt.hpp>
#include <stan/math/prim/fun/step.hpp>
#include <stan/math/prim/fun/tgamma.hpp>
#include <stan/math/prim/fun/trigamma.hpp>
#include <stan/math/prim/fun/trunc.hpp>
#include <stan/math/prim/fun/ub_constrain.hpp>
#include <stan/math/prim/fun/ub_free.hpp>
#include <stan/math/prim/fun/value_of.hpp>
#include <stan/math/prim/fun/value_of_rec.hpp>

#include <stan/math/prim/prob/bernoulli_ccdf_log.hpp>
#include <stan/math/prim/prob/bernoulli_cdf.hpp>
#include <stan/math/prim/prob/bernoulli_cdf_log.hpp>
#include <stan/math/prim/prob/bernoulli_lccdf.hpp>
#include <stan/math/prim/prob/bernoulli_lcdf.hpp>
#include <stan/math/prim/prob/bernoulli_log.hpp>
#include <stan/math/prim/prob/bernoulli_logit_log.hpp>
#include <stan/math/prim/prob/bernoulli_logit_lpmf.hpp>
#include <stan/math/prim/prob/bernoulli_logit_rng.hpp>
#include <stan/math/prim/prob/bernoulli_lpmf.hpp>
#include <stan/math/prim/prob/bernoulli_rng.hpp>
#include <stan/math/prim/prob/beta_binomial_ccdf_log.hpp>
#include <stan/math/prim/prob/beta_binomial_cdf.hpp>
#include <stan/math/prim/prob/beta_binomial_cdf_log.hpp>
#include <stan/math/prim/prob/beta_binomial_lccdf.hpp>
#include <stan/math/prim/prob/beta_binomial_lcdf.hpp>
#include <stan/math/prim/prob/beta_binomial_log.hpp>
#include <stan/math/prim/prob/beta_binomial_lpmf.hpp>
#include <stan/math/prim/prob/beta_binomial_rng.hpp>
#include <stan/math/prim/prob/beta_ccdf_log.hpp>
#include <stan/math/prim/prob/beta_cdf.hpp>
#include <stan/math/prim/prob/beta_cdf_log.hpp>
#include <stan/math/prim/prob/beta_lccdf.hpp>
#include <stan/math/prim/prob/beta_lcdf.hpp>
#include <stan/math/prim/prob/beta_log.hpp>
#include <stan/math/prim/prob/beta_lpdf.hpp>
#include <stan/math/prim/prob/beta_rng.hpp>
#include <stan/math/prim/prob/beta_proportion_ccdf_log.hpp>
#include <stan/math/prim/prob/beta_proportion_cdf_log.hpp>
#include <stan/math/prim/prob/beta_proportion_lccdf.hpp>
#include <stan/math/prim/prob/beta_proportion_lcdf.hpp>
#include <stan/math/prim/prob/beta_proportion_log.hpp>
#include <stan/math/prim/prob/beta_proportion_lpdf.hpp>
#include <stan/math/prim/prob/beta_proportion_rng.hpp>
#include <stan/math/prim/prob/binomial_ccdf_log.hpp>
#include <stan/math/prim/prob/binomial_cdf.hpp>
#include <stan/math/prim/prob/binomial_cdf_log.hpp>
#include <stan/math/prim/prob/binomial_lccdf.hpp>
#include <stan/math/prim/prob/binomial_lcdf.hpp>
#include <stan/math/prim/prob/binomial_log.hpp>
#include <stan/math/prim/prob/binomial_lpmf.hpp>
#include <stan/math/prim/prob/binomial_rng.hpp>
#include <stan/math/prim/prob/binomial_logit_log.hpp>
#include <stan/math/prim/prob/binomial_logit_lpmf.hpp>
#include <stan/math/prim/prob/cauchy_ccdf_log.hpp>
#include <stan/math/prim/prob/cauchy_cdf.hpp>
#include <stan/math/prim/prob/cauchy_cdf_log.hpp>
#include <stan/math/prim/prob/cauchy_lccdf.hpp>
#include <stan/math/prim/prob/cauchy_lcdf.hpp>
#include <stan/math/prim/prob/cauchy_log.hpp>
#include <stan/math/prim/prob/cauchy_lpdf.hpp>
#include <stan/math/prim/prob/cauchy_rng.hpp>
#include <stan/math/prim/prob/chi_square_ccdf_log.hpp>
#include <stan/math/prim/prob/chi_square_cdf.hpp>
#include <stan/math/prim/prob/chi_square_cdf_log.hpp>
#include <stan/math/prim/prob/chi_square_lccdf.hpp>
#include <stan/math/prim/prob/chi_square_lcdf.hpp>
#include <stan/math/prim/prob/chi_square_log.hpp>
#include <stan/math/prim/prob/chi_square_lpdf.hpp>
#include <stan/math/prim/prob/chi_square_rng.hpp>
#include <stan/math/prim/prob/double_exponential_ccdf_log.hpp>
#include <stan/math/prim/prob/double_exponential_cdf.hpp>
#include <stan/math/prim/prob/double_exponential_cdf_log.hpp>
#include <stan/math/prim/prob/double_exponential_lccdf.hpp>
#include <stan/math/prim/prob/double_exponential_lcdf.hpp>
#include <stan/math/prim/prob/double_exponential_log.hpp>
#include <stan/math/prim/prob/double_exponential_lpdf.hpp>
#include <stan/math/prim/prob/double_exponential_rng.hpp>
#include <stan/math/prim/prob/exp_mod_normal_ccdf_log.hpp>
#include <stan/math/prim/prob/exp_mod_normal_cdf.hpp>
#include <stan/math/prim/prob/exp_mod_normal_cdf_log.hpp>
#include <stan/math/prim/prob/exp_mod_normal_lccdf.hpp>
#include <stan/math/prim/prob/exp_mod_normal_lcdf.hpp>
#include <stan/math/prim/prob/exp_mod_normal_log.hpp>
#include <stan/math/prim/prob/exp_mod_normal_lpdf.hpp>
#include <stan/math/prim/prob/exp_mod_normal_rng.hpp>
#include <stan/math/prim/prob/exponential_ccdf_log.hpp>
#include <stan/math/prim/prob/exponential_cdf.hpp>
#include <stan/math/prim/prob/exponential_cdf_log.hpp>
#include <stan/math/prim/prob/exponential_lccdf.hpp>
#include <stan/math/prim/prob/exponential_lcdf.hpp>
#include <stan/math/prim/prob/exponential_log.hpp>
#include <stan/math/prim/prob/exponential_lpdf.hpp>
#include <stan/math/prim/prob/exponential_rng.hpp>
#include <stan/math/prim/prob/frechet_ccdf_log.hpp>
#include <stan/math/prim/prob/frechet_cdf.hpp>
#include <stan/math/prim/prob/frechet_cdf_log.hpp>
#include <stan/math/prim/prob/frechet_lccdf.hpp>
#include <stan/math/prim/prob/frechet_lcdf.hpp>
#include <stan/math/prim/prob/frechet_log.hpp>
#include <stan/math/prim/prob/frechet_lpdf.hpp>
#include <stan/math/prim/prob/frechet_rng.hpp>
#include <stan/math/prim/prob/gamma_ccdf_log.hpp>
#include <stan/math/prim/prob/gamma_cdf.hpp>
#include <stan/math/prim/prob/gamma_cdf_log.hpp>
#include <stan/math/prim/prob/gamma_lccdf.hpp>
#include <stan/math/prim/prob/gamma_lcdf.hpp>
#include <stan/math/prim/prob/gamma_log.hpp>
#include <stan/math/prim/prob/gamma_lpdf.hpp>
#include <stan/math/prim/prob/gamma_rng.hpp>
#include <stan/math/prim/prob/gumbel_ccdf_log.hpp>
#include <stan/math/prim/prob/gumbel_cdf.hpp>
#include <stan/math/prim/prob/gumbel_cdf_log.hpp>
#include <stan/math/prim/prob/gumbel_lccdf.hpp>
#include <stan/math/prim/prob/gumbel_lcdf.hpp>
#include <stan/math/prim/prob/gumbel_log.hpp>
#include <stan/math/prim/prob/gumbel_lpdf.hpp>
#include <stan/math/prim/prob/gumbel_rng.hpp>
#include <stan/math/prim/prob/hypergeometric_log.hpp>
#include <stan/math/prim/prob/hypergeometric_lpmf.hpp>
#include <stan/math/prim/prob/hypergeometric_rng.hpp>
#include <stan/math/prim/prob/inv_chi_square_ccdf_log.hpp>
#include <stan/math/prim/prob/inv_chi_square_cdf.hpp>
#include <stan/math/prim/prob/inv_chi_square_cdf_log.hpp>
#include <stan/math/prim/prob/inv_chi_square_lccdf.hpp>
#include <stan/math/prim/prob/inv_chi_square_lcdf.hpp>
#include <stan/math/prim/prob/inv_chi_square_log.hpp>
#include <stan/math/prim/prob/inv_chi_square_lpdf.hpp>
#include <stan/math/prim/prob/inv_chi_square_rng.hpp>
#include <stan/math/prim/prob/inv_gamma_ccdf_log.hpp>
#include <stan/math/prim/prob/inv_gamma_cdf.hpp>
#include <stan/math/prim/prob/inv_gamma_cdf_log.hpp>
#include <stan/math/prim/prob/inv_gamma_lccdf.hpp>
#include <stan/math/prim/prob/inv_gamma_lcdf.hpp>
#include <stan/math/prim/prob/inv_gamma_log.hpp>
#include <stan/math/prim/prob/inv_gamma_lpdf.hpp>
#include <stan/math/prim/prob/inv_gamma_rng.hpp>
#include <stan/math/prim/prob/logistic_ccdf_log.hpp>
#include <stan/math/prim/prob/logistic_cdf.hpp>
#include <stan/math/prim/prob/logistic_cdf_log.hpp>
#include <stan/math/prim/prob/logistic_lccdf.hpp>
#include <stan/math/prim/prob/logistic_lcdf.hpp>
#include <stan/math/prim/prob/logistic_log.hpp>
#include <stan/math/prim/prob/logistic_lpdf.hpp>
#include <stan/math/prim/prob/logistic_rng.hpp>
#include <stan/math/prim/prob/lognormal_ccdf_log.hpp>
#include <stan/math/prim/prob/lognormal_cdf.hpp>
#include <stan/math/prim/prob/lognormal_cdf_log.hpp>
#include <stan/math/prim/prob/lognormal_lccdf.hpp>
#include <stan/math/prim/prob/lognormal_lcdf.hpp>
#include <stan/math/prim/prob/lognormal_log.hpp>
#include <stan/math/prim/prob/lognormal_lpdf.hpp>
#include <stan/math/prim/prob/lognormal_rng.hpp>
#include <stan/math/prim/prob/neg_binomial_2_ccdf_log.hpp>
#include <stan/math/prim/prob/neg_binomial_2_cdf.hpp>
#include <stan/math/prim/prob/neg_binomial_2_cdf_log.hpp>
#include <stan/math/prim/prob/neg_binomial_2_lccdf.hpp>
#include <stan/math/prim/prob/neg_binomial_2_lcdf.hpp>
#include <stan/math/prim/prob/neg_binomial_2_log.hpp>
#include <stan/math/prim/prob/neg_binomial_2_lpmf.hpp>
#include <stan/math/prim/prob/neg_binomial_2_rng.hpp>
#include <stan/math/prim/prob/neg_binomial_2_log_log.hpp>
#include <stan/math/prim/prob/neg_binomial_2_log_lpmf.hpp>
#include <stan/math/prim/prob/neg_binomial_2_log_rng.hpp>
#include <stan/math/prim/prob/neg_binomial_ccdf_log.hpp>
#include <stan/math/prim/prob/neg_binomial_cdf.hpp>
#include <stan/math/prim/prob/neg_binomial_cdf_log.hpp>
#include <stan/math/prim/prob/neg_binomial_lccdf.hpp>
#include <stan/math/prim/prob/neg_binomial_lcdf.hpp>
#include <stan/math/prim/prob/neg_binomial_log.hpp>
#include <stan/math/prim/prob/neg_binomial_lpmf.hpp>
#include <stan/math/prim/prob/neg_binomial_rng.hpp>
#include <stan/math/prim/prob/normal_ccdf_log.hpp>
#include <stan/math/prim/prob/normal_cdf.hpp>
#include <stan/math/prim/prob/normal_cdf_log.hpp>
#include <stan/math/prim/prob/normal_lccdf.hpp>
#include <stan/math/prim/prob/normal_lcdf.hpp>
#include <stan/math/prim/prob/normal_log.hpp>
#include <stan/math/prim/prob/normal_lpdf.hpp>
#include <stan/math/prim/prob/normal_rng.hpp>
#include <stan/math/prim/prob/normal_sufficient_log.hpp>
#include <stan/math/prim/prob/normal_sufficient_lpdf.hpp>
#include <stan/math/prim/prob/pareto_ccdf_log.hpp>
#include <stan/math/prim/prob/pareto_cdf.hpp>
#include <stan/math/prim/prob/pareto_cdf_log.hpp>
#include <stan/math/prim/prob/pareto_lccdf.hpp>
#include <stan/math/prim/prob/pareto_lcdf.hpp>
#include <stan/math/prim/prob/pareto_log.hpp>
#include <stan/math/prim/prob/pareto_lpdf.hpp>
#include <stan/math/prim/prob/pareto_rng.hpp>
#include <stan/math/prim/prob/pareto_type_2_ccdf_log.hpp>
#include <stan/math/prim/prob/pareto_type_2_cdf.hpp>
#include <stan/math/prim/prob/pareto_type_2_cdf_log.hpp>
#include <stan/math/prim/prob/pareto_type_2_lccdf.hpp>
#include <stan/math/prim/prob/pareto_type_2_lcdf.hpp>
#include <stan/math/prim/prob/pareto_type_2_log.hpp>
#include <stan/math/prim/prob/pareto_type_2_lpdf.hpp>
#include <stan/math/prim/prob/pareto_type_2_rng.hpp>
#include <stan/math/prim/prob/poisson_ccdf_log.hpp>
#include <stan/math/prim/prob/poisson_cdf.hpp>
#include <stan/math/prim/prob/poisson_cdf_log.hpp>
#include <stan/math/prim/prob/poisson_lccdf.hpp>
#include <stan/math/prim/prob/poisson_lcdf.hpp>
#include <stan/math/prim/prob/poisson_log.hpp>
#include <stan/math/prim/prob/poisson_lpmf.hpp>
#include <stan/math/prim/prob/poisson_rng.hpp>
#include <stan/math/prim/prob/poisson_log_log.hpp>
#include <stan/math/prim/prob/poisson_log_lpmf.hpp>
#include <stan/math/prim/prob/poisson_log_rng.hpp>
#include <stan/math/prim/prob/rayleigh_ccdf_log.hpp>
#include <stan/math/prim/prob/rayleigh_cdf.hpp>
#include <stan/math/prim/prob/rayleigh_cdf_log.hpp>
#include <stan/math/prim/prob/rayleigh_lccdf.hpp>
#include <stan/math/prim/prob/rayleigh_lcdf.hpp>
#include <stan/math/prim/prob/rayleigh_log.hpp>
#include <stan/math/prim/prob/rayleigh_lpdf.hpp>
#include <stan/math/prim/prob/rayleigh_rng.hpp>
#include <stan/math/prim/prob/scaled_inv_chi_square_ccdf_log.hpp>
#include <stan/math/prim/prob/scaled_inv_chi_square_cdf.hpp>
#include <stan/math/prim/prob/scaled_inv_chi_square_cdf_log.hpp>
#include <stan/math/prim/prob/scaled_inv_chi_square_lccdf.hpp>
#include <stan/math/prim/prob/scaled_inv_chi_square_lcdf.hpp>
#include <stan/math/prim/prob/scaled_inv_chi_square_log.hpp>
#include <stan/math/prim/prob/scaled_inv_chi_square_lpdf.hpp>
#include <stan/math/prim/prob/scaled_inv_chi_square_rng.hpp>
#include <stan/math/prim/prob/skew_normal_ccdf_log.hpp>
#include <stan/math/prim/prob/skew_normal_cdf.hpp>
#include <stan/math/prim/prob/skew_normal_cdf_log.hpp>
#include <stan/math/prim/prob/skew_normal_lccdf.hpp>
#include <stan/math/prim/prob/skew_normal_lcdf.hpp>
#include <stan/math/prim/prob/skew_normal_log.hpp>
#include <stan/math/prim/prob/skew_normal_lpdf.hpp>
#include <stan/math/prim/prob/skew_normal_rng.hpp>
#include <stan/math/prim/prob/std_normal_lpdf.hpp>
#include <stan/math/prim/prob/std_normal_log.hpp>
#include <stan/math/prim/prob/student_t_ccdf_log.hpp>
#include <stan/math/prim/prob/student_t_cdf.hpp>
#include <stan/math/prim/prob/student_t_cdf_log.hpp>
#include <stan/math/prim/prob/student_t_lccdf.hpp>
#include <stan/math/prim/prob/student_t_lcdf.hpp>
#include <stan/math/prim/prob/student_t_log.hpp>
#include <stan/math/prim/prob/student_t_lpdf.hpp>
#include <stan/math/prim/prob/student_t_rng.hpp>
#include <stan/math/prim/prob/uniform_ccdf_log.hpp>
#include <stan/math/prim/prob/uniform_cdf.hpp>
#include <stan/math/prim/prob/uniform_cdf_log.hpp>
#include <stan/math/prim/prob/uniform_lccdf.hpp>
#include <stan/math/prim/prob/uniform_lcdf.hpp>
#include <stan/math/prim/prob/uniform_log.hpp>
#include <stan/math/prim/prob/uniform_lpdf.hpp>
#include <stan/math/prim/prob/uniform_rng.hpp>
#include <stan/math/prim/prob/von_mises_log.hpp>
#include <stan/math/prim/prob/von_mises_lpdf.hpp>
#include <stan/math/prim/prob/von_mises_rng.hpp>
#include <stan/math/prim/prob/weibull_ccdf_log.hpp>
#include <stan/math/prim/prob/weibull_cdf.hpp>
#include <stan/math/prim/prob/weibull_cdf_log.hpp>
#include <stan/math/prim/prob/weibull_lccdf.hpp>
#include <stan/math/prim/prob/weibull_lcdf.hpp>
#include <stan/math/prim/prob/weibull_log.hpp>
#include <stan/math/prim/prob/weibull_lpdf.hpp>
#include <stan/math/prim/prob/weibull_rng.hpp>
#include <stan/math/prim/prob/wiener_log.hpp>
#include <stan/math/prim/prob/wiener_lpdf.hpp>

#include <cmath>

#endif
