var searchData=
[
  ['lambert_5fw_2ehpp_0',['lambert_w.hpp',['../prim_2fun_2lambert__w_8hpp.html',1,'(Global Namespace)'],['../fwd_2fun_2lambert__w_8hpp.html',1,'(Global Namespace)'],['../rev_2fun_2lambert__w_8hpp.html',1,'(Global Namespace)']]],
  ['lb_5fconstrain_2ehpp_1',['lb_constrain.hpp',['../prim_2constraint_2lb__constrain_8hpp.html',1,'(Global Namespace)'],['../rev_2constraint_2lb__constrain_8hpp.html',1,'(Global Namespace)'],['../opencl_2rev_2constraint_2lb__constrain_8hpp.html',1,'(Global Namespace)'],['../opencl_2prim_2constraint_2lb__constrain_8hpp.html',1,'(Global Namespace)']]],
  ['lb_5ffree_2ehpp_2',['lb_free.hpp',['../lb__free_8hpp.html',1,'']]],
  ['lbeta_2ehpp_3',['lbeta.hpp',['../fwd_2fun_2lbeta_8hpp.html',1,'(Global Namespace)'],['../opencl_2kernels_2device__functions_2lbeta_8hpp.html',1,'(Global Namespace)'],['../opencl_2rev_2lbeta_8hpp.html',1,'(Global Namespace)'],['../prim_2fun_2lbeta_8hpp.html',1,'(Global Namespace)'],['../rev_2fun_2lbeta_8hpp.html',1,'(Global Namespace)']]],
  ['ldexp_2ehpp_4',['ldexp.hpp',['../rev_2fun_2ldexp_8hpp.html',1,'(Global Namespace)'],['../prim_2fun_2ldexp_8hpp.html',1,'(Global Namespace)'],['../opencl_2rev_2ldexp_8hpp.html',1,'(Global Namespace)'],['../fwd_2fun_2ldexp_8hpp.html',1,'(Global Namespace)']]],
  ['ldlt_5ffactor_2ehpp_5',['LDLT_factor.hpp',['../prim_2fun_2_l_d_l_t__factor_8hpp.html',1,'(Global Namespace)'],['../rev_2fun_2_l_d_l_t__factor_8hpp.html',1,'(Global Namespace)']]],
  ['lgamma_2ehpp_6',['lgamma.hpp',['../rev_2fun_2lgamma_8hpp.html',1,'(Global Namespace)'],['../prim_2fun_2lgamma_8hpp.html',1,'(Global Namespace)'],['../opencl_2rev_2lgamma_8hpp.html',1,'(Global Namespace)'],['../fwd_2fun_2lgamma_8hpp.html',1,'(Global Namespace)']]],
  ['lgamma_5fstirling_2ehpp_7',['lgamma_stirling.hpp',['../opencl_2kernels_2device__functions_2lgamma__stirling_8hpp.html',1,'(Global Namespace)'],['../prim_2fun_2lgamma__stirling_8hpp.html',1,'(Global Namespace)']]],
  ['lgamma_5fstirling_5fdiff_2ehpp_8',['lgamma_stirling_diff.hpp',['../opencl_2kernels_2device__functions_2lgamma__stirling__diff_8hpp.html',1,'(Global Namespace)'],['../prim_2fun_2lgamma__stirling__diff_8hpp.html',1,'(Global Namespace)']]],
  ['linspaced_5farray_2ehpp_9',['linspaced_array.hpp',['../linspaced__array_8hpp.html',1,'']]],
  ['linspaced_5fint_5farray_2ehpp_10',['linspaced_int_array.hpp',['../linspaced__int__array_8hpp.html',1,'']]],
  ['linspaced_5frow_5fvector_2ehpp_11',['linspaced_row_vector.hpp',['../linspaced__row__vector_8hpp.html',1,'']]],
  ['linspaced_5fvector_2ehpp_12',['linspaced_vector.hpp',['../linspaced__vector_8hpp.html',1,'']]],
  ['lkj_5fcorr_5fcholesky_5flpdf_2ehpp_13',['lkj_corr_cholesky_lpdf.hpp',['../lkj__corr__cholesky__lpdf_8hpp.html',1,'']]],
  ['lkj_5fcorr_5fcholesky_5frng_2ehpp_14',['lkj_corr_cholesky_rng.hpp',['../lkj__corr__cholesky__rng_8hpp.html',1,'']]],
  ['lkj_5fcorr_5flpdf_2ehpp_15',['lkj_corr_lpdf.hpp',['../lkj__corr__lpdf_8hpp.html',1,'']]],
  ['lkj_5fcorr_5frng_2ehpp_16',['lkj_corr_rng.hpp',['../lkj__corr__rng_8hpp.html',1,'']]],
  ['lkj_5fcov_5flpdf_2ehpp_17',['lkj_cov_lpdf.hpp',['../lkj__cov__lpdf_8hpp.html',1,'']]],
  ['lmgamma_2ehpp_18',['lmgamma.hpp',['../rev_2fun_2lmgamma_8hpp.html',1,'(Global Namespace)'],['../prim_2fun_2lmgamma_8hpp.html',1,'(Global Namespace)'],['../fwd_2fun_2lmgamma_8hpp.html',1,'(Global Namespace)']]],
  ['lmultiply_2ehpp_19',['lmultiply.hpp',['../rev_2fun_2lmultiply_8hpp.html',1,'(Global Namespace)'],['../prim_2fun_2lmultiply_8hpp.html',1,'(Global Namespace)'],['../opencl_2rev_2lmultiply_8hpp.html',1,'(Global Namespace)'],['../opencl_2kernels_2device__functions_2lmultiply_8hpp.html',1,'(Global Namespace)'],['../fwd_2fun_2lmultiply_8hpp.html',1,'(Global Namespace)']]],
  ['load_2ehpp_20',['load.hpp',['../load_8hpp.html',1,'']]],
  ['log_2ehpp_21',['log.hpp',['../opencl_2rev_2log_8hpp.html',1,'(Global Namespace)'],['../prim_2fun_2log_8hpp.html',1,'(Global Namespace)'],['../rev_2fun_2log_8hpp.html',1,'(Global Namespace)'],['../fwd_2fun_2log_8hpp.html',1,'(Global Namespace)']]],
  ['log10_2ehpp_22',['log10.hpp',['../fwd_2fun_2log10_8hpp.html',1,'(Global Namespace)'],['../opencl_2rev_2log10_8hpp.html',1,'(Global Namespace)'],['../prim_2fun_2log10_8hpp.html',1,'(Global Namespace)'],['../rev_2fun_2log10_8hpp.html',1,'(Global Namespace)']]],
  ['log1m_2ehpp_23',['log1m.hpp',['../fwd_2fun_2log1m_8hpp.html',1,'(Global Namespace)'],['../opencl_2kernels_2device__functions_2log1m_8hpp.html',1,'(Global Namespace)'],['../opencl_2rev_2log1m_8hpp.html',1,'(Global Namespace)'],['../prim_2fun_2log1m_8hpp.html',1,'(Global Namespace)'],['../rev_2fun_2log1m_8hpp.html',1,'(Global Namespace)']]],
  ['log1m_5fexp_2ehpp_24',['log1m_exp.hpp',['../fwd_2fun_2log1m__exp_8hpp.html',1,'(Global Namespace)'],['../opencl_2kernels_2device__functions_2log1m__exp_8hpp.html',1,'(Global Namespace)'],['../opencl_2rev_2log1m__exp_8hpp.html',1,'(Global Namespace)'],['../prim_2fun_2log1m__exp_8hpp.html',1,'(Global Namespace)'],['../rev_2fun_2log1m__exp_8hpp.html',1,'(Global Namespace)']]],
  ['log1m_5finv_5flogit_2ehpp_25',['log1m_inv_logit.hpp',['../fwd_2fun_2log1m__inv__logit_8hpp.html',1,'(Global Namespace)'],['../opencl_2kernels_2device__functions_2log1m__inv__logit_8hpp.html',1,'(Global Namespace)'],['../rev_2fun_2log1m__inv__logit_8hpp.html',1,'(Global Namespace)'],['../prim_2fun_2log1m__inv__logit_8hpp.html',1,'(Global Namespace)'],['../opencl_2rev_2log1m__inv__logit_8hpp.html',1,'(Global Namespace)']]],
  ['log1p_2ehpp_26',['log1p.hpp',['../prim_2fun_2log1p_8hpp.html',1,'(Global Namespace)'],['../rev_2fun_2log1p_8hpp.html',1,'(Global Namespace)'],['../fwd_2fun_2log1p_8hpp.html',1,'(Global Namespace)'],['../opencl_2rev_2log1p_8hpp.html',1,'(Global Namespace)']]],
  ['log1p_5fexp_2ehpp_27',['log1p_exp.hpp',['../rev_2fun_2log1p__exp_8hpp.html',1,'(Global Namespace)'],['../prim_2fun_2log1p__exp_8hpp.html',1,'(Global Namespace)'],['../opencl_2rev_2log1p__exp_8hpp.html',1,'(Global Namespace)'],['../opencl_2kernels_2device__functions_2log1p__exp_8hpp.html',1,'(Global Namespace)'],['../fwd_2fun_2log1p__exp_8hpp.html',1,'(Global Namespace)']]],
  ['log2_2ehpp_28',['log2.hpp',['../rev_2fun_2log2_8hpp.html',1,'(Global Namespace)'],['../prim_2fun_2log2_8hpp.html',1,'(Global Namespace)'],['../opencl_2rev_2log2_8hpp.html',1,'(Global Namespace)'],['../fwd_2fun_2log2_8hpp.html',1,'(Global Namespace)']]],
  ['log_5fdeterminant_2ehpp_29',['log_determinant.hpp',['../rev_2fun_2log__determinant_8hpp.html',1,'(Global Namespace)'],['../prim_2fun_2log__determinant_8hpp.html',1,'(Global Namespace)'],['../fwd_2fun_2log__determinant_8hpp.html',1,'(Global Namespace)']]],
  ['log_5fdeterminant_5fldlt_2ehpp_30',['log_determinant_ldlt.hpp',['../prim_2fun_2log__determinant__ldlt_8hpp.html',1,'(Global Namespace)'],['../rev_2fun_2log__determinant__ldlt_8hpp.html',1,'(Global Namespace)']]],
  ['log_5fdeterminant_5fspd_2ehpp_31',['log_determinant_spd.hpp',['../prim_2fun_2log__determinant__spd_8hpp.html',1,'(Global Namespace)'],['../rev_2fun_2log__determinant__spd_8hpp.html',1,'(Global Namespace)']]],
  ['log_5fdiff_5fexp_2ehpp_32',['log_diff_exp.hpp',['../fwd_2fun_2log__diff__exp_8hpp.html',1,'(Global Namespace)'],['../opencl_2kernels_2device__functions_2log__diff__exp_8hpp.html',1,'(Global Namespace)'],['../opencl_2rev_2log__diff__exp_8hpp.html',1,'(Global Namespace)'],['../prim_2fun_2log__diff__exp_8hpp.html',1,'(Global Namespace)'],['../rev_2fun_2log__diff__exp_8hpp.html',1,'(Global Namespace)']]],
  ['log_5ffalling_5ffactorial_2ehpp_33',['log_falling_factorial.hpp',['../fwd_2fun_2log__falling__factorial_8hpp.html',1,'(Global Namespace)'],['../prim_2fun_2log__falling__factorial_8hpp.html',1,'(Global Namespace)'],['../rev_2fun_2log__falling__factorial_8hpp.html',1,'(Global Namespace)']]],
  ['log_5finv_5flogit_2ehpp_34',['log_inv_logit.hpp',['../prim_2fun_2log__inv__logit_8hpp.html',1,'(Global Namespace)'],['../rev_2fun_2log__inv__logit_8hpp.html',1,'(Global Namespace)'],['../opencl_2rev_2log__inv__logit_8hpp.html',1,'(Global Namespace)'],['../opencl_2kernels_2device__functions_2log__inv__logit_8hpp.html',1,'(Global Namespace)'],['../fwd_2fun_2log__inv__logit_8hpp.html',1,'(Global Namespace)']]],
  ['log_5finv_5flogit_5fdiff_2ehpp_35',['log_inv_logit_diff.hpp',['../fwd_2fun_2log__inv__logit__diff_8hpp.html',1,'(Global Namespace)'],['../opencl_2kernels_2device__functions_2log__inv__logit__diff_8hpp.html',1,'(Global Namespace)'],['../opencl_2rev_2log__inv__logit__diff_8hpp.html',1,'(Global Namespace)'],['../prim_2fun_2log__inv__logit__diff_8hpp.html',1,'(Global Namespace)'],['../rev_2fun_2log__inv__logit__diff_8hpp.html',1,'(Global Namespace)']]],
  ['log_5fmix_2ehpp_36',['log_mix.hpp',['../rev_2fun_2log__mix_8hpp.html',1,'(Global Namespace)'],['../prim_2fun_2log__mix_8hpp.html',1,'(Global Namespace)'],['../fwd_2fun_2log__mix_8hpp.html',1,'(Global Namespace)'],['../opencl_2prim_2log__mix_8hpp.html',1,'(Global Namespace)']]],
  ['log_5fmodified_5fbessel_5ffirst_5fkind_2ehpp_37',['log_modified_bessel_first_kind.hpp',['../log__modified__bessel__first__kind_8hpp.html',1,'']]],
  ['log_5frising_5ffactorial_2ehpp_38',['log_rising_factorial.hpp',['../rev_2fun_2log__rising__factorial_8hpp.html',1,'(Global Namespace)'],['../prim_2fun_2log__rising__factorial_8hpp.html',1,'(Global Namespace)'],['../fwd_2fun_2log__rising__factorial_8hpp.html',1,'(Global Namespace)']]],
  ['log_5fsoftmax_2ehpp_39',['log_softmax.hpp',['../opencl_2prim_2log__softmax_8hpp.html',1,'(Global Namespace)'],['../fwd_2fun_2log__softmax_8hpp.html',1,'(Global Namespace)'],['../opencl_2rev_2log__softmax_8hpp.html',1,'(Global Namespace)'],['../prim_2fun_2log__softmax_8hpp.html',1,'(Global Namespace)'],['../rev_2fun_2log__softmax_8hpp.html',1,'(Global Namespace)']]],
  ['log_5fsum_5fexp_2ehpp_40',['log_sum_exp.hpp',['../fwd_2fun_2log__sum__exp_8hpp.html',1,'(Global Namespace)'],['../opencl_2prim_2log__sum__exp_8hpp.html',1,'(Global Namespace)'],['../opencl_2rev_2log__sum__exp_8hpp.html',1,'(Global Namespace)'],['../prim_2fun_2log__sum__exp_8hpp.html',1,'(Global Namespace)'],['../rev_2fun_2log__sum__exp_8hpp.html',1,'(Global Namespace)']]],
  ['log_5fsum_5fexp_5fsigned_2ehpp_41',['log_sum_exp_signed.hpp',['../log__sum__exp__signed_8hpp.html',1,'']]],
  ['logb_2ehpp_42',['logb.hpp',['../logb_8hpp.html',1,'']]],
  ['logical_5fand_2ehpp_43',['logical_and.hpp',['../logical__and_8hpp.html',1,'']]],
  ['logical_5feq_2ehpp_44',['logical_eq.hpp',['../logical__eq_8hpp.html',1,'']]],
  ['logical_5fgt_2ehpp_45',['logical_gt.hpp',['../logical__gt_8hpp.html',1,'']]],
  ['logical_5fgte_2ehpp_46',['logical_gte.hpp',['../logical__gte_8hpp.html',1,'']]],
  ['logical_5flt_2ehpp_47',['logical_lt.hpp',['../logical__lt_8hpp.html',1,'']]],
  ['logical_5flte_2ehpp_48',['logical_lte.hpp',['../logical__lte_8hpp.html',1,'']]],
  ['logical_5fnegation_2ehpp_49',['logical_negation.hpp',['../logical__negation_8hpp.html',1,'']]],
  ['logical_5fneq_2ehpp_50',['logical_neq.hpp',['../logical__neq_8hpp.html',1,'']]],
  ['logical_5for_2ehpp_51',['logical_or.hpp',['../logical__or_8hpp.html',1,'']]],
  ['logistic_5fccdf_5flog_2ehpp_52',['logistic_ccdf_log.hpp',['../logistic__ccdf__log_8hpp.html',1,'']]],
  ['logistic_5fcdf_2ehpp_53',['logistic_cdf.hpp',['../prim_2prob_2logistic__cdf_8hpp.html',1,'(Global Namespace)'],['../opencl_2prim_2logistic__cdf_8hpp.html',1,'(Global Namespace)']]],
  ['logistic_5fcdf_5flog_2ehpp_54',['logistic_cdf_log.hpp',['../logistic__cdf__log_8hpp.html',1,'']]],
  ['logistic_5flccdf_2ehpp_55',['logistic_lccdf.hpp',['../opencl_2prim_2logistic__lccdf_8hpp.html',1,'(Global Namespace)'],['../prim_2prob_2logistic__lccdf_8hpp.html',1,'(Global Namespace)']]],
  ['logistic_5flcdf_2ehpp_56',['logistic_lcdf.hpp',['../opencl_2prim_2logistic__lcdf_8hpp.html',1,'(Global Namespace)'],['../prim_2prob_2logistic__lcdf_8hpp.html',1,'(Global Namespace)']]],
  ['logistic_5flpdf_2ehpp_57',['logistic_lpdf.hpp',['../prim_2prob_2logistic__lpdf_8hpp.html',1,'(Global Namespace)'],['../opencl_2prim_2logistic__lpdf_8hpp.html',1,'(Global Namespace)']]],
  ['logistic_5frng_2ehpp_58',['logistic_rng.hpp',['../logistic__rng_8hpp.html',1,'']]],
  ['logit_2ehpp_59',['logit.hpp',['../opencl_2rev_2logit_8hpp.html',1,'(Global Namespace)'],['../prim_2fun_2logit_8hpp.html',1,'(Global Namespace)'],['../rev_2fun_2logit_8hpp.html',1,'(Global Namespace)'],['../opencl_2kernels_2device__functions_2logit_8hpp.html',1,'(Global Namespace)'],['../fwd_2fun_2logit_8hpp.html',1,'(Global Namespace)']]],
  ['loglogistic_5fcdf_2ehpp_60',['loglogistic_cdf.hpp',['../loglogistic__cdf_8hpp.html',1,'']]],
  ['loglogistic_5flpdf_2ehpp_61',['loglogistic_lpdf.hpp',['../loglogistic__lpdf_8hpp.html',1,'']]],
  ['loglogistic_5frng_2ehpp_62',['loglogistic_rng.hpp',['../loglogistic__rng_8hpp.html',1,'']]],
  ['lognormal_5fccdf_5flog_2ehpp_63',['lognormal_ccdf_log.hpp',['../lognormal__ccdf__log_8hpp.html',1,'']]],
  ['lognormal_5fcdf_2ehpp_64',['lognormal_cdf.hpp',['../opencl_2prim_2lognormal__cdf_8hpp.html',1,'(Global Namespace)'],['../prim_2prob_2lognormal__cdf_8hpp.html',1,'(Global Namespace)']]],
  ['lognormal_5fcdf_5flog_2ehpp_65',['lognormal_cdf_log.hpp',['../lognormal__cdf__log_8hpp.html',1,'']]],
  ['lognormal_5flccdf_2ehpp_66',['lognormal_lccdf.hpp',['../prim_2prob_2lognormal__lccdf_8hpp.html',1,'(Global Namespace)'],['../opencl_2prim_2lognormal__lccdf_8hpp.html',1,'(Global Namespace)']]],
  ['lognormal_5flcdf_2ehpp_67',['lognormal_lcdf.hpp',['../prim_2prob_2lognormal__lcdf_8hpp.html',1,'(Global Namespace)'],['../opencl_2prim_2lognormal__lcdf_8hpp.html',1,'(Global Namespace)']]],
  ['lognormal_5flpdf_2ehpp_68',['lognormal_lpdf.hpp',['../opencl_2prim_2lognormal__lpdf_8hpp.html',1,'(Global Namespace)'],['../prim_2prob_2lognormal__lpdf_8hpp.html',1,'(Global Namespace)']]],
  ['lognormal_5frng_2ehpp_69',['lognormal_rng.hpp',['../lognormal__rng_8hpp.html',1,'']]],
  ['lub_5fconstrain_2ehpp_70',['lub_constrain.hpp',['../rev_2constraint_2lub__constrain_8hpp.html',1,'(Global Namespace)'],['../prim_2constraint_2lub__constrain_8hpp.html',1,'(Global Namespace)'],['../opencl_2rev_2constraint_2lub__constrain_8hpp.html',1,'(Global Namespace)'],['../opencl_2prim_2constraint_2lub__constrain_8hpp.html',1,'(Global Namespace)']]],
  ['lub_5ffree_2ehpp_71',['lub_free.hpp',['../lub__free_8hpp.html',1,'']]]
];
