var searchData=
[
  ['tail_2ehpp_0',['tail.hpp',['../prim_2fun_2tail_8hpp.html',1,'(Global Namespace)'],['../opencl_2prim_2tail_8hpp.html',1,'(Global Namespace)']]],
  ['tan_2ehpp_1',['tan.hpp',['../fwd_2fun_2tan_8hpp.html',1,'(Global Namespace)'],['../rev_2fun_2tan_8hpp.html',1,'(Global Namespace)'],['../opencl_2rev_2tan_8hpp.html',1,'(Global Namespace)'],['../prim_2fun_2tan_8hpp.html',1,'(Global Namespace)']]],
  ['tanh_2ehpp_2',['tanh.hpp',['../fwd_2fun_2tanh_8hpp.html',1,'(Global Namespace)'],['../rev_2fun_2tanh_8hpp.html',1,'(Global Namespace)'],['../opencl_2rev_2tanh_8hpp.html',1,'(Global Namespace)'],['../prim_2fun_2tanh_8hpp.html',1,'(Global Namespace)']]],
  ['tcrossprod_2ehpp_3',['tcrossprod.hpp',['../fwd_2fun_2tcrossprod_8hpp.html',1,'(Global Namespace)'],['../opencl_2prim_2tcrossprod_8hpp.html',1,'(Global Namespace)'],['../opencl_2rev_2tcrossprod_8hpp.html',1,'(Global Namespace)'],['../prim_2fun_2tcrossprod_8hpp.html',1,'(Global Namespace)'],['../rev_2fun_2tcrossprod_8hpp.html',1,'(Global Namespace)']]],
  ['tgamma_2ehpp_4',['tgamma.hpp',['../rev_2fun_2tgamma_8hpp.html',1,'(Global Namespace)'],['../prim_2fun_2tgamma_8hpp.html',1,'(Global Namespace)'],['../opencl_2rev_2tgamma_8hpp.html',1,'(Global Namespace)'],['../fwd_2fun_2tgamma_8hpp.html',1,'(Global Namespace)']]],
  ['threading_5ftbb_2emd_5',['threading_tbb.md',['../threading__tbb_8md.html',1,'']]],
  ['throw_5fdomain_5ferror_2ehpp_6',['throw_domain_error.hpp',['../throw__domain__error_8hpp.html',1,'']]],
  ['throw_5fdomain_5ferror_5fmat_2ehpp_7',['throw_domain_error_mat.hpp',['../throw__domain__error__mat_8hpp.html',1,'']]],
  ['throw_5fdomain_5ferror_5fvec_2ehpp_8',['throw_domain_error_vec.hpp',['../throw__domain__error__vec_8hpp.html',1,'']]],
  ['to_5farena_2ehpp_9',['to_arena.hpp',['../rev_2fun_2to__arena_8hpp.html',1,'(Global Namespace)'],['../opencl_2rev_2to__arena_8hpp.html',1,'(Global Namespace)']]],
  ['to_5farray_5f1d_2ehpp_10',['to_array_1d.hpp',['../opencl_2prim_2to__array__1d_8hpp.html',1,'(Global Namespace)'],['../prim_2fun_2to__array__1d_8hpp.html',1,'(Global Namespace)']]],
  ['to_5farray_5f2d_2ehpp_11',['to_array_2d.hpp',['../prim_2fun_2to__array__2d_8hpp.html',1,'(Global Namespace)'],['../opencl_2prim_2to__array__2d_8hpp.html',1,'(Global Namespace)']]],
  ['to_5fcomplex_2ehpp_12',['to_complex.hpp',['../to__complex_8hpp.html',1,'']]],
  ['to_5ffvar_2ehpp_13',['to_fvar.hpp',['../to__fvar_8hpp.html',1,'']]],
  ['to_5fint_2ehpp_14',['to_int.hpp',['../to__int_8hpp.html',1,'']]],
  ['to_5fmatrix_2ehpp_15',['to_matrix.hpp',['../prim_2fun_2to__matrix_8hpp.html',1,'(Global Namespace)'],['../opencl_2rev_2to__matrix_8hpp.html',1,'(Global Namespace)'],['../opencl_2prim_2to__matrix_8hpp.html',1,'(Global Namespace)']]],
  ['to_5fref_2ehpp_16',['to_ref.hpp',['../to__ref_8hpp.html',1,'']]],
  ['to_5fref_5ffor_5fopencl_2ehpp_17',['to_ref_for_opencl.hpp',['../to__ref__for__opencl_8hpp.html',1,'']]],
  ['to_5frow_5fvector_2ehpp_18',['to_row_vector.hpp',['../opencl_2prim_2to__row__vector_8hpp.html',1,'(Global Namespace)'],['../prim_2fun_2to__row__vector_8hpp.html',1,'(Global Namespace)']]],
  ['to_5fvar_2ehpp_19',['to_var.hpp',['../to__var_8hpp.html',1,'']]],
  ['to_5fvar_5fvalue_2ehpp_20',['to_var_value.hpp',['../to__var__value_8hpp.html',1,'']]],
  ['to_5fvector_2ehpp_21',['to_vector.hpp',['../opencl_2prim_2to__vector_8hpp.html',1,'(Global Namespace)'],['../prim_2fun_2to__vector_8hpp.html',1,'(Global Namespace)'],['../rev_2fun_2to__vector_8hpp.html',1,'(Global Namespace)']]],
  ['trace_2ehpp_22',['trace.hpp',['../prim_2fun_2trace_8hpp.html',1,'(Global Namespace)'],['../opencl_2rev_2trace_8hpp.html',1,'(Global Namespace)'],['../opencl_2prim_2trace_8hpp.html',1,'(Global Namespace)'],['../rev_2fun_2trace_8hpp.html',1,'(Global Namespace)']]],
  ['trace_5fgen_5finv_5fquad_5fform_5fldlt_2ehpp_23',['trace_gen_inv_quad_form_ldlt.hpp',['../prim_2fun_2trace__gen__inv__quad__form__ldlt_8hpp.html',1,'(Global Namespace)'],['../rev_2fun_2trace__gen__inv__quad__form__ldlt_8hpp.html',1,'(Global Namespace)']]],
  ['trace_5fgen_5fquad_5fform_2ehpp_24',['trace_gen_quad_form.hpp',['../prim_2fun_2trace__gen__quad__form_8hpp.html',1,'(Global Namespace)'],['../rev_2fun_2trace__gen__quad__form_8hpp.html',1,'(Global Namespace)']]],
  ['trace_5finv_5fquad_5fform_5fldlt_2ehpp_25',['trace_inv_quad_form_ldlt.hpp',['../rev_2fun_2trace__inv__quad__form__ldlt_8hpp.html',1,'(Global Namespace)'],['../prim_2fun_2trace__inv__quad__form__ldlt_8hpp.html',1,'(Global Namespace)']]],
  ['trace_5fquad_5fform_2ehpp_26',['trace_quad_form.hpp',['../prim_2fun_2trace__quad__form_8hpp.html',1,'(Global Namespace)'],['../fwd_2fun_2trace__quad__form_8hpp.html',1,'(Global Namespace)'],['../rev_2fun_2trace__quad__form_8hpp.html',1,'(Global Namespace)']]],
  ['transpose_2ehpp_27',['transpose.hpp',['../opencl_2kernel__generator_2transpose_8hpp.html',1,'(Global Namespace)'],['../opencl_2rev_2transpose_8hpp.html',1,'(Global Namespace)'],['../prim_2fun_2transpose_8hpp.html',1,'(Global Namespace)']]],
  ['tri_5finverse_2ehpp_28',['tri_inverse.hpp',['../tri__inverse_8hpp.html',1,'']]],
  ['tridiagonalization_2ehpp_29',['tridiagonalization.hpp',['../tridiagonalization_8hpp.html',1,'(Global Namespace)'],['../kernels_2tridiagonalization_8hpp.html',1,'(Global Namespace)']]],
  ['trigamma_2ehpp_30',['trigamma.hpp',['../fwd_2fun_2trigamma_8hpp.html',1,'(Global Namespace)'],['../opencl_2kernels_2device__functions_2trigamma_8hpp.html',1,'(Global Namespace)'],['../prim_2fun_2trigamma_8hpp.html',1,'(Global Namespace)'],['../rev_2fun_2trigamma_8hpp.html',1,'(Global Namespace)']]],
  ['trunc_2ehpp_31',['trunc.hpp',['../opencl_2rev_2trunc_8hpp.html',1,'(Global Namespace)'],['../prim_2fun_2trunc_8hpp.html',1,'(Global Namespace)'],['../rev_2fun_2trunc_8hpp.html',1,'(Global Namespace)'],['../fwd_2fun_2trunc_8hpp.html',1,'(Global Namespace)']]],
  ['type_5fstr_2ehpp_32',['type_str.hpp',['../type__str_8hpp.html',1,'']]],
  ['typedefs_2ehpp_33',['typedefs.hpp',['../prim_2fun_2typedefs_8hpp.html',1,'(Global Namespace)'],['../mix_2fun_2typedefs_8hpp.html',1,'(Global Namespace)'],['../fwd_2fun_2typedefs_8hpp.html',1,'(Global Namespace)'],['../rev_2core_2typedefs_8hpp.html',1,'(Global Namespace)']]]
];
