var searchData=
[
  ['abs_2ehpp_0',['abs.hpp',['../fwd_2fun_2abs_8hpp.html',1,'(Global Namespace)'],['../prim_2fun_2abs_8hpp.html',1,'(Global Namespace)'],['../rev_2fun_2abs_8hpp.html',1,'(Global Namespace)']]],
  ['accumulate_5fadjoints_2ehpp_1',['accumulate_adjoints.hpp',['../accumulate__adjoints_8hpp.html',1,'']]],
  ['accumulator_2ehpp_2',['accumulator.hpp',['../fwd_2fun_2accumulator_8hpp.html',1,'(Global Namespace)'],['../prim_2fun_2accumulator_8hpp.html',1,'(Global Namespace)'],['../rev_2fun_2accumulator_8hpp.html',1,'(Global Namespace)']]],
  ['acos_2ehpp_3',['acos.hpp',['../rev_2fun_2acos_8hpp.html',1,'(Global Namespace)'],['../prim_2fun_2acos_8hpp.html',1,'(Global Namespace)'],['../opencl_2rev_2acos_8hpp.html',1,'(Global Namespace)'],['../fwd_2fun_2acos_8hpp.html',1,'(Global Namespace)']]],
  ['acosh_2ehpp_4',['acosh.hpp',['../fwd_2fun_2acosh_8hpp.html',1,'(Global Namespace)'],['../opencl_2rev_2acosh_8hpp.html',1,'(Global Namespace)'],['../prim_2fun_2acosh_8hpp.html',1,'(Global Namespace)'],['../rev_2fun_2acosh_8hpp.html',1,'(Global Namespace)']]],
  ['ad_5fpromotable_2ehpp_5',['ad_promotable.hpp',['../ad__promotable_8hpp.html',1,'']]],
  ['add_2ehpp_6',['add.hpp',['../opencl_2rev_2add_8hpp.html',1,'(Global Namespace)'],['../opencl_2kernels_2add_8hpp.html',1,'(Global Namespace)'],['../prim_2fun_2add_8hpp.html',1,'(Global Namespace)']]],
  ['add_5fdiag_2ehpp_7',['add_diag.hpp',['../opencl_2prim_2add__diag_8hpp.html',1,'(Global Namespace)'],['../opencl_2rev_2add__diag_8hpp.html',1,'(Global Namespace)'],['../prim_2fun_2add__diag_8hpp.html',1,'(Global Namespace)']]],
  ['add_5fnew_5fopencl_5fkernel_2emd_8',['add_new_opencl_kernel.md',['../add__new__opencl__kernel_8md.html',1,'']]],
  ['adding_5fnew_5fdistributions_2emd_9',['adding_new_distributions.md',['../adding__new__distributions_8md.html',1,'']]],
  ['adjoint_5fof_2ehpp_10',['adjoint_of.hpp',['../adjoint__of_8hpp.html',1,'']]],
  ['adjoint_5fresults_2ehpp_11',['adjoint_results.hpp',['../adjoint__results_8hpp.html',1,'']]],
  ['algebra_5fsolver_5fadapter_2ehpp_12',['algebra_solver_adapter.hpp',['../algebra__solver__adapter_8hpp.html',1,'']]],
  ['algebra_5fsolver_5ffp_2ehpp_13',['algebra_solver_fp.hpp',['../algebra__solver__fp_8hpp.html',1,'']]],
  ['algebra_5fsystem_2ehpp_14',['algebra_system.hpp',['../algebra__system_8hpp.html',1,'']]],
  ['all_2ehpp_15',['all.hpp',['../all_8hpp.html',1,'']]],
  ['any_2ehpp_16',['any.hpp',['../any_8hpp.html',1,'']]],
  ['append_2ehpp_17',['append.hpp',['../append_8hpp.html',1,'']]],
  ['append_5farray_2ehpp_18',['append_array.hpp',['../opencl_2prim_2append__array_8hpp.html',1,'(Global Namespace)'],['../prim_2fun_2append__array_8hpp.html',1,'(Global Namespace)']]],
  ['append_5fcol_2ehpp_19',['append_col.hpp',['../rev_2fun_2append__col_8hpp.html',1,'(Global Namespace)'],['../prim_2fun_2append__col_8hpp.html',1,'(Global Namespace)'],['../opencl_2rev_2append__col_8hpp.html',1,'(Global Namespace)']]],
  ['append_5freturn_5ftype_2ehpp_20',['append_return_type.hpp',['../append__return__type_8hpp.html',1,'']]],
  ['append_5frow_2ehpp_21',['append_row.hpp',['../opencl_2rev_2append__row_8hpp.html',1,'(Global Namespace)'],['../prim_2fun_2append__row_8hpp.html',1,'(Global Namespace)'],['../rev_2fun_2append__row_8hpp.html',1,'(Global Namespace)']]],
  ['apply_2ehpp_22',['apply.hpp',['../apply_8hpp.html',1,'']]],
  ['apply_5fscalar_5fbinary_2ehpp_23',['apply_scalar_binary.hpp',['../prim_2functor_2apply__scalar__binary_8hpp.html',1,'(Global Namespace)'],['../rev_2functor_2apply__scalar__binary_8hpp.html',1,'(Global Namespace)']]],
  ['apply_5fscalar_5fternary_2ehpp_24',['apply_scalar_ternary.hpp',['../apply__scalar__ternary_8hpp.html',1,'']]],
  ['apply_5fscalar_5funary_2ehpp_25',['apply_scalar_unary.hpp',['../fwd_2functor_2apply__scalar__unary_8hpp.html',1,'(Global Namespace)'],['../prim_2functor_2apply__scalar__unary_8hpp.html',1,'(Global Namespace)'],['../rev_2functor_2apply__scalar__unary_8hpp.html',1,'(Global Namespace)']]],
  ['apply_5fvector_5funary_2ehpp_26',['apply_vector_unary.hpp',['../prim_2functor_2apply__vector__unary_8hpp.html',1,'(Global Namespace)'],['../rev_2functor_2apply__vector__unary_8hpp.html',1,'(Global Namespace)']]],
  ['arena_5fallocator_2ehpp_27',['arena_allocator.hpp',['../arena__allocator_8hpp.html',1,'']]],
  ['arena_5fmatrix_2ehpp_28',['arena_matrix.hpp',['../arena__matrix_8hpp.html',1,'']]],
  ['arena_5fmatrix_5fcl_2ehpp_29',['arena_matrix_cl.hpp',['../arena__matrix__cl_8hpp.html',1,'']]],
  ['arena_5ftype_2ehpp_30',['arena_type.hpp',['../opencl_2rev_2arena__type_8hpp.html',1,'(Global Namespace)'],['../rev_2meta_2arena__type_8hpp.html',1,'(Global Namespace)']]],
  ['arg_2ehpp_31',['arg.hpp',['../fwd_2fun_2arg_8hpp.html',1,'(Global Namespace)'],['../prim_2fun_2arg_8hpp.html',1,'(Global Namespace)'],['../rev_2fun_2arg_8hpp.html',1,'(Global Namespace)']]],
  ['array_5fbuilder_2ehpp_32',['array_builder.hpp',['../array__builder_8hpp.html',1,'']]],
  ['as_5farray_5for_5fscalar_2ehpp_33',['as_array_or_scalar.hpp',['../rev_2fun_2as__array__or__scalar_8hpp.html',1,'(Global Namespace)'],['../prim_2fun_2as__array__or__scalar_8hpp.html',1,'(Global Namespace)']]],
  ['as_5fbool_2ehpp_34',['as_bool.hpp',['../rev_2fun_2as__bool_8hpp.html',1,'(Global Namespace)'],['../prim_2fun_2as__bool_8hpp.html',1,'(Global Namespace)']]],
  ['as_5fcolumn_5fvector_5for_5fscalar_2ehpp_35',['as_column_vector_or_scalar.hpp',['../opencl_2rev_2as__column__vector__or__scalar_8hpp.html',1,'(Global Namespace)'],['../rev_2fun_2as__column__vector__or__scalar_8hpp.html',1,'(Global Namespace)'],['../prim_2fun_2as__column__vector__or__scalar_8hpp.html',1,'(Global Namespace)'],['../opencl_2kernel__generator_2as__column__vector__or__scalar_8hpp.html',1,'(Global Namespace)']]],
  ['as_5foperation_5fcl_2ehpp_36',['as_operation_cl.hpp',['../as__operation__cl_8hpp.html',1,'']]],
  ['as_5fvalue_5farray_5for_5fscalar_2ehpp_37',['as_value_array_or_scalar.hpp',['../as__value__array__or__scalar_8hpp.html',1,'']]],
  ['as_5fvalue_5fcolumn_5farray_5for_5fscalar_2ehpp_38',['as_value_column_array_or_scalar.hpp',['../as__value__column__array__or__scalar_8hpp.html',1,'']]],
  ['as_5fvalue_5fcolumn_5fvector_5for_5fscalar_2ehpp_39',['as_value_column_vector_or_scalar.hpp',['../as__value__column__vector__or__scalar_8hpp.html',1,'']]],
  ['asin_2ehpp_40',['asin.hpp',['../prim_2fun_2asin_8hpp.html',1,'(Global Namespace)'],['../opencl_2rev_2asin_8hpp.html',1,'(Global Namespace)'],['../fwd_2fun_2asin_8hpp.html',1,'(Global Namespace)'],['../rev_2fun_2asin_8hpp.html',1,'(Global Namespace)']]],
  ['asinh_2ehpp_41',['asinh.hpp',['../fwd_2fun_2asinh_8hpp.html',1,'(Global Namespace)'],['../rev_2fun_2asinh_8hpp.html',1,'(Global Namespace)'],['../prim_2fun_2asinh_8hpp.html',1,'(Global Namespace)'],['../opencl_2rev_2asinh_8hpp.html',1,'(Global Namespace)']]],
  ['assign_2ehpp_42',['assign.hpp',['../assign_8hpp.html',1,'']]],
  ['assignment_5fops_2ehpp_43',['assignment_ops.hpp',['../assignment__ops_8hpp.html',1,'']]],
  ['atan_2ehpp_44',['atan.hpp',['../fwd_2fun_2atan_8hpp.html',1,'(Global Namespace)'],['../opencl_2rev_2atan_8hpp.html',1,'(Global Namespace)'],['../prim_2fun_2atan_8hpp.html',1,'(Global Namespace)'],['../rev_2fun_2atan_8hpp.html',1,'(Global Namespace)']]],
  ['atan2_2ehpp_45',['atan2.hpp',['../fwd_2fun_2atan2_8hpp.html',1,'(Global Namespace)'],['../prim_2fun_2atan2_8hpp.html',1,'(Global Namespace)'],['../rev_2fun_2atan2_8hpp.html',1,'(Global Namespace)']]],
  ['atanh_2ehpp_46',['atanh.hpp',['../fwd_2fun_2atanh_8hpp.html',1,'(Global Namespace)'],['../opencl_2rev_2atanh_8hpp.html',1,'(Global Namespace)'],['../prim_2fun_2atanh_8hpp.html',1,'(Global Namespace)'],['../rev_2fun_2atanh_8hpp.html',1,'(Global Namespace)']]],
  ['atomic_5fadd_5fdouble_2ehpp_47',['atomic_add_double.hpp',['../atomic__add__double_8hpp.html',1,'']]],
  ['autocorrelation_2ehpp_48',['autocorrelation.hpp',['../autocorrelation_8hpp.html',1,'']]],
  ['autocovariance_2ehpp_49',['autocovariance.hpp',['../autocovariance_8hpp.html',1,'']]],
  ['autodiff_5ftest_5fguide_2emd_50',['autodiff_test_guide.md',['../autodiff__test__guide_8md.html',1,'']]],
  ['autodiffstackstorage_2ehpp_51',['autodiffstackstorage.hpp',['../autodiffstackstorage_8hpp.html',1,'']]]
];
