var searchData=
[
  ['pack_2ehpp_0',['pack.hpp',['../pack_8hpp.html',1,'']]],
  ['pareto_5fccdf_5flog_2ehpp_1',['pareto_ccdf_log.hpp',['../pareto__ccdf__log_8hpp.html',1,'']]],
  ['pareto_5fcdf_2ehpp_2',['pareto_cdf.hpp',['../prim_2prob_2pareto__cdf_8hpp.html',1,'(Global Namespace)'],['../opencl_2prim_2pareto__cdf_8hpp.html',1,'(Global Namespace)']]],
  ['pareto_5fcdf_5flog_2ehpp_3',['pareto_cdf_log.hpp',['../pareto__cdf__log_8hpp.html',1,'']]],
  ['pareto_5flccdf_2ehpp_4',['pareto_lccdf.hpp',['../opencl_2prim_2pareto__lccdf_8hpp.html',1,'(Global Namespace)'],['../prim_2prob_2pareto__lccdf_8hpp.html',1,'(Global Namespace)']]],
  ['pareto_5flcdf_2ehpp_5',['pareto_lcdf.hpp',['../prim_2prob_2pareto__lcdf_8hpp.html',1,'(Global Namespace)'],['../opencl_2prim_2pareto__lcdf_8hpp.html',1,'(Global Namespace)']]],
  ['pareto_5flog_2ehpp_6',['pareto_log.hpp',['../pareto__log_8hpp.html',1,'']]],
  ['pareto_5flpdf_2ehpp_7',['pareto_lpdf.hpp',['../prim_2prob_2pareto__lpdf_8hpp.html',1,'(Global Namespace)'],['../opencl_2prim_2pareto__lpdf_8hpp.html',1,'(Global Namespace)']]],
  ['pareto_5frng_2ehpp_8',['pareto_rng.hpp',['../pareto__rng_8hpp.html',1,'']]],
  ['pareto_5ftype_5f2_5fccdf_5flog_2ehpp_9',['pareto_type_2_ccdf_log.hpp',['../pareto__type__2__ccdf__log_8hpp.html',1,'']]],
  ['pareto_5ftype_5f2_5fcdf_2ehpp_10',['pareto_type_2_cdf.hpp',['../prim_2prob_2pareto__type__2__cdf_8hpp.html',1,'(Global Namespace)'],['../opencl_2prim_2pareto__type__2__cdf_8hpp.html',1,'(Global Namespace)']]],
  ['pareto_5ftype_5f2_5fcdf_5flog_2ehpp_11',['pareto_type_2_cdf_log.hpp',['../pareto__type__2__cdf__log_8hpp.html',1,'']]],
  ['pareto_5ftype_5f2_5flccdf_2ehpp_12',['pareto_type_2_lccdf.hpp',['../prim_2prob_2pareto__type__2__lccdf_8hpp.html',1,'(Global Namespace)'],['../opencl_2prim_2pareto__type__2__lccdf_8hpp.html',1,'(Global Namespace)']]],
  ['pareto_5ftype_5f2_5flcdf_2ehpp_13',['pareto_type_2_lcdf.hpp',['../prim_2prob_2pareto__type__2__lcdf_8hpp.html',1,'(Global Namespace)'],['../opencl_2prim_2pareto__type__2__lcdf_8hpp.html',1,'(Global Namespace)']]],
  ['pareto_5ftype_5f2_5flog_2ehpp_14',['pareto_type_2_log.hpp',['../pareto__type__2__log_8hpp.html',1,'']]],
  ['pareto_5ftype_5f2_5flpdf_2ehpp_15',['pareto_type_2_lpdf.hpp',['../opencl_2prim_2pareto__type__2__lpdf_8hpp.html',1,'(Global Namespace)'],['../prim_2prob_2pareto__type__2__lpdf_8hpp.html',1,'(Global Namespace)']]],
  ['pareto_5ftype_5f2_5frng_2ehpp_16',['pareto_type_2_rng.hpp',['../pareto__type__2__rng_8hpp.html',1,'']]],
  ['partial_5fderivative_2ehpp_17',['partial_derivative.hpp',['../partial__derivative_8hpp.html',1,'']]],
  ['partials_5fpropagator_2ehpp_18',['partials_propagator.hpp',['../fwd_2functor_2partials__propagator_8hpp.html',1,'(Global Namespace)'],['../prim_2functor_2partials__propagator_8hpp.html',1,'(Global Namespace)'],['../rev_2functor_2partials__propagator_8hpp.html',1,'(Global Namespace)']]],
  ['partials_5freturn_5ftype_2ehpp_19',['partials_return_type.hpp',['../partials__return__type_8hpp.html',1,'']]],
  ['partials_5ftype_2ehpp_20',['partials_type.hpp',['../fwd_2meta_2partials__type_8hpp.html',1,'(Global Namespace)'],['../prim_2meta_2partials__type_8hpp.html',1,'(Global Namespace)'],['../rev_2meta_2partials__type_8hpp.html',1,'(Global Namespace)']]],
  ['phi_2ehpp_21',['Phi.hpp',['../fwd_2fun_2_phi_8hpp.html',1,'(Global Namespace)'],['../opencl_2kernels_2device__functions_2_phi_8hpp.html',1,'(Global Namespace)'],['../opencl_2rev_2_phi_8hpp.html',1,'(Global Namespace)'],['../prim_2fun_2_phi_8hpp.html',1,'(Global Namespace)'],['../rev_2fun_2_phi_8hpp.html',1,'(Global Namespace)']]],
  ['phi_5fapprox_2ehpp_22',['Phi_approx.hpp',['../fwd_2fun_2_phi__approx_8hpp.html',1,'(Global Namespace)'],['../opencl_2kernels_2device__functions_2_phi__approx_8hpp.html',1,'(Global Namespace)'],['../opencl_2rev_2_phi__approx_8hpp.html',1,'(Global Namespace)'],['../prim_2fun_2_phi__approx_8hpp.html',1,'(Global Namespace)'],['../rev_2fun_2_phi__approx_8hpp.html',1,'(Global Namespace)']]],
  ['pinned_5fmatrix_2ehpp_23',['pinned_matrix.hpp',['../pinned__matrix_8hpp.html',1,'']]],
  ['plain_5ftype_2ehpp_24',['plain_type.hpp',['../prim_2meta_2plain__type_8hpp.html',1,'(Global Namespace)'],['../rev_2meta_2plain__type_8hpp.html',1,'(Global Namespace)'],['../opencl_2plain__type_8hpp.html',1,'(Global Namespace)']]],
  ['plus_2ehpp_25',['plus.hpp',['../plus_8hpp.html',1,'']]],
  ['poisson_5fbinomial_5fccdf_5flog_2ehpp_26',['poisson_binomial_ccdf_log.hpp',['../poisson__binomial__ccdf__log_8hpp.html',1,'']]],
  ['poisson_5fbinomial_5fcdf_2ehpp_27',['poisson_binomial_cdf.hpp',['../poisson__binomial__cdf_8hpp.html',1,'']]],
  ['poisson_5fbinomial_5fcdf_5flog_2ehpp_28',['poisson_binomial_cdf_log.hpp',['../poisson__binomial__cdf__log_8hpp.html',1,'']]],
  ['poisson_5fbinomial_5flccdf_2ehpp_29',['poisson_binomial_lccdf.hpp',['../poisson__binomial__lccdf_8hpp.html',1,'']]],
  ['poisson_5fbinomial_5flcdf_2ehpp_30',['poisson_binomial_lcdf.hpp',['../poisson__binomial__lcdf_8hpp.html',1,'']]],
  ['poisson_5fbinomial_5flog_2ehpp_31',['poisson_binomial_log.hpp',['../poisson__binomial__log_8hpp.html',1,'']]],
  ['poisson_5fbinomial_5flog_5fprobs_2ehpp_32',['poisson_binomial_log_probs.hpp',['../poisson__binomial__log__probs_8hpp.html',1,'']]],
  ['poisson_5fbinomial_5flpmf_2ehpp_33',['poisson_binomial_lpmf.hpp',['../poisson__binomial__lpmf_8hpp.html',1,'']]],
  ['poisson_5fbinomial_5frng_2ehpp_34',['poisson_binomial_rng.hpp',['../poisson__binomial__rng_8hpp.html',1,'']]],
  ['poisson_5fccdf_5flog_2ehpp_35',['poisson_ccdf_log.hpp',['../poisson__ccdf__log_8hpp.html',1,'']]],
  ['poisson_5fcdf_2ehpp_36',['poisson_cdf.hpp',['../poisson__cdf_8hpp.html',1,'']]],
  ['poisson_5fcdf_5flog_2ehpp_37',['poisson_cdf_log.hpp',['../poisson__cdf__log_8hpp.html',1,'']]],
  ['poisson_5flccdf_2ehpp_38',['poisson_lccdf.hpp',['../poisson__lccdf_8hpp.html',1,'']]],
  ['poisson_5flcdf_2ehpp_39',['poisson_lcdf.hpp',['../poisson__lcdf_8hpp.html',1,'']]],
  ['poisson_5flog_2ehpp_40',['poisson_log.hpp',['../poisson__log_8hpp.html',1,'']]],
  ['poisson_5flog_5fglm_5flog_2ehpp_41',['poisson_log_glm_log.hpp',['../poisson__log__glm__log_8hpp.html',1,'']]],
  ['poisson_5flog_5fglm_5flpmf_2ehpp_42',['poisson_log_glm_lpmf.hpp',['../prim_2prob_2poisson__log__glm__lpmf_8hpp.html',1,'(Global Namespace)'],['../opencl_2prim_2poisson__log__glm__lpmf_8hpp.html',1,'(Global Namespace)']]],
  ['poisson_5flog_5flog_2ehpp_43',['poisson_log_log.hpp',['../poisson__log__log_8hpp.html',1,'']]],
  ['poisson_5flog_5flpmf_2ehpp_44',['poisson_log_lpmf.hpp',['../opencl_2prim_2poisson__log__lpmf_8hpp.html',1,'(Global Namespace)'],['../prim_2prob_2poisson__log__lpmf_8hpp.html',1,'(Global Namespace)']]],
  ['poisson_5flog_5frng_2ehpp_45',['poisson_log_rng.hpp',['../poisson__log__rng_8hpp.html',1,'']]],
  ['poisson_5flpmf_2ehpp_46',['poisson_lpmf.hpp',['../opencl_2prim_2poisson__lpmf_8hpp.html',1,'(Global Namespace)'],['../prim_2prob_2poisson__lpmf_8hpp.html',1,'(Global Namespace)']]],
  ['poisson_5frng_2ehpp_47',['poisson_rng.hpp',['../poisson__rng_8hpp.html',1,'']]],
  ['polar_2ehpp_48',['polar.hpp',['../rev_2fun_2polar_8hpp.html',1,'(Global Namespace)'],['../prim_2fun_2polar_8hpp.html',1,'(Global Namespace)'],['../fwd_2fun_2polar_8hpp.html',1,'(Global Namespace)']]],
  ['positive_5fconstrain_2ehpp_49',['positive_constrain.hpp',['../positive__constrain_8hpp.html',1,'']]],
  ['positive_5ffree_2ehpp_50',['positive_free.hpp',['../positive__free_8hpp.html',1,'']]],
  ['positive_5fordered_5fconstrain_2ehpp_51',['positive_ordered_constrain.hpp',['../rev_2fun_2positive__ordered__constrain_8hpp.html',1,'(Global Namespace)'],['../prim_2fun_2positive__ordered__constrain_8hpp.html',1,'(Global Namespace)']]],
  ['positive_5fordered_5ffree_2ehpp_52',['positive_ordered_free.hpp',['../positive__ordered__free_8hpp.html',1,'']]],
  ['possibly_5fsum_2ehpp_53',['possibly_sum.hpp',['../possibly__sum_8hpp.html',1,'']]],
  ['pow_2ehpp_54',['pow.hpp',['../fwd_2fun_2pow_8hpp.html',1,'(Global Namespace)'],['../opencl_2rev_2pow_8hpp.html',1,'(Global Namespace)'],['../prim_2fun_2pow_8hpp.html',1,'(Global Namespace)'],['../rev_2fun_2pow_8hpp.html',1,'(Global Namespace)']]],
  ['precomp_5fvv_5fvari_2ehpp_55',['precomp_vv_vari.hpp',['../precomp__vv__vari_8hpp.html',1,'']]],
  ['precomp_5fvvv_5fvari_2ehpp_56',['precomp_vvv_vari.hpp',['../precomp__vvv__vari_8hpp.html',1,'']]],
  ['precomputed_5fgradients_2ehpp_57',['precomputed_gradients.hpp',['../precomputed__gradients_8hpp.html',1,'']]],
  ['prim_2ehpp_58',['prim.hpp',['../opencl_2prim_8hpp.html',1,'(Global Namespace)'],['../prim_8hpp.html',1,'(Global Namespace)']]],
  ['primitive_5fvalue_2ehpp_59',['primitive_value.hpp',['../rev_2fun_2primitive__value_8hpp.html',1,'(Global Namespace)'],['../prim_2fun_2primitive__value_8hpp.html',1,'(Global Namespace)'],['../fwd_2fun_2primitive__value_8hpp.html',1,'(Global Namespace)']]],
  ['print_5fstack_2ehpp_60',['print_stack.hpp',['../print__stack_8hpp.html',1,'']]],
  ['prob_2ehpp_61',['prob.hpp',['../prim_2prob_8hpp.html',1,'(Global Namespace)'],['../fwd_2prob_8hpp.html',1,'(Global Namespace)'],['../rev_2prob_8hpp.html',1,'(Global Namespace)']]],
  ['prob_5fconstrain_2ehpp_62',['prob_constrain.hpp',['../prob__constrain_8hpp.html',1,'']]],
  ['prob_5ffree_2ehpp_63',['prob_free.hpp',['../prob__free_8hpp.html',1,'']]],
  ['prod_2ehpp_64',['prod.hpp',['../opencl_2rev_2prod_8hpp.html',1,'(Global Namespace)'],['../opencl_2prim_2prod_8hpp.html',1,'(Global Namespace)'],['../prim_2fun_2prod_8hpp.html',1,'(Global Namespace)']]],
  ['profiling_2ehpp_65',['profiling.hpp',['../profiling_8hpp.html',1,'']]],
  ['proj_2ehpp_66',['proj.hpp',['../fwd_2fun_2proj_8hpp.html',1,'(Global Namespace)'],['../prim_2fun_2proj_8hpp.html',1,'(Global Namespace)'],['../rev_2fun_2proj_8hpp.html',1,'(Global Namespace)']]],
  ['promote_5fargs_2ehpp_67',['promote_args.hpp',['../promote__args_8hpp.html',1,'']]],
  ['promote_5felements_2ehpp_68',['promote_elements.hpp',['../promote__elements_8hpp.html',1,'']]],
  ['promote_5fscalar_2ehpp_69',['promote_scalar.hpp',['../promote__scalar_8hpp.html',1,'']]],
  ['promote_5fscalar_5ftype_2ehpp_70',['promote_scalar_type.hpp',['../promote__scalar__type_8hpp.html',1,'']]],
  ['promote_5fvar_5fmatrix_2ehpp_71',['promote_var_matrix.hpp',['../promote__var__matrix_8hpp.html',1,'']]],
  ['pseudo_5feigenvalues_2ehpp_72',['pseudo_eigenvalues.hpp',['../pseudo__eigenvalues_8hpp.html',1,'']]],
  ['pseudo_5feigenvectors_2ehpp_73',['pseudo_eigenvectors.hpp',['../pseudo__eigenvectors_8hpp.html',1,'']]]
];
