var searchData=
[
  ['base_5ftype_2ehpp_0',['base_type.hpp',['../base__type_8hpp.html',1,'']]],
  ['batch_5fidentity_2ehpp_1',['batch_identity.hpp',['../batch__identity_8hpp.html',1,'']]],
  ['bernoulli_5fccdf_5flog_2ehpp_2',['bernoulli_ccdf_log.hpp',['../bernoulli__ccdf__log_8hpp.html',1,'']]],
  ['bernoulli_5fcdf_2ehpp_3',['bernoulli_cdf.hpp',['../prim_2prob_2bernoulli__cdf_8hpp.html',1,'(Global Namespace)'],['../opencl_2prim_2bernoulli__cdf_8hpp.html',1,'(Global Namespace)']]],
  ['bernoulli_5fcdf_5flog_2ehpp_4',['bernoulli_cdf_log.hpp',['../bernoulli__cdf__log_8hpp.html',1,'']]],
  ['bernoulli_5flccdf_2ehpp_5',['bernoulli_lccdf.hpp',['../prim_2prob_2bernoulli__lccdf_8hpp.html',1,'(Global Namespace)'],['../opencl_2prim_2bernoulli__lccdf_8hpp.html',1,'(Global Namespace)']]],
  ['bernoulli_5flcdf_2ehpp_6',['bernoulli_lcdf.hpp',['../prim_2prob_2bernoulli__lcdf_8hpp.html',1,'(Global Namespace)'],['../opencl_2prim_2bernoulli__lcdf_8hpp.html',1,'(Global Namespace)']]],
  ['bernoulli_5flog_2ehpp_7',['bernoulli_log.hpp',['../bernoulli__log_8hpp.html',1,'']]],
  ['bernoulli_5flogit_5fglm_5flog_2ehpp_8',['bernoulli_logit_glm_log.hpp',['../bernoulli__logit__glm__log_8hpp.html',1,'']]],
  ['bernoulli_5flogit_5fglm_5flpmf_2ehpp_9',['bernoulli_logit_glm_lpmf.hpp',['../opencl_2prim_2bernoulli__logit__glm__lpmf_8hpp.html',1,'(Global Namespace)'],['../prim_2prob_2bernoulli__logit__glm__lpmf_8hpp.html',1,'(Global Namespace)']]],
  ['bernoulli_5flogit_5fglm_5frng_2ehpp_10',['bernoulli_logit_glm_rng.hpp',['../bernoulli__logit__glm__rng_8hpp.html',1,'']]],
  ['bernoulli_5flogit_5flog_2ehpp_11',['bernoulli_logit_log.hpp',['../bernoulli__logit__log_8hpp.html',1,'']]],
  ['bernoulli_5flogit_5flpmf_2ehpp_12',['bernoulli_logit_lpmf.hpp',['../prim_2prob_2bernoulli__logit__lpmf_8hpp.html',1,'(Global Namespace)'],['../opencl_2prim_2bernoulli__logit__lpmf_8hpp.html',1,'(Global Namespace)']]],
  ['bernoulli_5flogit_5frng_2ehpp_13',['bernoulli_logit_rng.hpp',['../bernoulli__logit__rng_8hpp.html',1,'']]],
  ['bernoulli_5flpmf_2ehpp_14',['bernoulli_lpmf.hpp',['../prim_2prob_2bernoulli__lpmf_8hpp.html',1,'(Global Namespace)'],['../opencl_2prim_2bernoulli__lpmf_8hpp.html',1,'(Global Namespace)']]],
  ['bernoulli_5frng_2ehpp_15',['bernoulli_rng.hpp',['../bernoulli__rng_8hpp.html',1,'']]],
  ['bessel_5ffirst_5fkind_2ehpp_16',['bessel_first_kind.hpp',['../prim_2fun_2bessel__first__kind_8hpp.html',1,'(Global Namespace)'],['../fwd_2fun_2bessel__first__kind_8hpp.html',1,'(Global Namespace)'],['../rev_2fun_2bessel__first__kind_8hpp.html',1,'(Global Namespace)']]],
  ['bessel_5fsecond_5fkind_2ehpp_17',['bessel_second_kind.hpp',['../rev_2fun_2bessel__second__kind_8hpp.html',1,'(Global Namespace)'],['../prim_2fun_2bessel__second__kind_8hpp.html',1,'(Global Namespace)'],['../fwd_2fun_2bessel__second__kind_8hpp.html',1,'(Global Namespace)']]],
  ['beta_2ehpp_18',['beta.hpp',['../prim_2fun_2beta_8hpp.html',1,'(Global Namespace)'],['../opencl_2rev_2beta_8hpp.html',1,'(Global Namespace)'],['../opencl_2kernels_2device__functions_2beta_8hpp.html',1,'(Global Namespace)'],['../rev_2fun_2beta_8hpp.html',1,'(Global Namespace)'],['../fwd_2fun_2beta_8hpp.html',1,'(Global Namespace)']]],
  ['beta_5fbinomial_5fccdf_5flog_2ehpp_19',['beta_binomial_ccdf_log.hpp',['../beta__binomial__ccdf__log_8hpp.html',1,'']]],
  ['beta_5fbinomial_5fcdf_2ehpp_20',['beta_binomial_cdf.hpp',['../beta__binomial__cdf_8hpp.html',1,'']]],
  ['beta_5fbinomial_5fcdf_5flog_2ehpp_21',['beta_binomial_cdf_log.hpp',['../beta__binomial__cdf__log_8hpp.html',1,'']]],
  ['beta_5fbinomial_5flccdf_2ehpp_22',['beta_binomial_lccdf.hpp',['../beta__binomial__lccdf_8hpp.html',1,'']]],
  ['beta_5fbinomial_5flcdf_2ehpp_23',['beta_binomial_lcdf.hpp',['../beta__binomial__lcdf_8hpp.html',1,'']]],
  ['beta_5fbinomial_5flog_2ehpp_24',['beta_binomial_log.hpp',['../beta__binomial__log_8hpp.html',1,'']]],
  ['beta_5fbinomial_5flpmf_2ehpp_25',['beta_binomial_lpmf.hpp',['../prim_2prob_2beta__binomial__lpmf_8hpp.html',1,'(Global Namespace)'],['../opencl_2prim_2beta__binomial__lpmf_8hpp.html',1,'(Global Namespace)']]],
  ['beta_5fbinomial_5frng_2ehpp_26',['beta_binomial_rng.hpp',['../beta__binomial__rng_8hpp.html',1,'']]],
  ['beta_5fccdf_5flog_2ehpp_27',['beta_ccdf_log.hpp',['../beta__ccdf__log_8hpp.html',1,'']]],
  ['beta_5fcdf_2ehpp_28',['beta_cdf.hpp',['../beta__cdf_8hpp.html',1,'']]],
  ['beta_5fcdf_5flog_2ehpp_29',['beta_cdf_log.hpp',['../beta__cdf__log_8hpp.html',1,'']]],
  ['beta_5flccdf_2ehpp_30',['beta_lccdf.hpp',['../beta__lccdf_8hpp.html',1,'']]],
  ['beta_5flcdf_2ehpp_31',['beta_lcdf.hpp',['../beta__lcdf_8hpp.html',1,'']]],
  ['beta_5flog_2ehpp_32',['beta_log.hpp',['../beta__log_8hpp.html',1,'']]],
  ['beta_5flpdf_2ehpp_33',['beta_lpdf.hpp',['../prim_2prob_2beta__lpdf_8hpp.html',1,'(Global Namespace)'],['../opencl_2prim_2beta__lpdf_8hpp.html',1,'(Global Namespace)']]],
  ['beta_5fproportion_5fccdf_5flog_2ehpp_34',['beta_proportion_ccdf_log.hpp',['../beta__proportion__ccdf__log_8hpp.html',1,'']]],
  ['beta_5fproportion_5fcdf_5flog_2ehpp_35',['beta_proportion_cdf_log.hpp',['../beta__proportion__cdf__log_8hpp.html',1,'']]],
  ['beta_5fproportion_5flccdf_2ehpp_36',['beta_proportion_lccdf.hpp',['../beta__proportion__lccdf_8hpp.html',1,'']]],
  ['beta_5fproportion_5flcdf_2ehpp_37',['beta_proportion_lcdf.hpp',['../beta__proportion__lcdf_8hpp.html',1,'']]],
  ['beta_5fproportion_5flog_2ehpp_38',['beta_proportion_log.hpp',['../beta__proportion__log_8hpp.html',1,'']]],
  ['beta_5fproportion_5flpdf_2ehpp_39',['beta_proportion_lpdf.hpp',['../opencl_2prim_2beta__proportion__lpdf_8hpp.html',1,'(Global Namespace)'],['../prim_2prob_2beta__proportion__lpdf_8hpp.html',1,'(Global Namespace)']]],
  ['beta_5fproportion_5frng_2ehpp_40',['beta_proportion_rng.hpp',['../beta__proportion__rng_8hpp.html',1,'']]],
  ['beta_5frng_2ehpp_41',['beta_rng.hpp',['../beta__rng_8hpp.html',1,'']]],
  ['binary_5flog_5floss_2ehpp_42',['binary_log_loss.hpp',['../fwd_2fun_2binary__log__loss_8hpp.html',1,'(Global Namespace)'],['../prim_2fun_2binary__log__loss_8hpp.html',1,'(Global Namespace)'],['../rev_2fun_2binary__log__loss_8hpp.html',1,'(Global Namespace)']]],
  ['binary_5foperation_2ehpp_43',['binary_operation.hpp',['../binary__operation_8hpp.html',1,'']]],
  ['binomial_5fccdf_5flog_2ehpp_44',['binomial_ccdf_log.hpp',['../binomial__ccdf__log_8hpp.html',1,'']]],
  ['binomial_5fcdf_2ehpp_45',['binomial_cdf.hpp',['../binomial__cdf_8hpp.html',1,'']]],
  ['binomial_5fcdf_5flog_2ehpp_46',['binomial_cdf_log.hpp',['../binomial__cdf__log_8hpp.html',1,'']]],
  ['binomial_5fcoefficient_5flog_2ehpp_47',['binomial_coefficient_log.hpp',['../prim_2fun_2binomial__coefficient__log_8hpp.html',1,'(Global Namespace)'],['../opencl_2kernels_2device__functions_2binomial__coefficient__log_8hpp.html',1,'(Global Namespace)']]],
  ['binomial_5flccdf_2ehpp_48',['binomial_lccdf.hpp',['../binomial__lccdf_8hpp.html',1,'']]],
  ['binomial_5flcdf_2ehpp_49',['binomial_lcdf.hpp',['../binomial__lcdf_8hpp.html',1,'']]],
  ['binomial_5flog_2ehpp_50',['binomial_log.hpp',['../binomial__log_8hpp.html',1,'']]],
  ['binomial_5flogit_5fglm_5flpmf_2ehpp_51',['binomial_logit_glm_lpmf.hpp',['../opencl_2prim_2binomial__logit__glm__lpmf_8hpp.html',1,'(Global Namespace)'],['../prim_2prob_2binomial__logit__glm__lpmf_8hpp.html',1,'(Global Namespace)']]],
  ['binomial_5flogit_5flog_2ehpp_52',['binomial_logit_log.hpp',['../binomial__logit__log_8hpp.html',1,'']]],
  ['binomial_5flogit_5flpmf_2ehpp_53',['binomial_logit_lpmf.hpp',['../opencl_2prim_2binomial__logit__lpmf_8hpp.html',1,'(Global Namespace)'],['../prim_2prob_2binomial__logit__lpmf_8hpp.html',1,'(Global Namespace)']]],
  ['binomial_5flpmf_2ehpp_54',['binomial_lpmf.hpp',['../prim_2prob_2binomial__lpmf_8hpp.html',1,'(Global Namespace)'],['../opencl_2prim_2binomial__lpmf_8hpp.html',1,'(Global Namespace)']]],
  ['binomial_5frng_2ehpp_55',['binomial_rng.hpp',['../binomial__rng_8hpp.html',1,'']]],
  ['block_2ehpp_56',['block.hpp',['../prim_2fun_2block_8hpp.html',1,'(Global Namespace)'],['../opencl_2rev_2block_8hpp.html',1,'(Global Namespace)'],['../opencl_2prim_2block_8hpp.html',1,'(Global Namespace)']]],
  ['block_5fzero_5fbased_2ehpp_57',['block_zero_based.hpp',['../block__zero__based_8hpp.html',1,'']]],
  ['bool_5fconstant_2ehpp_58',['bool_constant.hpp',['../bool__constant_8hpp.html',1,'']]],
  ['boost_5fpolicy_2ehpp_59',['boost_policy.hpp',['../boost__policy_8hpp.html',1,'']]],
  ['broadcast_2ehpp_60',['broadcast.hpp',['../broadcast_8hpp.html',1,'']]],
  ['broadcast_5farray_2ehpp_61',['broadcast_array.hpp',['../broadcast__array_8hpp.html',1,'']]],
  ['buffer_5ftypes_2ehpp_62',['buffer_types.hpp',['../buffer__types_8hpp.html',1,'']]],
  ['build_5fvari_5farray_2ehpp_63',['build_vari_array.hpp',['../build__vari__array_8hpp.html',1,'']]]
];
