var searchData=
[
  ['calc_5fif_2ehpp_0',['calc_if.hpp',['../calc__if_8hpp.html',1,'']]],
  ['callback_5fvari_2ehpp_1',['callback_vari.hpp',['../callback__vari_8hpp.html',1,'']]],
  ['cast_2ehpp_2',['cast.hpp',['../cast_8hpp.html',1,'']]],
  ['categorical_5flog_2ehpp_3',['categorical_log.hpp',['../categorical__log_8hpp.html',1,'']]],
  ['categorical_5flogit_5fglm_5flpmf_2ehpp_4',['categorical_logit_glm_lpmf.hpp',['../prim_2prob_2categorical__logit__glm__lpmf_8hpp.html',1,'(Global Namespace)'],['../opencl_2prim_2categorical__logit__glm__lpmf_8hpp.html',1,'(Global Namespace)'],['../opencl_2kernels_2categorical__logit__glm__lpmf_8hpp.html',1,'(Global Namespace)']]],
  ['categorical_5flogit_5flog_2ehpp_5',['categorical_logit_log.hpp',['../categorical__logit__log_8hpp.html',1,'']]],
  ['categorical_5flogit_5flpmf_2ehpp_6',['categorical_logit_lpmf.hpp',['../categorical__logit__lpmf_8hpp.html',1,'']]],
  ['categorical_5flogit_5frng_2ehpp_7',['categorical_logit_rng.hpp',['../categorical__logit__rng_8hpp.html',1,'']]],
  ['categorical_5flpmf_2ehpp_8',['categorical_lpmf.hpp',['../categorical__lpmf_8hpp.html',1,'']]],
  ['categorical_5frng_2ehpp_9',['categorical_rng.hpp',['../categorical__rng_8hpp.html',1,'']]],
  ['cauchy_5fccdf_5flog_2ehpp_10',['cauchy_ccdf_log.hpp',['../cauchy__ccdf__log_8hpp.html',1,'']]],
  ['cauchy_5fcdf_2ehpp_11',['cauchy_cdf.hpp',['../opencl_2prim_2cauchy__cdf_8hpp.html',1,'(Global Namespace)'],['../prim_2prob_2cauchy__cdf_8hpp.html',1,'(Global Namespace)']]],
  ['cauchy_5fcdf_5flog_2ehpp_12',['cauchy_cdf_log.hpp',['../cauchy__cdf__log_8hpp.html',1,'']]],
  ['cauchy_5flccdf_2ehpp_13',['cauchy_lccdf.hpp',['../opencl_2prim_2cauchy__lccdf_8hpp.html',1,'(Global Namespace)'],['../prim_2prob_2cauchy__lccdf_8hpp.html',1,'(Global Namespace)']]],
  ['cauchy_5flcdf_2ehpp_14',['cauchy_lcdf.hpp',['../opencl_2prim_2cauchy__lcdf_8hpp.html',1,'(Global Namespace)'],['../prim_2prob_2cauchy__lcdf_8hpp.html',1,'(Global Namespace)']]],
  ['cauchy_5flog_2ehpp_15',['cauchy_log.hpp',['../cauchy__log_8hpp.html',1,'']]],
  ['cauchy_5flpdf_2ehpp_16',['cauchy_lpdf.hpp',['../prim_2prob_2cauchy__lpdf_8hpp.html',1,'(Global Namespace)'],['../opencl_2prim_2cauchy__lpdf_8hpp.html',1,'(Global Namespace)']]],
  ['cauchy_5frng_2ehpp_17',['cauchy_rng.hpp',['../cauchy__rng_8hpp.html',1,'']]],
  ['cbrt_2ehpp_18',['cbrt.hpp',['../fwd_2fun_2cbrt_8hpp.html',1,'(Global Namespace)'],['../rev_2fun_2cbrt_8hpp.html',1,'(Global Namespace)'],['../prim_2fun_2cbrt_8hpp.html',1,'(Global Namespace)'],['../opencl_2rev_2cbrt_8hpp.html',1,'(Global Namespace)']]],
  ['ceil_2ehpp_19',['ceil.hpp',['../rev_2fun_2ceil_8hpp.html',1,'(Global Namespace)'],['../prim_2fun_2ceil_8hpp.html',1,'(Global Namespace)'],['../fwd_2fun_2ceil_8hpp.html',1,'(Global Namespace)'],['../opencl_2rev_2ceil_8hpp.html',1,'(Global Namespace)']]],
  ['chainable_5falloc_2ehpp_20',['chainable_alloc.hpp',['../chainable__alloc_8hpp.html',1,'']]],
  ['chainable_5fobject_2ehpp_21',['chainable_object.hpp',['../chainable__object_8hpp.html',1,'']]],
  ['chainablestack_2ehpp_22',['chainablestack.hpp',['../chainablestack_8hpp.html',1,'']]],
  ['check_5f2f1_5fconverges_2ehpp_23',['check_2F1_converges.hpp',['../check__2_f1__converges_8hpp.html',1,'']]],
  ['check_5f3f2_5fconverges_2ehpp_24',['check_3F2_converges.hpp',['../check__3_f2__converges_8hpp.html',1,'']]],
  ['check_5fbounded_2ehpp_25',['check_bounded.hpp',['../check__bounded_8hpp.html',1,'']]],
  ['check_5fcholesky_5ffactor_2ehpp_26',['check_cholesky_factor.hpp',['../check__cholesky__factor_8hpp.html',1,'']]],
  ['check_5fcholesky_5ffactor_5fcorr_2ehpp_27',['check_cholesky_factor_corr.hpp',['../check__cholesky__factor__corr_8hpp.html',1,'']]],
  ['check_5fcl_2ehpp_28',['check_cl.hpp',['../check__cl_8hpp.html',1,'']]],
  ['check_5fcolumn_5findex_2ehpp_29',['check_column_index.hpp',['../check__column__index_8hpp.html',1,'']]],
  ['check_5fconsistent_5fsize_2ehpp_30',['check_consistent_size.hpp',['../check__consistent__size_8hpp.html',1,'']]],
  ['check_5fconsistent_5fsizes_2ehpp_31',['check_consistent_sizes.hpp',['../check__consistent__sizes_8hpp.html',1,'']]],
  ['check_5fconsistent_5fsizes_5fmvt_2ehpp_32',['check_consistent_sizes_mvt.hpp',['../check__consistent__sizes__mvt_8hpp.html',1,'']]],
  ['check_5fcorr_5fmatrix_2ehpp_33',['check_corr_matrix.hpp',['../check__corr__matrix_8hpp.html',1,'']]],
  ['check_5fcov_5fmatrix_2ehpp_34',['check_cov_matrix.hpp',['../check__cov__matrix_8hpp.html',1,'']]],
  ['check_5ffinite_2ehpp_35',['check_finite.hpp',['../check__finite_8hpp.html',1,'']]],
  ['check_5fflag_5fsundials_2ehpp_36',['check_flag_sundials.hpp',['../check__flag__sundials_8hpp.html',1,'']]],
  ['check_5fgreater_2ehpp_37',['check_greater.hpp',['../check__greater_8hpp.html',1,'']]],
  ['check_5fgreater_5for_5fequal_2ehpp_38',['check_greater_or_equal.hpp',['../check__greater__or__equal_8hpp.html',1,'']]],
  ['check_5fldlt_5ffactor_2ehpp_39',['check_ldlt_factor.hpp',['../check__ldlt__factor_8hpp.html',1,'']]],
  ['check_5fless_2ehpp_40',['check_less.hpp',['../check__less_8hpp.html',1,'']]],
  ['check_5fless_5for_5fequal_2ehpp_41',['check_less_or_equal.hpp',['../check__less__or__equal_8hpp.html',1,'']]],
  ['check_5flower_5ftriangular_2ehpp_42',['check_lower_triangular.hpp',['../check__lower__triangular_8hpp.html',1,'']]],
  ['check_5fmat_5fsize_5fone_2ehpp_43',['check_mat_size_one.hpp',['../check__mat__size__one_8hpp.html',1,'']]],
  ['check_5fmatching_5fdims_2ehpp_44',['check_matching_dims.hpp',['../check__matching__dims_8hpp.html',1,'']]],
  ['check_5fmatching_5fsizes_2ehpp_45',['check_matching_sizes.hpp',['../check__matching__sizes_8hpp.html',1,'']]],
  ['check_5fmultiplicable_2ehpp_46',['check_multiplicable.hpp',['../check__multiplicable_8hpp.html',1,'']]],
  ['check_5fnonnegative_2ehpp_47',['check_nonnegative.hpp',['../check__nonnegative_8hpp.html',1,'']]],
  ['check_5fnonzero_5fsize_2ehpp_48',['check_nonzero_size.hpp',['../check__nonzero__size_8hpp.html',1,'']]],
  ['check_5fnot_5fnan_2ehpp_49',['check_not_nan.hpp',['../check__not__nan_8hpp.html',1,'']]],
  ['check_5fopencl_2ehpp_50',['check_opencl.hpp',['../check__opencl_8hpp.html',1,'']]],
  ['check_5fordered_2ehpp_51',['check_ordered.hpp',['../check__ordered_8hpp.html',1,'']]],
  ['check_5fpos_5fdefinite_2ehpp_52',['check_pos_definite.hpp',['../check__pos__definite_8hpp.html',1,'']]],
  ['check_5fpos_5fsemidefinite_2ehpp_53',['check_pos_semidefinite.hpp',['../check__pos__semidefinite_8hpp.html',1,'']]],
  ['check_5fpositive_2ehpp_54',['check_positive.hpp',['../check__positive_8hpp.html',1,'']]],
  ['check_5fpositive_5ffinite_2ehpp_55',['check_positive_finite.hpp',['../check__positive__finite_8hpp.html',1,'']]],
  ['check_5fpositive_5fordered_2ehpp_56',['check_positive_ordered.hpp',['../check__positive__ordered_8hpp.html',1,'']]],
  ['check_5frange_2ehpp_57',['check_range.hpp',['../check__range_8hpp.html',1,'']]],
  ['check_5frow_5findex_2ehpp_58',['check_row_index.hpp',['../check__row__index_8hpp.html',1,'']]],
  ['check_5fsimplex_2ehpp_59',['check_simplex.hpp',['../check__simplex_8hpp.html',1,'']]],
  ['check_5fsize_5fmatch_2ehpp_60',['check_size_match.hpp',['../check__size__match_8hpp.html',1,'']]],
  ['check_5fsorted_2ehpp_61',['check_sorted.hpp',['../check__sorted_8hpp.html',1,'']]],
  ['check_5fsquare_2ehpp_62',['check_square.hpp',['../check__square_8hpp.html',1,'']]],
  ['check_5fstd_5fvector_5findex_2ehpp_63',['check_std_vector_index.hpp',['../check__std__vector__index_8hpp.html',1,'']]],
  ['check_5fsymmetric_2ehpp_64',['check_symmetric.hpp',['../prim_2err_2check__symmetric_8hpp.html',1,'(Global Namespace)'],['../opencl_2kernels_2check__symmetric_8hpp.html',1,'(Global Namespace)'],['../opencl_2err_2check__symmetric_8hpp.html',1,'(Global Namespace)']]],
  ['check_5ftriangular_2ehpp_65',['check_triangular.hpp',['../check__triangular_8hpp.html',1,'']]],
  ['check_5funit_5fvector_2ehpp_66',['check_unit_vector.hpp',['../check__unit__vector_8hpp.html',1,'']]],
  ['check_5fvector_2ehpp_67',['check_vector.hpp',['../check__vector_8hpp.html',1,'']]],
  ['check_5fvector_5findex_2ehpp_68',['check_vector_index.hpp',['../check__vector__index_8hpp.html',1,'']]],
  ['chi_5fsquare_5fccdf_5flog_2ehpp_69',['chi_square_ccdf_log.hpp',['../chi__square__ccdf__log_8hpp.html',1,'']]],
  ['chi_5fsquare_5fcdf_2ehpp_70',['chi_square_cdf.hpp',['../chi__square__cdf_8hpp.html',1,'']]],
  ['chi_5fsquare_5fcdf_5flog_2ehpp_71',['chi_square_cdf_log.hpp',['../chi__square__cdf__log_8hpp.html',1,'']]],
  ['chi_5fsquare_5flccdf_2ehpp_72',['chi_square_lccdf.hpp',['../chi__square__lccdf_8hpp.html',1,'']]],
  ['chi_5fsquare_5flcdf_2ehpp_73',['chi_square_lcdf.hpp',['../chi__square__lcdf_8hpp.html',1,'']]],
  ['chi_5fsquare_5flog_2ehpp_74',['chi_square_log.hpp',['../chi__square__log_8hpp.html',1,'']]],
  ['chi_5fsquare_5flpdf_2ehpp_75',['chi_square_lpdf.hpp',['../prim_2prob_2chi__square__lpdf_8hpp.html',1,'(Global Namespace)'],['../opencl_2prim_2chi__square__lpdf_8hpp.html',1,'(Global Namespace)']]],
  ['chi_5fsquare_5frng_2ehpp_76',['chi_square_rng.hpp',['../chi__square__rng_8hpp.html',1,'']]],
  ['chol2inv_2ehpp_77',['chol2inv.hpp',['../chol2inv_8hpp.html',1,'']]],
  ['cholesky_5fcorr_5fconstrain_2ehpp_78',['cholesky_corr_constrain.hpp',['../rev_2fun_2cholesky__corr__constrain_8hpp.html',1,'(Global Namespace)'],['../prim_2fun_2cholesky__corr__constrain_8hpp.html',1,'(Global Namespace)']]],
  ['cholesky_5fcorr_5ffree_2ehpp_79',['cholesky_corr_free.hpp',['../cholesky__corr__free_8hpp.html',1,'']]],
  ['cholesky_5fdecompose_2ehpp_80',['cholesky_decompose.hpp',['../opencl_2cholesky__decompose_8hpp.html',1,'(Global Namespace)'],['../opencl_2kernels_2cholesky__decompose_8hpp.html',1,'(Global Namespace)'],['../opencl_2prim_2cholesky__decompose_8hpp.html',1,'(Global Namespace)'],['../opencl_2rev_2cholesky__decompose_8hpp.html',1,'(Global Namespace)'],['../prim_2fun_2cholesky__decompose_8hpp.html',1,'(Global Namespace)'],['../rev_2fun_2cholesky__decompose_8hpp.html',1,'(Global Namespace)']]],
  ['cholesky_5ffactor_5fconstrain_2ehpp_81',['cholesky_factor_constrain.hpp',['../rev_2fun_2cholesky__factor__constrain_8hpp.html',1,'(Global Namespace)'],['../prim_2fun_2cholesky__factor__constrain_8hpp.html',1,'(Global Namespace)']]],
  ['cholesky_5ffactor_5ffree_2ehpp_82',['cholesky_factor_free.hpp',['../cholesky__factor__free_8hpp.html',1,'']]],
  ['choose_2ehpp_83',['choose.hpp',['../choose_8hpp.html',1,'']]],
  ['col_2ehpp_84',['col.hpp',['../prim_2fun_2col_8hpp.html',1,'(Global Namespace)'],['../opencl_2prim_2col_8hpp.html',1,'(Global Namespace)']]],
  ['cols_2ehpp_85',['cols.hpp',['../opencl_2prim_2cols_8hpp.html',1,'(Global Namespace)'],['../prim_2fun_2cols_8hpp.html',1,'(Global Namespace)']]],
  ['columns_5fdot_5fproduct_2ehpp_86',['columns_dot_product.hpp',['../opencl_2prim_2columns__dot__product_8hpp.html',1,'(Global Namespace)'],['../opencl_2rev_2columns__dot__product_8hpp.html',1,'(Global Namespace)'],['../prim_2fun_2columns__dot__product_8hpp.html',1,'(Global Namespace)'],['../rev_2fun_2columns__dot__product_8hpp.html',1,'(Global Namespace)']]],
  ['columns_5fdot_5fself_2ehpp_87',['columns_dot_self.hpp',['../opencl_2prim_2columns__dot__self_8hpp.html',1,'(Global Namespace)'],['../opencl_2rev_2columns__dot__self_8hpp.html',1,'(Global Namespace)'],['../prim_2fun_2columns__dot__self_8hpp.html',1,'(Global Namespace)'],['../rev_2fun_2columns__dot__self_8hpp.html',1,'(Global Namespace)']]],
  ['colwise_5freduction_2ehpp_88',['colwise_reduction.hpp',['../colwise__reduction_8hpp.html',1,'']]],
  ['common_5fpitfalls_2emd_89',['common_pitfalls.md',['../common__pitfalls_8md.html',1,'']]],
  ['common_5freturn_5fscalar_2ehpp_90',['common_return_scalar.hpp',['../common__return__scalar_8hpp.html',1,'']]],
  ['compiler_5fattributes_2ehpp_91',['compiler_attributes.hpp',['../compiler__attributes_8hpp.html',1,'']]],
  ['complex_5fbase_2ehpp_92',['complex_base.hpp',['../complex__base_8hpp.html',1,'']]],
  ['complex_5fschur_5fdecompose_2ehpp_93',['complex_schur_decompose.hpp',['../complex__schur__decompose_8hpp.html',1,'']]],
  ['compound_5fassignments_2ehpp_94',['compound_assignments.hpp',['../compound__assignments_8hpp.html',1,'']]],
  ['conditional_5fvar_5fvalue_2ehpp_95',['conditional_var_value.hpp',['../conditional__var__value_8hpp.html',1,'']]],
  ['conj_2ehpp_96',['conj.hpp',['../fwd_2fun_2conj_8hpp.html',1,'(Global Namespace)'],['../prim_2fun_2conj_8hpp.html',1,'(Global Namespace)'],['../rev_2fun_2conj_8hpp.html',1,'(Global Namespace)']]],
  ['conjunction_2ehpp_97',['conjunction.hpp',['../conjunction_8hpp.html',1,'']]],
  ['constant_2ehpp_98',['constant.hpp',['../constant_8hpp.html',1,'']]],
  ['constants_2ehpp_99',['constants.hpp',['../constants_8hpp.html',1,'']]],
  ['constraint_5ftolerance_2ehpp_100',['constraint_tolerance.hpp',['../constraint__tolerance_8hpp.html',1,'']]],
  ['contains_5fstd_5fvector_2ehpp_101',['contains_std_vector.hpp',['../contains__std__vector_8hpp.html',1,'']]],
  ['contributing_2emd_102',['CONTRIBUTING.md',['../_c_o_n_t_r_i_b_u_t_i_n_g_8md.html',1,'']]],
  ['copy_2ehpp_103',['copy.hpp',['../copy_8hpp.html',1,'(Global Namespace)'],['../rev_2copy_8hpp.html',1,'(Global Namespace)']]],
  ['copysign_2ehpp_104',['copysign.hpp',['../copysign_8hpp.html',1,'']]],
  ['core_2ehpp_105',['core.hpp',['../rev_2core_8hpp.html',1,'(Global Namespace)'],['../prim_2core_8hpp.html',1,'(Global Namespace)'],['../fwd_2core_8hpp.html',1,'(Global Namespace)']]],
  ['corr_5fconstrain_2ehpp_106',['corr_constrain.hpp',['../corr__constrain_8hpp.html',1,'']]],
  ['corr_5ffree_2ehpp_107',['corr_free.hpp',['../corr__free_8hpp.html',1,'']]],
  ['corr_5fmatrix_5fconstrain_2ehpp_108',['corr_matrix_constrain.hpp',['../rev_2fun_2corr__matrix__constrain_8hpp.html',1,'(Global Namespace)'],['../prim_2fun_2corr__matrix__constrain_8hpp.html',1,'(Global Namespace)']]],
  ['corr_5fmatrix_5ffree_2ehpp_109',['corr_matrix_free.hpp',['../corr__matrix__free_8hpp.html',1,'']]],
  ['cos_2ehpp_110',['cos.hpp',['../fwd_2fun_2cos_8hpp.html',1,'(Global Namespace)'],['../opencl_2rev_2cos_8hpp.html',1,'(Global Namespace)'],['../prim_2fun_2cos_8hpp.html',1,'(Global Namespace)'],['../rev_2fun_2cos_8hpp.html',1,'(Global Namespace)']]],
  ['cosh_2ehpp_111',['cosh.hpp',['../fwd_2fun_2cosh_8hpp.html',1,'(Global Namespace)'],['../rev_2fun_2cosh_8hpp.html',1,'(Global Namespace)'],['../prim_2fun_2cosh_8hpp.html',1,'(Global Namespace)'],['../opencl_2rev_2cosh_8hpp.html',1,'(Global Namespace)']]],
  ['count_5fvars_2ehpp_112',['count_vars.hpp',['../count__vars_8hpp.html',1,'']]],
  ['coupled_5fode_5fsystem_2ehpp_113',['coupled_ode_system.hpp',['../prim_2functor_2coupled__ode__system_8hpp.html',1,'(Global Namespace)'],['../rev_2functor_2coupled__ode__system_8hpp.html',1,'(Global Namespace)']]],
  ['cov_5fexp_5fquad_2ehpp_114',['cov_exp_quad.hpp',['../prim_2fun_2cov__exp__quad_8hpp.html',1,'(Global Namespace)'],['../rev_2fun_2cov__exp__quad_8hpp.html',1,'(Global Namespace)']]],
  ['cov_5fmatrix_5fconstrain_2ehpp_115',['cov_matrix_constrain.hpp',['../prim_2fun_2cov__matrix__constrain_8hpp.html',1,'(Global Namespace)'],['../rev_2fun_2cov__matrix__constrain_8hpp.html',1,'(Global Namespace)']]],
  ['cov_5fmatrix_5fconstrain_5flkj_2ehpp_116',['cov_matrix_constrain_lkj.hpp',['../prim_2fun_2cov__matrix__constrain__lkj_8hpp.html',1,'(Global Namespace)'],['../rev_2fun_2cov__matrix__constrain__lkj_8hpp.html',1,'(Global Namespace)']]],
  ['cov_5fmatrix_5ffree_2ehpp_117',['cov_matrix_free.hpp',['../cov__matrix__free_8hpp.html',1,'']]],
  ['cov_5fmatrix_5ffree_5flkj_2ehpp_118',['cov_matrix_free_lkj.hpp',['../cov__matrix__free__lkj_8hpp.html',1,'']]],
  ['crossprod_2ehpp_119',['crossprod.hpp',['../opencl_2prim_2crossprod_8hpp.html',1,'(Global Namespace)'],['../opencl_2rev_2crossprod_8hpp.html',1,'(Global Namespace)'],['../prim_2fun_2crossprod_8hpp.html',1,'(Global Namespace)']]],
  ['csr_5fextract_2ehpp_120',['csr_extract.hpp',['../csr__extract_8hpp.html',1,'']]],
  ['csr_5fextract_5fu_2ehpp_121',['csr_extract_u.hpp',['../csr__extract__u_8hpp.html',1,'']]],
  ['csr_5fextract_5fv_2ehpp_122',['csr_extract_v.hpp',['../csr__extract__v_8hpp.html',1,'']]],
  ['csr_5fextract_5fw_2ehpp_123',['csr_extract_w.hpp',['../csr__extract__w_8hpp.html',1,'']]],
  ['csr_5fmatrix_5ftimes_5fvector_2ehpp_124',['csr_matrix_times_vector.hpp',['../prim_2fun_2csr__matrix__times__vector_8hpp.html',1,'(Global Namespace)'],['../rev_2fun_2csr__matrix__times__vector_8hpp.html',1,'(Global Namespace)']]],
  ['csr_5fto_5fdense_5fmatrix_2ehpp_125',['csr_to_dense_matrix.hpp',['../csr__to__dense__matrix_8hpp.html',1,'']]],
  ['csr_5fu_5fto_5fz_2ehpp_126',['csr_u_to_z.hpp',['../csr__u__to__z_8hpp.html',1,'']]],
  ['cumulative_5fsum_2ehpp_127',['cumulative_sum.hpp',['../opencl_2rev_2cumulative__sum_8hpp.html',1,'(Global Namespace)'],['../prim_2fun_2cumulative__sum_8hpp.html',1,'(Global Namespace)'],['../rev_2fun_2cumulative__sum_8hpp.html',1,'(Global Namespace)'],['../opencl_2prim_2cumulative__sum_8hpp.html',1,'(Global Namespace)'],['../opencl_2kernels_2cumulative__sum_8hpp.html',1,'(Global Namespace)']]],
  ['cvodes_5fintegrator_2ehpp_128',['cvodes_integrator.hpp',['../cvodes__integrator_8hpp.html',1,'']]],
  ['cvodes_5fintegrator_5fadjoint_2ehpp_129',['cvodes_integrator_adjoint.hpp',['../cvodes__integrator__adjoint_8hpp.html',1,'']]],
  ['cvodes_5futils_2ehpp_130',['cvodes_utils.hpp',['../cvodes__utils_8hpp.html',1,'']]]
];
