var searchData=
[
  ['rank_2ehpp_0',['rank.hpp',['../prim_2fun_2rank_8hpp.html',1,'(Global Namespace)'],['../opencl_2prim_2rank_8hpp.html',1,'(Global Namespace)']]],
  ['rayleigh_5fccdf_5flog_2ehpp_1',['rayleigh_ccdf_log.hpp',['../rayleigh__ccdf__log_8hpp.html',1,'']]],
  ['rayleigh_5fcdf_2ehpp_2',['rayleigh_cdf.hpp',['../prim_2prob_2rayleigh__cdf_8hpp.html',1,'(Global Namespace)'],['../opencl_2prim_2rayleigh__cdf_8hpp.html',1,'(Global Namespace)']]],
  ['rayleigh_5fcdf_5flog_2ehpp_3',['rayleigh_cdf_log.hpp',['../rayleigh__cdf__log_8hpp.html',1,'']]],
  ['rayleigh_5flccdf_2ehpp_4',['rayleigh_lccdf.hpp',['../prim_2prob_2rayleigh__lccdf_8hpp.html',1,'(Global Namespace)'],['../opencl_2prim_2rayleigh__lccdf_8hpp.html',1,'(Global Namespace)']]],
  ['rayleigh_5flcdf_2ehpp_5',['rayleigh_lcdf.hpp',['../prim_2prob_2rayleigh__lcdf_8hpp.html',1,'(Global Namespace)'],['../opencl_2prim_2rayleigh__lcdf_8hpp.html',1,'(Global Namespace)']]],
  ['rayleigh_5flog_2ehpp_6',['rayleigh_log.hpp',['../rayleigh__log_8hpp.html',1,'']]],
  ['rayleigh_5flpdf_2ehpp_7',['rayleigh_lpdf.hpp',['../prim_2prob_2rayleigh__lpdf_8hpp.html',1,'(Global Namespace)'],['../opencl_2prim_2rayleigh__lpdf_8hpp.html',1,'(Global Namespace)']]],
  ['rayleigh_5frng_2ehpp_8',['rayleigh_rng.hpp',['../rayleigh__rng_8hpp.html',1,'']]],
  ['read_5fcorr_5fl_2ehpp_9',['read_corr_L.hpp',['../rev_2fun_2read__corr___l_8hpp.html',1,'(Global Namespace)'],['../prim_2fun_2read__corr___l_8hpp.html',1,'(Global Namespace)']]],
  ['read_5fcorr_5fmatrix_2ehpp_10',['read_corr_matrix.hpp',['../prim_2fun_2read__corr__matrix_8hpp.html',1,'(Global Namespace)'],['../rev_2fun_2read__corr__matrix_8hpp.html',1,'(Global Namespace)']]],
  ['read_5fcov_5fl_2ehpp_11',['read_cov_L.hpp',['../prim_2fun_2read__cov___l_8hpp.html',1,'(Global Namespace)'],['../rev_2fun_2read__cov___l_8hpp.html',1,'(Global Namespace)']]],
  ['read_5fcov_5fmatrix_2ehpp_12',['read_cov_matrix.hpp',['../prim_2fun_2read__cov__matrix_8hpp.html',1,'(Global Namespace)'],['../rev_2fun_2read__cov__matrix_8hpp.html',1,'(Global Namespace)']]],
  ['read_5ffvar_2ehpp_13',['read_fvar.hpp',['../read__fvar_8hpp.html',1,'']]],
  ['read_5fvar_2ehpp_14',['read_var.hpp',['../read__var_8hpp.html',1,'']]],
  ['readme_2emd_15',['README.md',['../_r_e_a_d_m_e_8md.html',1,'']]],
  ['real_2ehpp_16',['real.hpp',['../real_8hpp.html',1,'']]],
  ['recover_5fmemory_2ehpp_17',['recover_memory.hpp',['../recover__memory_8hpp.html',1,'']]],
  ['recover_5fmemory_5fnested_2ehpp_18',['recover_memory_nested.hpp',['../recover__memory__nested_8hpp.html',1,'']]],
  ['reduce_5fsum_2ehpp_19',['reduce_sum.hpp',['../prim_2functor_2reduce__sum_8hpp.html',1,'(Global Namespace)'],['../fwd_2functor_2reduce__sum_8hpp.html',1,'(Global Namespace)'],['../rev_2functor_2reduce__sum_8hpp.html',1,'(Global Namespace)']]],
  ['reduce_5fsum_5fstatic_2ehpp_20',['reduce_sum_static.hpp',['../reduce__sum__static_8hpp.html',1,'']]],
  ['reduction_5f2d_2ehpp_21',['reduction_2d.hpp',['../reduction__2d_8hpp.html',1,'']]],
  ['ref_5ftype_2ehpp_22',['ref_type.hpp',['../opencl_2ref__type_8hpp.html',1,'(Global Namespace)'],['../prim_2meta_2ref__type_8hpp.html',1,'(Global Namespace)']]],
  ['ref_5ftype_5ffor_5fopencl_2ehpp_23',['ref_type_for_opencl.hpp',['../ref__type__for__opencl_8hpp.html',1,'']]],
  ['rep_5farray_2ehpp_24',['rep_array.hpp',['../opencl_2prim_2rep__array_8hpp.html',1,'(Global Namespace)'],['../prim_2fun_2rep__array_8hpp.html',1,'(Global Namespace)']]],
  ['rep_5fmatrix_2ehpp_25',['rep_matrix.hpp',['../rev_2fun_2rep__matrix_8hpp.html',1,'(Global Namespace)'],['../opencl_2kernels_2rep__matrix_8hpp.html',1,'(Global Namespace)'],['../opencl_2prim_2rep__matrix_8hpp.html',1,'(Global Namespace)'],['../opencl_2rev_2rep__matrix_8hpp.html',1,'(Global Namespace)'],['../prim_2fun_2rep__matrix_8hpp.html',1,'(Global Namespace)']]],
  ['rep_5frow_5fvector_2ehpp_26',['rep_row_vector.hpp',['../rev_2fun_2rep__row__vector_8hpp.html',1,'(Global Namespace)'],['../prim_2fun_2rep__row__vector_8hpp.html',1,'(Global Namespace)'],['../opencl_2prim_2rep__row__vector_8hpp.html',1,'(Global Namespace)']]],
  ['rep_5fvector_2ehpp_27',['rep_vector.hpp',['../rev_2fun_2rep__vector_8hpp.html',1,'(Global Namespace)'],['../opencl_2prim_2rep__vector_8hpp.html',1,'(Global Namespace)'],['../prim_2fun_2rep__vector_8hpp.html',1,'(Global Namespace)']]],
  ['require_5fgenerics_2ehpp_28',['require_generics.hpp',['../require__generics_8hpp.html',1,'']]],
  ['require_5fhelpers_2ehpp_29',['require_helpers.hpp',['../require__helpers_8hpp.html',1,'']]],
  ['require_5fmeta_2emd_30',['require_meta.md',['../require__meta_8md.html',1,'']]],
  ['resize_2ehpp_31',['resize.hpp',['../resize_8hpp.html',1,'']]],
  ['return_5ftype_2ehpp_32',['return_type.hpp',['../return__type_8hpp.html',1,'']]],
  ['return_5fvar_5fmatrix_2ehpp_33',['return_var_matrix.hpp',['../return__var__matrix_8hpp.html',1,'']]],
  ['rev_2ehpp_34',['rev.hpp',['../rev_8hpp.html',1,'(Global Namespace)'],['../opencl_2rev_8hpp.html',1,'(Global Namespace)']]],
  ['rev_5fmatrix_5ftype_2ehpp_35',['rev_matrix_type.hpp',['../rev__matrix__type_8hpp.html',1,'']]],
  ['reverse_2ehpp_36',['reverse.hpp',['../prim_2fun_2reverse_8hpp.html',1,'(Global Namespace)'],['../opencl_2rev_2reverse_8hpp.html',1,'(Global Namespace)'],['../opencl_2prim_2reverse_8hpp.html',1,'(Global Namespace)']]],
  ['reverse_5fmode_5ftypes_2emd_37',['reverse_mode_types.md',['../reverse__mode__types_8md.html',1,'']]],
  ['reverse_5fpass_5fcallback_2ehpp_38',['reverse_pass_callback.hpp',['../reverse__pass__callback_8hpp.html',1,'']]],
  ['rising_5ffactorial_2ehpp_39',['rising_factorial.hpp',['../fwd_2fun_2rising__factorial_8hpp.html',1,'(Global Namespace)'],['../prim_2fun_2rising__factorial_8hpp.html',1,'(Global Namespace)'],['../rev_2fun_2rising__factorial_8hpp.html',1,'(Global Namespace)']]],
  ['round_2ehpp_40',['round.hpp',['../fwd_2fun_2round_8hpp.html',1,'(Global Namespace)'],['../opencl_2rev_2round_8hpp.html',1,'(Global Namespace)'],['../prim_2fun_2round_8hpp.html',1,'(Global Namespace)'],['../rev_2fun_2round_8hpp.html',1,'(Global Namespace)']]],
  ['row_2ehpp_41',['row.hpp',['../prim_2fun_2row_8hpp.html',1,'(Global Namespace)'],['../opencl_2prim_2row_8hpp.html',1,'(Global Namespace)']]],
  ['rows_2ehpp_42',['rows.hpp',['../prim_2fun_2rows_8hpp.html',1,'(Global Namespace)'],['../opencl_2prim_2rows_8hpp.html',1,'(Global Namespace)']]],
  ['rows_5fdot_5fproduct_2ehpp_43',['rows_dot_product.hpp',['../prim_2fun_2rows__dot__product_8hpp.html',1,'(Global Namespace)'],['../opencl_2prim_2rows__dot__product_8hpp.html',1,'(Global Namespace)'],['../opencl_2rev_2rows__dot__product_8hpp.html',1,'(Global Namespace)'],['../rev_2fun_2rows__dot__product_8hpp.html',1,'(Global Namespace)']]],
  ['rows_5fdot_5fself_2ehpp_44',['rows_dot_self.hpp',['../opencl_2prim_2rows__dot__self_8hpp.html',1,'(Global Namespace)'],['../opencl_2rev_2rows__dot__self_8hpp.html',1,'(Global Namespace)'],['../prim_2fun_2rows__dot__self_8hpp.html',1,'(Global Namespace)'],['../rev_2fun_2rows__dot__self_8hpp.html',1,'(Global Namespace)']]],
  ['rowwise_5freduction_2ehpp_45',['rowwise_reduction.hpp',['../rowwise__reduction_8hpp.html',1,'']]]
];
