var searchData=
[
  ['save_5fvaris_2ehpp_0',['save_varis.hpp',['../save__varis_8hpp.html',1,'']]],
  ['scalar_2ehpp_1',['scalar.hpp',['../scalar_8hpp.html',1,'']]],
  ['scalar_5fseq_5fview_2ehpp_2',['scalar_seq_view.hpp',['../scalar__seq__view_8hpp.html',1,'']]],
  ['scalar_5ftype_2ehpp_3',['scalar_type.hpp',['../opencl_2scalar__type_8hpp.html',1,'(Global Namespace)'],['../prim_2meta_2scalar__type_8hpp.html',1,'(Global Namespace)']]],
  ['scalbn_2ehpp_4',['scalbn.hpp',['../scalbn_8hpp.html',1,'']]],
  ['scale_5fmatrix_5fexp_5fmultiply_2ehpp_5',['scale_matrix_exp_multiply.hpp',['../scale__matrix__exp__multiply_8hpp.html',1,'']]],
  ['scaled_5fadd_2ehpp_6',['scaled_add.hpp',['../scaled__add_8hpp.html',1,'']]],
  ['scaled_5finv_5fchi_5fsquare_5fccdf_5flog_2ehpp_7',['scaled_inv_chi_square_ccdf_log.hpp',['../scaled__inv__chi__square__ccdf__log_8hpp.html',1,'']]],
  ['scaled_5finv_5fchi_5fsquare_5fcdf_2ehpp_8',['scaled_inv_chi_square_cdf.hpp',['../scaled__inv__chi__square__cdf_8hpp.html',1,'']]],
  ['scaled_5finv_5fchi_5fsquare_5fcdf_5flog_2ehpp_9',['scaled_inv_chi_square_cdf_log.hpp',['../scaled__inv__chi__square__cdf__log_8hpp.html',1,'']]],
  ['scaled_5finv_5fchi_5fsquare_5flccdf_2ehpp_10',['scaled_inv_chi_square_lccdf.hpp',['../scaled__inv__chi__square__lccdf_8hpp.html',1,'']]],
  ['scaled_5finv_5fchi_5fsquare_5flcdf_2ehpp_11',['scaled_inv_chi_square_lcdf.hpp',['../scaled__inv__chi__square__lcdf_8hpp.html',1,'']]],
  ['scaled_5finv_5fchi_5fsquare_5flog_2ehpp_12',['scaled_inv_chi_square_log.hpp',['../scaled__inv__chi__square__log_8hpp.html',1,'']]],
  ['scaled_5finv_5fchi_5fsquare_5flpdf_2ehpp_13',['scaled_inv_chi_square_lpdf.hpp',['../opencl_2prim_2scaled__inv__chi__square__lpdf_8hpp.html',1,'(Global Namespace)'],['../prim_2prob_2scaled__inv__chi__square__lpdf_8hpp.html',1,'(Global Namespace)']]],
  ['scaled_5finv_5fchi_5fsquare_5frng_2ehpp_14',['scaled_inv_chi_square_rng.hpp',['../scaled__inv__chi__square__rng_8hpp.html',1,'']]],
  ['scoped_5fchainablestack_2ehpp_15',['scoped_chainablestack.hpp',['../scoped__chainablestack_8hpp.html',1,'']]],
  ['sd_2ehpp_16',['sd.hpp',['../opencl_2prim_2sd_8hpp.html',1,'(Global Namespace)'],['../opencl_2rev_2sd_8hpp.html',1,'(Global Namespace)'],['../rev_2fun_2sd_8hpp.html',1,'(Global Namespace)'],['../prim_2fun_2sd_8hpp.html',1,'(Global Namespace)']]],
  ['segment_2ehpp_17',['segment.hpp',['../prim_2fun_2segment_8hpp.html',1,'(Global Namespace)'],['../opencl_2prim_2segment_8hpp.html',1,'(Global Namespace)']]],
  ['select_2ehpp_18',['select.hpp',['../prim_2fun_2select_8hpp.html',1,'(Global Namespace)'],['../opencl_2kernel__generator_2select_8hpp.html',1,'(Global Namespace)']]],
  ['seq_5fview_2ehpp_19',['seq_view.hpp',['../seq__view_8hpp.html',1,'']]],
  ['serializer_2ehpp_20',['serializer.hpp',['../serializer_8hpp.html',1,'']]],
  ['set_5fzero_5fall_5fadjoints_2ehpp_21',['set_zero_all_adjoints.hpp',['../set__zero__all__adjoints_8hpp.html',1,'']]],
  ['set_5fzero_5fall_5fadjoints_5fnested_2ehpp_22',['set_zero_all_adjoints_nested.hpp',['../set__zero__all__adjoints__nested_8hpp.html',1,'']]],
  ['sign_2ehpp_23',['sign.hpp',['../opencl_2prim_2sign_8hpp.html',1,'(Global Namespace)'],['../prim_2fun_2sign_8hpp.html',1,'(Global Namespace)']]],
  ['signbit_2ehpp_24',['signbit.hpp',['../signbit_8hpp.html',1,'']]],
  ['simplex_5fconstrain_2ehpp_25',['simplex_constrain.hpp',['../rev_2fun_2simplex__constrain_8hpp.html',1,'(Global Namespace)'],['../prim_2fun_2simplex__constrain_8hpp.html',1,'(Global Namespace)']]],
  ['simplex_5ffree_2ehpp_26',['simplex_free.hpp',['../simplex__free_8hpp.html',1,'']]],
  ['sin_2ehpp_27',['sin.hpp',['../fwd_2fun_2sin_8hpp.html',1,'(Global Namespace)'],['../opencl_2rev_2sin_8hpp.html',1,'(Global Namespace)'],['../prim_2fun_2sin_8hpp.html',1,'(Global Namespace)'],['../rev_2fun_2sin_8hpp.html',1,'(Global Namespace)']]],
  ['singular_5fvalues_2ehpp_28',['singular_values.hpp',['../prim_2fun_2singular__values_8hpp.html',1,'(Global Namespace)'],['../rev_2fun_2singular__values_8hpp.html',1,'(Global Namespace)']]],
  ['sinh_2ehpp_29',['sinh.hpp',['../rev_2fun_2sinh_8hpp.html',1,'(Global Namespace)'],['../prim_2fun_2sinh_8hpp.html',1,'(Global Namespace)'],['../opencl_2rev_2sinh_8hpp.html',1,'(Global Namespace)'],['../fwd_2fun_2sinh_8hpp.html',1,'(Global Namespace)']]],
  ['size_2ehpp_30',['size.hpp',['../opencl_2prim_2size_8hpp.html',1,'(Global Namespace)'],['../prim_2fun_2size_8hpp.html',1,'(Global Namespace)']]],
  ['size_5fmvt_2ehpp_31',['size_mvt.hpp',['../size__mvt_8hpp.html',1,'']]],
  ['size_5fzero_2ehpp_32',['size_zero.hpp',['../size__zero_8hpp.html',1,'']]],
  ['skew_5fdouble_5fexponential_5fccdf_5flog_2ehpp_33',['skew_double_exponential_ccdf_log.hpp',['../skew__double__exponential__ccdf__log_8hpp.html',1,'']]],
  ['skew_5fdouble_5fexponential_5fcdf_2ehpp_34',['skew_double_exponential_cdf.hpp',['../opencl_2prim_2skew__double__exponential__cdf_8hpp.html',1,'(Global Namespace)'],['../prim_2prob_2skew__double__exponential__cdf_8hpp.html',1,'(Global Namespace)']]],
  ['skew_5fdouble_5fexponential_5fcdf_5flog_2ehpp_35',['skew_double_exponential_cdf_log.hpp',['../skew__double__exponential__cdf__log_8hpp.html',1,'']]],
  ['skew_5fdouble_5fexponential_5flccdf_2ehpp_36',['skew_double_exponential_lccdf.hpp',['../opencl_2prim_2skew__double__exponential__lccdf_8hpp.html',1,'(Global Namespace)'],['../prim_2prob_2skew__double__exponential__lccdf_8hpp.html',1,'(Global Namespace)']]],
  ['skew_5fdouble_5fexponential_5flcdf_2ehpp_37',['skew_double_exponential_lcdf.hpp',['../opencl_2prim_2skew__double__exponential__lcdf_8hpp.html',1,'(Global Namespace)'],['../prim_2prob_2skew__double__exponential__lcdf_8hpp.html',1,'(Global Namespace)']]],
  ['skew_5fdouble_5fexponential_5flog_2ehpp_38',['skew_double_exponential_log.hpp',['../skew__double__exponential__log_8hpp.html',1,'']]],
  ['skew_5fdouble_5fexponential_5flpdf_2ehpp_39',['skew_double_exponential_lpdf.hpp',['../opencl_2prim_2skew__double__exponential__lpdf_8hpp.html',1,'(Global Namespace)'],['../prim_2prob_2skew__double__exponential__lpdf_8hpp.html',1,'(Global Namespace)']]],
  ['skew_5fdouble_5fexponential_5frng_2ehpp_40',['skew_double_exponential_rng.hpp',['../skew__double__exponential__rng_8hpp.html',1,'']]],
  ['skew_5fnormal_5fccdf_5flog_2ehpp_41',['skew_normal_ccdf_log.hpp',['../skew__normal__ccdf__log_8hpp.html',1,'']]],
  ['skew_5fnormal_5fcdf_2ehpp_42',['skew_normal_cdf.hpp',['../skew__normal__cdf_8hpp.html',1,'']]],
  ['skew_5fnormal_5fcdf_5flog_2ehpp_43',['skew_normal_cdf_log.hpp',['../skew__normal__cdf__log_8hpp.html',1,'']]],
  ['skew_5fnormal_5flccdf_2ehpp_44',['skew_normal_lccdf.hpp',['../skew__normal__lccdf_8hpp.html',1,'']]],
  ['skew_5fnormal_5flcdf_2ehpp_45',['skew_normal_lcdf.hpp',['../skew__normal__lcdf_8hpp.html',1,'']]],
  ['skew_5fnormal_5flog_2ehpp_46',['skew_normal_log.hpp',['../skew__normal__log_8hpp.html',1,'']]],
  ['skew_5fnormal_5flpdf_2ehpp_47',['skew_normal_lpdf.hpp',['../prim_2prob_2skew__normal__lpdf_8hpp.html',1,'(Global Namespace)'],['../opencl_2prim_2skew__normal__lpdf_8hpp.html',1,'(Global Namespace)']]],
  ['skew_5fnormal_5frng_2ehpp_48',['skew_normal_rng.hpp',['../skew__normal__rng_8hpp.html',1,'']]],
  ['softmax_2ehpp_49',['softmax.hpp',['../fwd_2fun_2softmax_8hpp.html',1,'(Global Namespace)'],['../opencl_2prim_2softmax_8hpp.html',1,'(Global Namespace)'],['../opencl_2rev_2softmax_8hpp.html',1,'(Global Namespace)'],['../prim_2fun_2softmax_8hpp.html',1,'(Global Namespace)'],['../rev_2fun_2softmax_8hpp.html',1,'(Global Namespace)']]],
  ['solve_5fnewton_2ehpp_50',['solve_newton.hpp',['../solve__newton_8hpp.html',1,'']]],
  ['solve_5fpowell_2ehpp_51',['solve_powell.hpp',['../solve__powell_8hpp.html',1,'']]],
  ['sort_5fasc_2ehpp_52',['sort_asc.hpp',['../prim_2fun_2sort__asc_8hpp.html',1,'(Global Namespace)'],['../opencl_2prim_2sort__asc_8hpp.html',1,'(Global Namespace)']]],
  ['sort_5fdesc_2ehpp_53',['sort_desc.hpp',['../prim_2fun_2sort__desc_8hpp.html',1,'(Global Namespace)'],['../opencl_2prim_2sort__desc_8hpp.html',1,'(Global Namespace)']]],
  ['sort_5findices_2ehpp_54',['sort_indices.hpp',['../sort__indices_8hpp.html',1,'']]],
  ['sort_5findices_5fasc_2ehpp_55',['sort_indices_asc.hpp',['../sort__indices__asc_8hpp.html',1,'']]],
  ['sort_5findices_5fdesc_2ehpp_56',['sort_indices_desc.hpp',['../sort__indices__desc_8hpp.html',1,'']]],
  ['sqrt_2ehpp_57',['sqrt.hpp',['../rev_2fun_2sqrt_8hpp.html',1,'(Global Namespace)'],['../prim_2fun_2sqrt_8hpp.html',1,'(Global Namespace)'],['../opencl_2rev_2sqrt_8hpp.html',1,'(Global Namespace)'],['../fwd_2fun_2sqrt_8hpp.html',1,'(Global Namespace)']]],
  ['square_2ehpp_58',['square.hpp',['../rev_2fun_2square_8hpp.html',1,'(Global Namespace)'],['../prim_2fun_2square_8hpp.html',1,'(Global Namespace)'],['../opencl_2rev_2square_8hpp.html',1,'(Global Namespace)'],['../fwd_2fun_2square_8hpp.html',1,'(Global Namespace)']]],
  ['squared_5fdistance_2ehpp_59',['squared_distance.hpp',['../opencl_2prim_2squared__distance_8hpp.html',1,'(Global Namespace)'],['../rev_2fun_2squared__distance_8hpp.html',1,'(Global Namespace)'],['../prim_2fun_2squared__distance_8hpp.html',1,'(Global Namespace)'],['../opencl_2rev_2squared__distance_8hpp.html',1,'(Global Namespace)']]],
  ['stack_5falloc_2ehpp_60',['stack_alloc.hpp',['../stack__alloc_8hpp.html',1,'']]],
  ['stan_2edox_61',['stan.dox',['../stan_8dox.html',1,'']]],
  ['stan_5fprint_2ehpp_62',['stan_print.hpp',['../prim_2fun_2stan__print_8hpp.html',1,'(Global Namespace)'],['../rev_2fun_2stan__print_8hpp.html',1,'(Global Namespace)']]],
  ['start_5fnested_2ehpp_63',['start_nested.hpp',['../start__nested_8hpp.html',1,'']]],
  ['static_5fselect_2ehpp_64',['static_select.hpp',['../static__select_8hpp.html',1,'']]],
  ['std_5fcomplex_2ehpp_65',['std_complex.hpp',['../fwd_2core_2std__complex_8hpp.html',1,'(Global Namespace)'],['../rev_2core_2std__complex_8hpp.html',1,'(Global Namespace)']]],
  ['std_5fisinf_2ehpp_66',['std_isinf.hpp',['../std__isinf_8hpp.html',1,'']]],
  ['std_5fisnan_2ehpp_67',['std_isnan.hpp',['../std__isnan_8hpp.html',1,'']]],
  ['std_5fiterator_5ftraits_2ehpp_68',['std_iterator_traits.hpp',['../rev_2core_2std__iterator__traits_8hpp.html',1,'(Global Namespace)'],['../fwd_2core_2std__iterator__traits_8hpp.html',1,'(Global Namespace)']]],
  ['std_5fnormal_5fccdf_5flog_2ehpp_69',['std_normal_ccdf_log.hpp',['../std__normal__ccdf__log_8hpp.html',1,'']]],
  ['std_5fnormal_5fcdf_2ehpp_70',['std_normal_cdf.hpp',['../opencl_2prim_2std__normal__cdf_8hpp.html',1,'(Global Namespace)'],['../prim_2prob_2std__normal__cdf_8hpp.html',1,'(Global Namespace)']]],
  ['std_5fnormal_5fcdf_5flog_2ehpp_71',['std_normal_cdf_log.hpp',['../std__normal__cdf__log_8hpp.html',1,'']]],
  ['std_5fnormal_5flccdf_2ehpp_72',['std_normal_lccdf.hpp',['../opencl_2prim_2std__normal__lccdf_8hpp.html',1,'(Global Namespace)'],['../prim_2prob_2std__normal__lccdf_8hpp.html',1,'(Global Namespace)']]],
  ['std_5fnormal_5flcdf_2ehpp_73',['std_normal_lcdf.hpp',['../opencl_2prim_2std__normal__lcdf_8hpp.html',1,'(Global Namespace)'],['../prim_2prob_2std__normal__lcdf_8hpp.html',1,'(Global Namespace)']]],
  ['std_5fnormal_5flog_2ehpp_74',['std_normal_log.hpp',['../std__normal__log_8hpp.html',1,'']]],
  ['std_5fnormal_5flog_5fqf_2ehpp_75',['std_normal_log_qf.hpp',['../fwd_2prob_2std__normal__log__qf_8hpp.html',1,'(Global Namespace)'],['../rev_2prob_2std__normal__log__qf_8hpp.html',1,'(Global Namespace)'],['../prim_2prob_2std__normal__log__qf_8hpp.html',1,'(Global Namespace)']]],
  ['std_5fnormal_5flpdf_2ehpp_76',['std_normal_lpdf.hpp',['../prim_2prob_2std__normal__lpdf_8hpp.html',1,'(Global Namespace)'],['../opencl_2prim_2std__normal__lpdf_8hpp.html',1,'(Global Namespace)']]],
  ['std_5fnormal_5frng_2ehpp_77',['std_normal_rng.hpp',['../std__normal__rng_8hpp.html',1,'']]],
  ['std_5fnumeric_5flimits_2ehpp_78',['std_numeric_limits.hpp',['../rev_2core_2std__numeric__limits_8hpp.html',1,'(Global Namespace)'],['../fwd_2core_2std__numeric__limits_8hpp.html',1,'(Global Namespace)']]],
  ['stdvectorbuilder_2ehpp_79',['StdVectorBuilder.hpp',['../_std_vector_builder_8hpp.html',1,'']]],
  ['step_2ehpp_80',['step.hpp',['../prim_2fun_2step_8hpp.html',1,'(Global Namespace)'],['../rev_2fun_2step_8hpp.html',1,'(Global Namespace)']]],
  ['stochastic_5fcolumn_5fconstrain_2ehpp_81',['stochastic_column_constrain.hpp',['../prim_2fun_2stochastic__column__constrain_8hpp.html',1,'(Global Namespace)'],['../rev_2fun_2stochastic__column__constrain_8hpp.html',1,'(Global Namespace)']]],
  ['stochastic_5fcolumn_5ffree_2ehpp_82',['stochastic_column_free.hpp',['../stochastic__column__free_8hpp.html',1,'']]],
  ['stochastic_5frow_5fconstrain_2ehpp_83',['stochastic_row_constrain.hpp',['../rev_2fun_2stochastic__row__constrain_8hpp.html',1,'(Global Namespace)'],['../prim_2fun_2stochastic__row__constrain_8hpp.html',1,'(Global Namespace)']]],
  ['stochastic_5frow_5ffree_2ehpp_84',['stochastic_row_free.hpp',['../stochastic__row__free_8hpp.html',1,'']]],
  ['stored_5fgradient_5fvari_2ehpp_85',['stored_gradient_vari.hpp',['../stored__gradient__vari_8hpp.html',1,'']]],
  ['stringify_2ehpp_86',['stringify.hpp',['../stringify_8hpp.html',1,'']]],
  ['student_5ft_5fccdf_5flog_2ehpp_87',['student_t_ccdf_log.hpp',['../student__t__ccdf__log_8hpp.html',1,'']]],
  ['student_5ft_5fcdf_2ehpp_88',['student_t_cdf.hpp',['../student__t__cdf_8hpp.html',1,'']]],
  ['student_5ft_5fcdf_5flog_2ehpp_89',['student_t_cdf_log.hpp',['../student__t__cdf__log_8hpp.html',1,'']]],
  ['student_5ft_5flccdf_2ehpp_90',['student_t_lccdf.hpp',['../student__t__lccdf_8hpp.html',1,'']]],
  ['student_5ft_5flcdf_2ehpp_91',['student_t_lcdf.hpp',['../student__t__lcdf_8hpp.html',1,'']]],
  ['student_5ft_5flog_2ehpp_92',['student_t_log.hpp',['../student__t__log_8hpp.html',1,'']]],
  ['student_5ft_5flpdf_2ehpp_93',['student_t_lpdf.hpp',['../opencl_2prim_2student__t__lpdf_8hpp.html',1,'(Global Namespace)'],['../prim_2prob_2student__t__lpdf_8hpp.html',1,'(Global Namespace)']]],
  ['student_5ft_5frng_2ehpp_94',['student_t_rng.hpp',['../student__t__rng_8hpp.html',1,'']]],
  ['sub_5fcol_2ehpp_95',['sub_col.hpp',['../prim_2fun_2sub__col_8hpp.html',1,'(Global Namespace)'],['../opencl_2prim_2sub__col_8hpp.html',1,'(Global Namespace)']]],
  ['sub_5frow_2ehpp_96',['sub_row.hpp',['../prim_2fun_2sub__row_8hpp.html',1,'(Global Namespace)'],['../opencl_2prim_2sub__row_8hpp.html',1,'(Global Namespace)']]],
  ['subtract_2ehpp_97',['subtract.hpp',['../opencl_2rev_2subtract_8hpp.html',1,'(Global Namespace)'],['../prim_2fun_2subtract_8hpp.html',1,'(Global Namespace)']]],
  ['sum_2ehpp_98',['sum.hpp',['../opencl_2rev_2sum_8hpp.html',1,'(Global Namespace)'],['../opencl_2prim_2sum_8hpp.html',1,'(Global Namespace)'],['../fwd_2fun_2sum_8hpp.html',1,'(Global Namespace)'],['../rev_2fun_2sum_8hpp.html',1,'(Global Namespace)'],['../prim_2fun_2sum_8hpp.html',1,'(Global Namespace)']]],
  ['svd_2ehpp_99',['svd.hpp',['../rev_2fun_2svd_8hpp.html',1,'(Global Namespace)'],['../prim_2fun_2svd_8hpp.html',1,'(Global Namespace)']]],
  ['svd_5fu_2ehpp_100',['svd_U.hpp',['../rev_2fun_2svd___u_8hpp.html',1,'(Global Namespace)'],['../prim_2fun_2svd___u_8hpp.html',1,'(Global Namespace)']]],
  ['svd_5fv_2ehpp_101',['svd_V.hpp',['../rev_2fun_2svd___v_8hpp.html',1,'(Global Namespace)'],['../prim_2fun_2svd___v_8hpp.html',1,'(Global Namespace)']]],
  ['symmetric_5feigensolver_2ehpp_102',['symmetric_eigensolver.hpp',['../symmetric__eigensolver_8hpp.html',1,'']]],
  ['symmetrize_5ffrom_5flower_5ftri_2ehpp_103',['symmetrize_from_lower_tri.hpp',['../prim_2fun_2symmetrize__from__lower__tri_8hpp.html',1,'(Global Namespace)'],['../opencl_2rev_2symmetrize__from__lower__tri_8hpp.html',1,'(Global Namespace)'],['../opencl_2prim_2symmetrize__from__lower__tri_8hpp.html',1,'(Global Namespace)']]],
  ['symmetrize_5ffrom_5fupper_5ftri_2ehpp_104',['symmetrize_from_upper_tri.hpp',['../opencl_2rev_2symmetrize__from__upper__tri_8hpp.html',1,'(Global Namespace)'],['../opencl_2prim_2symmetrize__from__upper__tri_8hpp.html',1,'(Global Namespace)'],['../prim_2fun_2symmetrize__from__upper__tri_8hpp.html',1,'(Global Namespace)']]],
  ['system_5ferror_2ehpp_105',['system_error.hpp',['../system__error_8hpp.html',1,'']]]
];
