#include <test/unit/math/prim/err/is_column_index_test.cpp>
#include <test/unit/math/prim/err/is_corr_matrix_test.cpp>
#include <test/unit/math/prim/err/is_ldlt_factor_test.cpp>
#include <test/unit/math/prim/err/is_less_or_equal_test.cpp>
#include <test/unit/math/prim/err/is_lower_triangular_test.cpp>
#include <test/unit/math/prim/err/is_mat_finite_test.cpp>
#include <test/unit/math/prim/err/is_matching_dims_test.cpp>
#include <test/unit/math/prim/err/is_matching_size_test.cpp>
#include <test/unit/math/prim/err/is_nonzero_size_test.cpp>
#include <test/unit/math/prim/err/is_not_nan_test.cpp>
#include <test/unit/math/prim/err/is_ordered_test.cpp>
#include <test/unit/math/prim/err/is_pos_definite_test.cpp>
#include <test/unit/math/prim/err/is_positive_test.cpp>
#include <test/unit/math/prim/err/is_scal_finite_test.cpp>
#include <test/unit/math/prim/err/is_size_match_test.cpp>
