#include <test/unit/math/prim/err/check_lower_triangular_test.cpp>
#include <test/unit/math/prim/err/check_matching_dims_test.cpp>
#include <test/unit/math/prim/err/check_matching_sizes_test.cpp>
#include <test/unit/math/prim/err/check_multiplicable_test.cpp>
#include <test/unit/math/prim/err/check_nonnegative_test.cpp>
#include <test/unit/math/prim/err/check_nonzero_size_test.cpp>
#include <test/unit/math/prim/err/check_not_nan_test.cpp>
#include <test/unit/math/prim/err/check_ordered_test.cpp>
#include <test/unit/math/prim/err/check_pos_definite_test.cpp>
#include <test/unit/math/prim/err/check_pos_semidefinite_test.cpp>
#include <test/unit/math/prim/err/check_positive_finite_test.cpp>
#include <test/unit/math/prim/err/check_positive_ordered_test.cpp>
#include <test/unit/math/prim/err/check_positive_test.cpp>
#include <test/unit/math/prim/err/check_range_test.cpp>
#include <test/unit/math/prim/err/check_row_index_test.cpp>
