#include <test/unit/math/prim/err/check_2F1_converges_test.cpp>
#include <test/unit/math/prim/err/check_3F2_converges_test.cpp>
#include <test/unit/math/prim/err/check_bounded_test.cpp>
#include <test/unit/math/prim/err/check_cholesky_factor_corr_test.cpp>
#include <test/unit/math/prim/err/check_cholesky_factor_test.cpp>
#include <test/unit/math/prim/err/check_column_index_test.cpp>
#include <test/unit/math/prim/err/check_consistent_sizes_mvt_test.cpp>
#include <test/unit/math/prim/err/check_corr_matrix_test.cpp>
#include <test/unit/math/prim/err/check_cov_matrix_test.cpp>
#include <test/unit/math/prim/err/check_finite_test.cpp>
#include <test/unit/math/prim/err/check_greater_or_equal_test.cpp>
#include <test/unit/math/prim/err/check_greater_test.cpp>
#include <test/unit/math/prim/err/check_ldlt_factor_test.cpp>
#include <test/unit/math/prim/err/check_less_or_equal_test.cpp>
#include <test/unit/math/prim/err/check_less_test.cpp>
