#include <test/unit/math/prim/fun/one_hot_int_array_test.cpp>
#include <test/unit/math/prim/fun/one_hot_row_vector_test.cpp>
#include <test/unit/math/prim/fun/one_hot_vector_test.cpp>
#include <test/unit/math/prim/fun/ones_array_test.cpp>
#include <test/unit/math/prim/fun/ones_int_array_test.cpp>
#include <test/unit/math/prim/fun/ones_row_vector_test.cpp>
#include <test/unit/math/prim/fun/ones_vector_test.cpp>
#include <test/unit/math/prim/fun/ordered_transform_test.cpp>
#include <test/unit/math/prim/fun/owens_t_test.cpp>
#include <test/unit/math/prim/fun/plus_test.cpp>
#include <test/unit/math/prim/fun/poisson_binomial_log_probs_test.cpp>
#include <test/unit/math/prim/fun/positive_ordered_transform_test.cpp>
#include <test/unit/math/prim/fun/positive_transform_test.cpp>
#include <test/unit/math/prim/fun/pow_test.cpp>
#include <test/unit/math/prim/fun/primitive_value_test.cpp>
