#include <test/unit/math/prim/fun/rep_matrix_test.cpp>
#include <test/unit/math/prim/fun/rep_row_vector_test.cpp>
#include <test/unit/math/prim/fun/rep_vector_test.cpp>
#include <test/unit/math/prim/fun/resize_test.cpp>
#include <test/unit/math/prim/fun/reverse_test.cpp>
#include <test/unit/math/prim/fun/rising_factorial_test.cpp>
#include <test/unit/math/prim/fun/round_test.cpp>
#include <test/unit/math/prim/fun/row_test.cpp>
#include <test/unit/math/prim/fun/rows_dot_self_test.cpp>
#include <test/unit/math/prim/fun/rows_test.cpp>
#include <test/unit/math/prim/fun/scalar_seq_view_test.cpp>
#include <test/unit/math/prim/fun/scale_matrix_exp_multiply_test.cpp>
#include <test/unit/math/prim/fun/scaled_add_test.cpp>
#include <test/unit/math/prim/fun/sd_test.cpp>
#include <test/unit/math/prim/fun/segment_test.cpp>
