#include <test/unit/math/prim/fun/grad_reg_inc_beta_test.cpp>
#include <test/unit/math/prim/fun/grad_reg_inc_gamma_test.cpp>
#include <test/unit/math/prim/fun/grad_reg_lower_inc_gamma_test.cpp>
#include <test/unit/math/prim/fun/head_test.cpp>
#include <test/unit/math/prim/fun/hypot_test.cpp>
#include <test/unit/math/prim/fun/identity_matrix_test.cpp>
#include <test/unit/math/prim/fun/identity_transform_test.cpp>
#include <test/unit/math/prim/fun/if_else_test.cpp>
#include <test/unit/math/prim/fun/inc_beta_dda_test.cpp>
#include <test/unit/math/prim/fun/inc_beta_ddb_test.cpp>
#include <test/unit/math/prim/fun/inc_beta_ddz_test.cpp>
#include <test/unit/math/prim/fun/inc_beta_test.cpp>
#include <test/unit/math/prim/fun/initialize_fill_test.cpp>
#include <test/unit/math/prim/fun/initialize_test.cpp>
#include <test/unit/math/prim/fun/int_step_test.cpp>
