#include <test/unit/math/prim/fun/inv_Phi_test.cpp>
#include <test/unit/math/prim/fun/inv_cloglog_test.cpp>
#include <test/unit/math/prim/fun/inv_erfc_test.cpp>
#include <test/unit/math/prim/fun/inv_inc_beta_test.cpp>
#include <test/unit/math/prim/fun/inv_logit_test.cpp>
#include <test/unit/math/prim/fun/inv_sqrt_test.cpp>
#include <test/unit/math/prim/fun/inv_square_test.cpp>
#include <test/unit/math/prim/fun/inv_test.cpp>
#include <test/unit/math/prim/fun/inverse_softmax_test.cpp>
#include <test/unit/math/prim/fun/inverse_spd_test.cpp>
#include <test/unit/math/prim/fun/inverse_test.cpp>
#include <test/unit/math/prim/fun/is_any_nan_test.cpp>
#include <test/unit/math/prim/fun/is_inf_test.cpp>
#include <test/unit/math/prim/fun/is_nan_test.cpp>
#include <test/unit/math/prim/fun/is_uninitialized_test.cpp>
