#include <test/unit/math/prim/fun/log_test.cpp>
#include <test/unit/math/prim/fun/logical_and_test.cpp>
#include <test/unit/math/prim/fun/logical_eq_test.cpp>
#include <test/unit/math/prim/fun/logical_gt_test.cpp>
#include <test/unit/math/prim/fun/logical_gte_test.cpp>
#include <test/unit/math/prim/fun/logical_lt_test.cpp>
#include <test/unit/math/prim/fun/logical_lte_test.cpp>
#include <test/unit/math/prim/fun/logical_negation_test.cpp>
#include <test/unit/math/prim/fun/logical_neq_test.cpp>
#include <test/unit/math/prim/fun/logical_or_test.cpp>
#include <test/unit/math/prim/fun/logit_test.cpp>
#include <test/unit/math/prim/fun/lub_transform_test.cpp>
#include <test/unit/math/prim/fun/matrix_exp_2x2_test.cpp>
#include <test/unit/math/prim/fun/matrix_exp_action_handler_test.cpp>
#include <test/unit/math/prim/fun/matrix_exp_multiply_test.cpp>
