#include <test/unit/math/prim/fun/log1m_inv_logit_test.cpp>
#include <test/unit/math/prim/fun/log1m_test.cpp>
#include <test/unit/math/prim/fun/log1p_exp_test.cpp>
#include <test/unit/math/prim/fun/log1p_test.cpp>
#include <test/unit/math/prim/fun/log2_test.cpp>
#include <test/unit/math/prim/fun/log_determinant_ldlt_test.cpp>
#include <test/unit/math/prim/fun/log_diff_exp_test.cpp>
#include <test/unit/math/prim/fun/log_falling_factorial_test.cpp>
#include <test/unit/math/prim/fun/log_inv_logit_diff_test.cpp>
#include <test/unit/math/prim/fun/log_inv_logit_test.cpp>
#include <test/unit/math/prim/fun/log_mix_test.cpp>
#include <test/unit/math/prim/fun/log_modified_bessel_first_kind_test.cpp>
#include <test/unit/math/prim/fun/log_rising_factorial_test.cpp>
#include <test/unit/math/prim/fun/log_softmax_test.cpp>
#include <test/unit/math/prim/fun/log_sum_exp_test.cpp>
