#include <test/unit/math/prim/fun/cos_test.cpp>
#include <test/unit/math/prim/fun/cov_exp_quad_test.cpp>
#include <test/unit/math/prim/fun/cov_matrix_transform_test.cpp>
#include <test/unit/math/prim/fun/crossprod_test.cpp>
#include <test/unit/math/prim/fun/csr_extract_u_test.cpp>
#include <test/unit/math/prim/fun/csr_extract_v_test.cpp>
#include <test/unit/math/prim/fun/csr_extract_w_test.cpp>
#include <test/unit/math/prim/fun/csr_matrix_times_vector_test.cpp>
#include <test/unit/math/prim/fun/csr_to_dense_matrix_test.cpp>
#include <test/unit/math/prim/fun/csr_u_to_z_test.cpp>
#include <test/unit/math/prim/fun/cumulative_sum_test.cpp>
#include <test/unit/math/prim/fun/determinant_test.cpp>
#include <test/unit/math/prim/fun/diag_matrix_test.cpp>
#include <test/unit/math/prim/fun/diag_post_multiply_test.cpp>
#include <test/unit/math/prim/fun/diag_pre_multiply_test.cpp>
