#include <test/unit/math/prim/fun/diagonal_test.cpp>
#include <test/unit/math/prim/fun/digamma_test.cpp>
#include <test/unit/math/prim/fun/dims_test.cpp>
#include <test/unit/math/prim/fun/distance_test.cpp>
#include <test/unit/math/prim/fun/divide_columns_test.cpp>
#include <test/unit/math/prim/fun/divide_test.cpp>
#include <test/unit/math/prim/fun/dot_product_test.cpp>
#include <test/unit/math/prim/fun/dot_self_test.cpp>
#include <test/unit/math/prim/fun/dot_test.cpp>
#include <test/unit/math/prim/fun/eigenvalues_sym_test.cpp>
#include <test/unit/math/prim/fun/eigenvectors_sym_test.cpp>
#include <test/unit/math/prim/fun/elt_divide_test.cpp>
#include <test/unit/math/prim/fun/elt_multiply_test.cpp>
#include <test/unit/math/prim/fun/erf_test.cpp>
#include <test/unit/math/prim/fun/erfc_test.cpp>
