#include <test/unit/math/prim/functor/apply_scalar_binary_test.cpp>
#include <test/unit/math/prim/functor/apply_test.cpp>
#include <test/unit/math/prim/functor/coupled_ode_system_test.cpp>
#include <test/unit/math/prim/functor/for_each_test.cpp>
#include <test/unit/math/prim/functor/integrate_1d_impl_test.cpp>
#include <test/unit/math/prim/functor/integrate_1d_test.cpp>
#include <test/unit/math/prim/functor/integrate_ode_std_vector_interface_adapter_test.cpp>
#include <test/unit/math/prim/functor/mpi_cluster_test.cpp>
#include <test/unit/math/prim/functor/mpi_parallel_call_test.cpp>
#include <test/unit/math/prim/functor/ode_store_sensitivities_test.cpp>
#include <test/unit/math/prim/functor/operands_and_partials_test.cpp>
#include <test/unit/math/prim/functor/reduce_sum_test.cpp>
