#include <test/unit/math/prim/meta/is_base_pointer_convertible_test.cpp>
#include <test/unit/math/prim/meta/is_constant_all_test.cpp>
#include <test/unit/math/prim/meta/is_container_test.cpp>
#include <test/unit/math/prim/meta/is_detected_test.cpp>
#include <test/unit/math/prim/meta/is_fvar_test.cpp>
#include <test/unit/math/prim/meta/is_plain_type_test.cpp>
#include <test/unit/math/prim/meta/is_std_vector_test.cpp>
#include <test/unit/math/prim/meta/is_string_convertible_test.cpp>
#include <test/unit/math/prim/meta/is_var_or_arithmetic_test.cpp>
#include <test/unit/math/prim/meta/is_var_test.cpp>
#include <test/unit/math/prim/meta/is_vector_like_test.cpp>
#include <test/unit/math/prim/meta/is_vector_test.cpp>
#include <test/unit/math/prim/meta/partials_return_type_test.cpp>
#include <test/unit/math/prim/meta/partials_type_test.cpp>
#include <test/unit/math/prim/meta/plain_type_test.cpp>
