#include <test/unit/math/prim/prob/poisson_binomial_log_test.cpp>
#include <test/unit/math/prim/prob/poisson_binomial_test.cpp>
#include <test/unit/math/prim/prob/poisson_ccdf_log_test.cpp>
#include <test/unit/math/prim/prob/poisson_cdf_log_test.cpp>
#include <test/unit/math/prim/prob/poisson_log_log_test.cpp>
#include <test/unit/math/prim/prob/poisson_log_test.cpp>
#include <test/unit/math/prim/prob/poisson_test.cpp>
#include <test/unit/math/prim/prob/rayleigh_ccdf_log_test.cpp>
#include <test/unit/math/prim/prob/rayleigh_cdf_log_test.cpp>
#include <test/unit/math/prim/prob/rayleigh_log_test.cpp>
#include <test/unit/math/prim/prob/rayleigh_test.cpp>
#include <test/unit/math/prim/prob/scaled_inv_chi_square_ccdf_log_test.cpp>
#include <test/unit/math/prim/prob/scaled_inv_chi_square_cdf_log_test.cpp>
#include <test/unit/math/prim/prob/scaled_inv_chi_square_log_test.cpp>
#include <test/unit/math/prim/prob/scaled_inv_chi_square_test.cpp>
