#include <test/unit/math/prim/prob/bernoulli_ccdf_log_test.cpp>
#include <test/unit/math/prim/prob/bernoulli_cdf_log_test.cpp>
#include <test/unit/math/prim/prob/bernoulli_log_test.cpp>
#include <test/unit/math/prim/prob/bernoulli_logit_glm_rng_test.cpp>
#include <test/unit/math/prim/prob/bernoulli_logit_log_test.cpp>
#include <test/unit/math/prim/prob/bernoulli_logit_test.cpp>
#include <test/unit/math/prim/prob/bernoulli_test.cpp>
#include <test/unit/math/prim/prob/beta_binomial_ccdf_log_test.cpp>
#include <test/unit/math/prim/prob/beta_binomial_cdf_log_test.cpp>
#include <test/unit/math/prim/prob/beta_binomial_log_test.cpp>
#include <test/unit/math/prim/prob/beta_binomial_test.cpp>
#include <test/unit/math/prim/prob/beta_ccdf_log_test.cpp>
#include <test/unit/math/prim/prob/beta_cdf_log_test.cpp>
#include <test/unit/math/prim/prob/beta_log_test.cpp>
#include <test/unit/math/prim/prob/beta_proportion_ccdf_log_test.cpp>
