#include <test/unit/math/prim/prob/cauchy_ccdf_log_test.cpp>
#include <test/unit/math/prim/prob/cauchy_cdf_log_test.cpp>
#include <test/unit/math/prim/prob/cauchy_log_test.cpp>
#include <test/unit/math/prim/prob/cauchy_test.cpp>
#include <test/unit/math/prim/prob/chi_square_ccdf_log_test.cpp>
#include <test/unit/math/prim/prob/chi_square_cdf_log_test.cpp>
#include <test/unit/math/prim/prob/chi_square_log_test.cpp>
#include <test/unit/math/prim/prob/chi_square_test.cpp>
#include <test/unit/math/prim/prob/dirichlet_log_test.cpp>
#include <test/unit/math/prim/prob/dirichlet_test.cpp>
#include <test/unit/math/prim/prob/discrete_range_ccdf_log_test.cpp>
#include <test/unit/math/prim/prob/discrete_range_cdf_log_test.cpp>
#include <test/unit/math/prim/prob/discrete_range_cdf_test.cpp>
#include <test/unit/math/prim/prob/discrete_range_log_test.cpp>
#include <test/unit/math/prim/prob/discrete_range_test.cpp>
