#include <test/unit/math/prim/prob/double_exponential_ccdf_log_test.cpp>
#include <test/unit/math/prim/prob/double_exponential_cdf_log_test.cpp>
#include <test/unit/math/prim/prob/double_exponential_log_test.cpp>
#include <test/unit/math/prim/prob/double_exponential_test.cpp>
#include <test/unit/math/prim/prob/exp_mod_normal_ccdf_log_test.cpp>
#include <test/unit/math/prim/prob/exp_mod_normal_cdf_log_test.cpp>
#include <test/unit/math/prim/prob/exp_mod_normal_log_test.cpp>
#include <test/unit/math/prim/prob/exp_mod_normal_test.cpp>
#include <test/unit/math/prim/prob/exponential_ccdf_log_test.cpp>
#include <test/unit/math/prim/prob/exponential_cdf_log_test.cpp>
#include <test/unit/math/prim/prob/exponential_log_test.cpp>
#include <test/unit/math/prim/prob/exponential_test.cpp>
#include <test/unit/math/prim/prob/frechet_ccdf_log_test.cpp>
#include <test/unit/math/prim/prob/frechet_cdf_log_test.cpp>
#include <test/unit/math/prim/prob/frechet_log_test.cpp>
