#include <test/unit/math/prim/prob/multinomial_logit_test.cpp>
#include <test/unit/math/prim/prob/multinomial_test.cpp>
#include <test/unit/math/prim/prob/neg_binomial_2_ccdf_log_test.cpp>
#include <test/unit/math/prim/prob/neg_binomial_2_cdf_log_test.cpp>
#include <test/unit/math/prim/prob/neg_binomial_2_log_log_test.cpp>
#include <test/unit/math/prim/prob/neg_binomial_2_log_test.cpp>
#include <test/unit/math/prim/prob/neg_binomial_2_test.cpp>
#include <test/unit/math/prim/prob/neg_binomial_ccdf_log_test.cpp>
#include <test/unit/math/prim/prob/neg_binomial_cdf_log_test.cpp>
#include <test/unit/math/prim/prob/neg_binomial_log_test.cpp>
#include <test/unit/math/prim/prob/neg_binomial_test.cpp>
#include <test/unit/math/prim/prob/normal_ccdf_log_test.cpp>
#include <test/unit/math/prim/prob/normal_cdf_log_test.cpp>
#include <test/unit/math/prim/prob/normal_cdf_test.cpp>
#include <test/unit/math/prim/prob/normal_log_test.cpp>
