#ifndef STAN_MATH_FWD_SCAL_HPP
#define STAN_MATH_FWD_SCAL_HPP

#include <stan/math/fwd/core.hpp>
#include <stan/math/fwd/meta.hpp>

#include <stan/math/prim/scal.hpp>

#include <stan/math/fwd/fun/Phi.hpp>
#include <stan/math/fwd/fun/abs.hpp>
#include <stan/math/fwd/fun/acos.hpp>
#include <stan/math/fwd/fun/acosh.hpp>
#include <stan/math/fwd/fun/asin.hpp>
#include <stan/math/fwd/fun/asinh.hpp>
#include <stan/math/fwd/fun/atan.hpp>
#include <stan/math/fwd/fun/atan2.hpp>
#include <stan/math/fwd/fun/atanh.hpp>
#include <stan/math/fwd/fun/bessel_first_kind.hpp>
#include <stan/math/fwd/fun/bessel_second_kind.hpp>
#include <stan/math/fwd/fun/beta.hpp>
#include <stan/math/fwd/fun/binary_log_loss.hpp>
#include <stan/math/fwd/fun/cbrt.hpp>
#include <stan/math/fwd/fun/ceil.hpp>
#include <stan/math/fwd/fun/cos.hpp>
#include <stan/math/fwd/fun/cosh.hpp>
#include <stan/math/fwd/fun/digamma.hpp>
#include <stan/math/fwd/fun/erf.hpp>
#include <stan/math/fwd/fun/erfc.hpp>
#include <stan/math/fwd/fun/exp.hpp>
#include <stan/math/fwd/fun/exp2.hpp>
#include <stan/math/fwd/fun/expm1.hpp>
#include <stan/math/fwd/fun/fabs.hpp>
#include <stan/math/fwd/fun/falling_factorial.hpp>
#include <stan/math/fwd/fun/fdim.hpp>
#include <stan/math/fwd/fun/floor.hpp>
#include <stan/math/fwd/fun/fma.hpp>
#include <stan/math/fwd/fun/fmax.hpp>
#include <stan/math/fwd/fun/fmin.hpp>
#include <stan/math/fwd/fun/fmod.hpp>
#include <stan/math/fwd/fun/gamma_p.hpp>
#include <stan/math/fwd/fun/gamma_q.hpp>
#include <stan/math/fwd/fun/grad_inc_beta.hpp>
#include <stan/math/fwd/fun/hypot.hpp>
#include <stan/math/fwd/fun/inc_beta.hpp>
#include <stan/math/fwd/fun/inv.hpp>
#include <stan/math/fwd/fun/inv_Phi.hpp>
#include <stan/math/fwd/fun/inv_cloglog.hpp>
#include <stan/math/fwd/fun/inv_logit.hpp>
#include <stan/math/fwd/fun/inv_sqrt.hpp>
#include <stan/math/fwd/fun/inv_square.hpp>
#include <stan/math/fwd/fun/is_inf.hpp>
#include <stan/math/fwd/fun/is_nan.hpp>
#include <stan/math/fwd/fun/lbeta.hpp>
#include <stan/math/fwd/fun/ldexp.hpp>
#include <stan/math/fwd/fun/lgamma.hpp>
#include <stan/math/fwd/fun/lmgamma.hpp>
#include <stan/math/fwd/fun/log.hpp>
#include <stan/math/fwd/fun/log10.hpp>
#include <stan/math/fwd/fun/log1m.hpp>
#include <stan/math/fwd/fun/log1m_exp.hpp>
#include <stan/math/fwd/fun/log1m_inv_logit.hpp>
#include <stan/math/fwd/fun/log1p.hpp>
#include <stan/math/fwd/fun/log1p_exp.hpp>
#include <stan/math/fwd/fun/log2.hpp>
#include <stan/math/fwd/fun/log_diff_exp.hpp>
#include <stan/math/fwd/fun/log_falling_factorial.hpp>
#include <stan/math/fwd/fun/log_inv_logit.hpp>
#include <stan/math/fwd/fun/log_inv_logit_diff.hpp>
#include <stan/math/fwd/fun/log_mix.hpp>
#include <stan/math/fwd/fun/log_rising_factorial.hpp>
#include <stan/math/fwd/fun/log_sum_exp.hpp>
#include <stan/math/fwd/fun/logit.hpp>
#include <stan/math/fwd/fun/modified_bessel_first_kind.hpp>
#include <stan/math/fwd/fun/modified_bessel_second_kind.hpp>
#include <stan/math/fwd/fun/multiply_log.hpp>
#include <stan/math/fwd/fun/owens_t.hpp>
#include <stan/math/fwd/fun/Phi_approx.hpp>
#include <stan/math/fwd/fun/pow.hpp>
#include <stan/math/fwd/fun/primitive_value.hpp>
#include <stan/math/fwd/fun/rising_factorial.hpp>
#include <stan/math/fwd/fun/round.hpp>
#include <stan/math/fwd/fun/sin.hpp>
#include <stan/math/fwd/fun/sinh.hpp>
#include <stan/math/fwd/fun/sqrt.hpp>
#include <stan/math/fwd/fun/square.hpp>
#include <stan/math/fwd/fun/tan.hpp>
#include <stan/math/fwd/fun/tanh.hpp>
#include <stan/math/fwd/fun/tgamma.hpp>
#include <stan/math/fwd/fun/to_fvar.hpp>
#include <stan/math/fwd/fun/trigamma.hpp>
#include <stan/math/fwd/fun/trunc.hpp>
#include <stan/math/fwd/fun/value_of.hpp>
#include <stan/math/fwd/fun/value_of_rec.hpp>

#endif
