#include <test/prob/bernoulli/bernoulli_00000_generated_fd_test.cpp>
#include <test/prob/bernoulli/bernoulli_00000_generated_ffd_test.cpp>
#include <test/prob/bernoulli/bernoulli_00000_generated_ffv_test.cpp>
#include <test/prob/bernoulli/bernoulli_00000_generated_fv_test.cpp>
#include <test/prob/bernoulli/bernoulli_00000_generated_v_test.cpp>
#include <test/prob/bernoulli/bernoulli_ccdf_log_00000_generated_fd_test.cpp>
#include <test/prob/bernoulli/bernoulli_ccdf_log_00000_generated_ffd_test.cpp>
#include <test/prob/bernoulli/bernoulli_ccdf_log_00000_generated_ffv_test.cpp>
#include <test/prob/bernoulli/bernoulli_ccdf_log_00000_generated_fv_test.cpp>
#include <test/prob/bernoulli/bernoulli_ccdf_log_00000_generated_v_test.cpp>
#include <test/prob/bernoulli/bernoulli_cdf_00000_generated_fd_test.cpp>
#include <test/prob/bernoulli/bernoulli_cdf_00000_generated_ffd_test.cpp>
#include <test/prob/bernoulli/bernoulli_cdf_00000_generated_ffv_test.cpp>
#include <test/prob/bernoulli/bernoulli_cdf_00000_generated_fv_test.cpp>
#include <test/prob/bernoulli/bernoulli_cdf_00000_generated_v_test.cpp>
#include <test/prob/bernoulli/bernoulli_cdf_log_00000_generated_fd_test.cpp>
#include <test/prob/bernoulli/bernoulli_cdf_log_00000_generated_ffd_test.cpp>
#include <test/prob/bernoulli/bernoulli_cdf_log_00000_generated_ffv_test.cpp>
#include <test/prob/bernoulli/bernoulli_cdf_log_00000_generated_fv_test.cpp>
#include <test/prob/bernoulli/bernoulli_cdf_log_00000_generated_v_test.cpp>
#include <test/prob/bernoulli/bernoulli_logit_00000_generated_fd_test.cpp>
#include <test/prob/bernoulli/bernoulli_logit_00000_generated_ffd_test.cpp>
#include <test/prob/bernoulli/bernoulli_logit_00000_generated_ffv_test.cpp>
#include <test/prob/bernoulli/bernoulli_logit_00000_generated_fv_test.cpp>
#include <test/prob/bernoulli/bernoulli_logit_00000_generated_v_test.cpp>
