#include <stan/math/mix.hpp>
#include <stan/math/rev.hpp>
#include <test/prob/test_fixture_ccdf_log.hpp>
#include <test/prob/test_fixture_cdf_log.hpp>
#include <test/prob/test_fixture_cdf.hpp>
#include <test/prob/test_fixture_distr.hpp>
#include <test/prob/utility.hpp>
#include <gtest/gtest.h>
#include <stdexcept>
#include <tuple>
#include <type_traits>
#include <test/prob/args/arg_generated_v_int_real_pch.hpp>
#include <test/prob/args/arg_generated_ffv_int_real_pch.hpp>
#include <test/prob/args/arg_generated_vv_int_real_pch.hpp>
#include <test/prob/args/arg_generated_v_real_real_real_pch.hpp>
#include <test/prob/args/arg_generated_ffv_real_real_real_pch.hpp>
#include <test/prob/args/arg_generated_vv_real_real_real_pch.hpp>
#include <test/prob/args/arg_generated_v_int_int_real_real_pch.hpp>
#include <test/prob/args/arg_generated_ffv_int_int_real_real_pch.hpp>
#include <test/prob/args/arg_generated_vv_int_int_real_real_pch.hpp>
#include <test/prob/args/arg_generated_v_int_int_real_pch.hpp>
#include <test/prob/args/arg_generated_ffv_int_int_real_pch.hpp>
#include <test/prob/args/arg_generated_vv_int_int_real_pch.hpp>
#include <test/prob/args/arg_generated_v_real_real_pch.hpp>
#include <test/prob/args/arg_generated_ffv_real_real_pch.hpp>
#include <test/prob/args/arg_generated_vv_real_real_pch.hpp>
#include <test/prob/args/arg_generated_v_int_int_int_pch.hpp>
#include <test/prob/args/arg_generated_ffv_int_int_int_pch.hpp>
#include <test/prob/args/arg_generated_vv_int_int_int_pch.hpp>
#include <test/prob/args/arg_generated_v_real_real_real_real_pch.hpp>
#include <test/prob/args/arg_generated_ffv_real_real_real_real_pch.hpp>
#include <test/prob/args/arg_generated_vv_real_real_real_real_pch.hpp>
#include <test/prob/args/arg_generated_v_int_int_int_int_pch.hpp>
#include <test/prob/args/arg_generated_ffv_int_int_int_int_pch.hpp>
#include <test/prob/args/arg_generated_vv_int_int_int_int_pch.hpp>
#include <test/prob/args/arg_generated_v_int_real_real_pch.hpp>
#include <test/prob/args/arg_generated_ffv_int_real_real_pch.hpp>
#include <test/prob/args/arg_generated_vv_int_real_real_pch.hpp>
#include <test/prob/args/arg_generated_v_real_real_int_real_real_pch.hpp>
#include <test/prob/args/arg_generated_ffv_real_real_int_real_real_pch.hpp>
#include <test/prob/args/arg_generated_vv_real_real_int_real_real_pch.hpp>
#include <test/prob/args/arg_generated_v_real_pch.hpp>
#include <test/prob/args/arg_generated_ffv_real_pch.hpp>
#include <test/prob/args/arg_generated_vv_real_pch.hpp>
#include <test/prob/args/arg_generated_v_real_real_real_real_real_pch.hpp>
#include <test/prob/args/arg_generated_ffv_real_real_real_real_real_pch.hpp>
#include <test/prob/args/arg_generated_vv_real_real_real_real_real_pch.hpp>

