#include <test/prob/pareto_type_2/pareto_type_2_00006_generated_fd_test.cpp>
#include <test/prob/pareto_type_2/pareto_type_2_00006_generated_ffd_test.cpp>
#include <test/prob/pareto_type_2/pareto_type_2_00006_generated_ffv_test.cpp>
#include <test/prob/pareto_type_2/pareto_type_2_00006_generated_fv_test.cpp>
#include <test/prob/pareto_type_2/pareto_type_2_00006_generated_v_test.cpp>
#include <test/prob/pareto_type_2/pareto_type_2_00007_generated_fd_test.cpp>
#include <test/prob/pareto_type_2/pareto_type_2_00007_generated_ffd_test.cpp>
#include <test/prob/pareto_type_2/pareto_type_2_00007_generated_ffv_test.cpp>
#include <test/prob/pareto_type_2/pareto_type_2_00007_generated_fv_test.cpp>
#include <test/prob/pareto_type_2/pareto_type_2_00007_generated_v_test.cpp>
#include <test/prob/pareto_type_2/pareto_type_2_00008_generated_fd_test.cpp>
#include <test/prob/pareto_type_2/pareto_type_2_00008_generated_ffd_test.cpp>
#include <test/prob/pareto_type_2/pareto_type_2_00008_generated_ffv_test.cpp>
#include <test/prob/pareto_type_2/pareto_type_2_00008_generated_fv_test.cpp>
#include <test/prob/pareto_type_2/pareto_type_2_00008_generated_v_test.cpp>
#include <test/prob/pareto_type_2/pareto_type_2_00009_generated_fd_test.cpp>
#include <test/prob/pareto_type_2/pareto_type_2_00009_generated_ffd_test.cpp>
#include <test/prob/pareto_type_2/pareto_type_2_00009_generated_ffv_test.cpp>
#include <test/prob/pareto_type_2/pareto_type_2_00009_generated_fv_test.cpp>
#include <test/prob/pareto_type_2/pareto_type_2_00009_generated_v_test.cpp>
#include <test/prob/pareto_type_2/pareto_type_2_00010_generated_fd_test.cpp>
#include <test/prob/pareto_type_2/pareto_type_2_00010_generated_ffd_test.cpp>
#include <test/prob/pareto_type_2/pareto_type_2_00010_generated_ffv_test.cpp>
#include <test/prob/pareto_type_2/pareto_type_2_00010_generated_fv_test.cpp>
#include <test/prob/pareto_type_2/pareto_type_2_00010_generated_v_test.cpp>
#include <test/prob/pareto_type_2/pareto_type_2_00011_generated_fd_test.cpp>
#include <test/prob/pareto_type_2/pareto_type_2_00011_generated_ffd_test.cpp>
#include <test/prob/pareto_type_2/pareto_type_2_00011_generated_ffv_test.cpp>
#include <test/prob/pareto_type_2/pareto_type_2_00011_generated_fv_test.cpp>
#include <test/prob/pareto_type_2/pareto_type_2_00011_generated_v_test.cpp>
