#include <test/prob/student_t/student_t_00000_generated_fd_test.cpp>
#include <test/prob/student_t/student_t_00000_generated_ffd_test.cpp>
#include <test/prob/student_t/student_t_00000_generated_ffv_test.cpp>
#include <test/prob/student_t/student_t_00000_generated_fv_test.cpp>
#include <test/prob/student_t/student_t_00000_generated_v_test.cpp>
#include <test/prob/student_t/student_t_00001_generated_fd_test.cpp>
#include <test/prob/student_t/student_t_00001_generated_ffd_test.cpp>
#include <test/prob/student_t/student_t_00001_generated_ffv_test.cpp>
#include <test/prob/student_t/student_t_00001_generated_fv_test.cpp>
#include <test/prob/student_t/student_t_00001_generated_v_test.cpp>
#include <test/prob/student_t/student_t_00002_generated_fd_test.cpp>
#include <test/prob/student_t/student_t_00002_generated_ffd_test.cpp>
#include <test/prob/student_t/student_t_00002_generated_ffv_test.cpp>
#include <test/prob/student_t/student_t_00002_generated_fv_test.cpp>
#include <test/prob/student_t/student_t_00002_generated_v_test.cpp>
#include <test/prob/student_t/student_t_00003_generated_fd_test.cpp>
#include <test/prob/student_t/student_t_00003_generated_ffd_test.cpp>
#include <test/prob/student_t/student_t_00003_generated_ffv_test.cpp>
#include <test/prob/student_t/student_t_00003_generated_fv_test.cpp>
#include <test/prob/student_t/student_t_00003_generated_v_test.cpp>
#include <test/prob/student_t/student_t_00004_generated_fd_test.cpp>
#include <test/prob/student_t/student_t_00004_generated_ffd_test.cpp>
#include <test/prob/student_t/student_t_00004_generated_ffv_test.cpp>
#include <test/prob/student_t/student_t_00004_generated_fv_test.cpp>
#include <test/prob/student_t/student_t_00004_generated_v_test.cpp>
#include <test/prob/student_t/student_t_00005_generated_fd_test.cpp>
#include <test/prob/student_t/student_t_00005_generated_ffd_test.cpp>
#include <test/prob/student_t/student_t_00005_generated_ffv_test.cpp>
#include <test/prob/student_t/student_t_00005_generated_fv_test.cpp>
#include <test/prob/student_t/student_t_00005_generated_v_test.cpp>
