name: Windows Rtools44

on:
  pull_request:
    branches: [ develop, master ]
  push:
    branches: [ develop ]
    paths-ignore:
      - 'doygen/**'
      - 'hooks/**'
      - 'licenses/**'
      - 'LICENSE.md'
      - 'README.md'
      - 'RELEASE-NOTES.txt'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  prim-rev:
    name: prim and rev tests
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - uses: r-lib/actions/setup-r@v2
      with:
        r-version: 'release'
        rtools-version: '44'

    - name: Set path for Rtools44
      if: runner.os == 'Windows'
      run: echo "C:/rtools44/usr/bin;C:/rtools44/x86_64-w64-mingw32.static.posix/bin" | Out-File -Append -FilePath $env:GITHUB_PATH -Encoding utf8

    - name: Build Math libs
      shell: powershell
      run: |
        make -f make/standalone math-libs -j2
    - name: Add TBB to PATH
      shell: powershell
      run: echo "D:/a/math/math/lib/tbb" | Out-File -Append -FilePath $env:GITHUB_PATH -Encoding utf8
    - name: Run prim and rev unit tests
      shell: powershell
      run: |
        cmake -S . -B build -DCMAKE_BUILD_TYPE=RELEASE
        cd build
        make -j2 unit_math_prim_subtests
        ./test/unit/test_unit_math_prim_core
        ./test/unit/test_unit_math_prim_err
        ./test/unit/test_unit_math_prim_fun
        ./test/unit/test_unit_math_prim_functor
        ./test/unit/test_unit_math_prim_meta
        ./test/unit/test_unit_math_prim_prob
        make -j2 unit_math_rev_subtests
        ./test/unit/test_unit_math_rev_core
        ./test/unit/test_unit_math_rev_err
        ./test/unit/test_unit_math_rev_fun
        ./test/unit/test_unit_math_rev_functor
        ./test/unit/test_unit_math_rev_meta
        ./test/unit/test_unit_math_rev_prob
        make -j2 test_unit_math_memory
        ./test/unit/math/memory/test_unit_math_memory

    - name: Upload gtest_output xml
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: gtest_outputs_xml
        path: '**/*_test.xml'

  fwd-non-fun-mix:
    name: fwd tests and non-fun mix tests
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - uses: r-lib/actions/setup-r@v2
      with:
        r-version: 'release'
        rtools-version: '44'

    - name: Set path for Rtools44
      if: runner.os == 'Windows'
      run: echo "C:/rtools44/usr/bin;C:/rtools44/x86_64-w64-mingw32.static.posix/bin" | Out-File -Append -FilePath $env:GITHUB_PATH -Encoding utf8

    - name: Build Math libs
      shell: powershell
      run: |
        make -f make/standalone math-libs -j2
    - name: Add TBB to PATH
      shell: powershell
      run: echo "D:/a/math/math/lib/tbb" | Out-File -Append -FilePath $env:GITHUB_PATH -Encoding utf8
    - name: Disable running fwd/mix tests
      shell: powershell
      run: echo "CXXFLAGS+= -DSTAN_MATH_TESTS_REV_ONLY" | Out-File -Append -FilePath make/local -Encoding utf8
    - name: Run fwd unit tests and all the mix tests except those in mix/fun
      shell: powershell
      run: |
        cmake -S . -B build -DCMAKE_BUILD_TYPE=RELEASE
        cd build
        make -j2 unit_math_fwd_subtests
        ./test/unit/test_unit_math_fwd_core
        ./test/unit/test_unit_math_fwd_fun
        ./test/unit/test_unit_math_fwd_functor
        ./test/unit/test_unit_math_fwd_meta
        ./test/unit/test_unit_math_fwd_prob
        make -j2 unit_math_mix_subtests
        ./test/unit/test_unit_math_mix_core
        ./test/unit/test_unit_math_mix_functor
        ./test/unit/test_unit_math_mix_meta
        ./test/unit/test_unit_math_mix_prob
    - name: Upload gtest_output xml
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: gtest_outputs_xml
        path: '**/*_test.xml'

  mix-fun-1:
    name: mix/fun tests 1
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - uses: r-lib/actions/setup-r@v2
      with:
        r-version: 'release'
        rtools-version: '44'

    - name: Set path for Rtools44
      if: runner.os == 'Windows'
      run: echo "C:/rtools44/usr/bin;C:/rtools44/x86_64-w64-mingw32.static.posix/bin" | Out-File -Append -FilePath $env:GITHUB_PATH -Encoding utf8

    - name: Build Math libs
      shell: powershell
      run: |
        make -f make/standalone math-libs -j2
    - name: Add TBB to PATH
      shell: powershell
      run: echo "D:/a/math/math/lib/tbb" | Out-File -Append -FilePath $env:GITHUB_PATH -Encoding utf8
    - name: Run mix/fun unit tests
      shell: powershell
      run: |
        cmake -S . -B build -DCMAKE_BUILD_TYPE=RELEASE
        cd build
        make -j2 test_unit_math_mix_fun
        ./test/unit/test_unit_math_mix_fun

    - name: Upload gtest_output xml
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: gtest_outputs_xml
        path: '**/*_test.xml'

    - name: Upload gtest_output xml
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: gtest_outputs_xml
        path: '**/*_test.xml'
