name: Windows Rtools44

on:
  pull_request:
    branches: [ develop, master ]
  push:
    branches: [ develop, arm-ci ]
    paths-ignore:
      - 'doygen/**'
      - 'hooks/**'
      - 'licenses/**'
      - 'LICENSE.md'
      - 'README.md'
      - 'RELEASE-NOTES.txt'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  mix-fun-1:
    name: mix/fun tests 1
    runs-on: ubuntu-24.04-arm

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Suppress warnings
      run: |
        echo "CPPFLAGS += -Wno-psabi -Wno-deprecated-declarations" >> make/local
        echo "STAN_THREADS=true" >> make/local

    - name: Build Math libs
      run: |
        make -f make/standalone math-libs -j2

    - name: Run mix/fun unit tests
      run: |
        python runTests.py -j4 --jumbo --run-all test/unit/math/fwd
        python runTests.py -j4 --jumbo --run-all test/unit/math/prim
        python runTests.py -j4 --jumbo --run-all test/unit/math/rev
        python runTests.py -j2 --run-all test/unit/math/mix

    - name: Upload gtest_output xml
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: gtest_outputs_xml
        path: '**/*_test.xml'
