name: Math - Windows with RTools 3.5

on:
  push:
    branches: [ develop ]
    paths-ignore:
      - 'doygen/**'
      - 'hooks/**'
      - 'licenses/**'
      - 'LICENSE.md'
      - 'README.md'
      - 'RELEASE-NOTES.txt'
  pull_request:
    branches: [ develop ]
    paths-ignore:
      - 'doygen/**'
      - 'hooks/**'
      - 'licenses/**'
      - 'LICENSE.md'
      - 'README.md'
      - 'RELEASE-NOTES.txt'
jobs:
  prim:
    name: prim tests
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '2.x'
    - name: Download RTools
      run: Invoke-WebRequest -Uri https://cran.rstudio.com/bin/windows/Rtools/Rtools35.exe -OutFile ./R35.exe
    - name: Install RTools
      shell: powershell
      run: Start-Process -FilePath ./R35.exe -ArgumentList /VERYSILENT -NoNewWindow -Wait
    - name: PATH Setup
      shell: powershell
      run: echo "::add-path::C:/Rtools/bin"
    - name: PATH Setup
      shell: powershell
      run: echo "::add-path::C:/Rtools/mingw_64/bin"
    - name: Check g++ version
      shell: powershell
      run: g++ --version
    - name: Check g++ path
      shell: powershell
      run: Get-Command gcc | Select-Object -ExpandProperty Definition
    - name: Check mingw32-make version
      shell: powershell
      run: mingw32-make --version
    - name: Check mingw32-make path
      shell: powershell
      run: Get-Command mingw32-make | Select-Object -ExpandProperty Definition
    - name: Build libs
      shell: powershell
      run: mingw32-make -f make/standalone math-libs
    - name: PATH Setup
      shell: powershell
      run: echo "::add-path::D:/a/math/math/lib/tbb"
    - name: Run tests
      shell: powershell
      run: python.exe runTests.py -j2 test/unit -f test/unit/math/prim/
  rev:
    name: rev tests
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '2.x'
    - name: Download RTools
      run: Invoke-WebRequest -Uri https://cran.rstudio.com/bin/windows/Rtools/Rtools35.exe -OutFile ./R35.exe
    - name: Install RTools
      shell: powershell
      run: Start-Process -FilePath ./R35.exe -ArgumentList /VERYSILENT -NoNewWindow -Wait
    - name: PATH Setup
      shell: powershell
      run: echo "::add-path::C:/Rtools/bin"
    - name: PATH Setup
      shell: powershell
      run: echo "::add-path::C:/Rtools/mingw_64/bin"
    - name: Check g++ version
      shell: powershell
      run: g++ --version
    - name: Check g++ path
      shell: powershell
      run: Get-Command gcc | Select-Object -ExpandProperty Definition
    - name: Check mingw32-make version
      shell: powershell
      run: mingw32-make --version
    - name: Check mingw32-make path
      shell: powershell
      run: Get-Command mingw32-make | Select-Object -ExpandProperty Definition
    - name: Build libs
      shell: powershell
      run: mingw32-make -f make/standalone math-libs
    - name: PATH Setup
      shell: powershell
      run: echo "::add-path::D:/a/math/math/lib/tbb"
    - name: Run tests
      shell: powershell
      run: python.exe runTests.py -j2 test/unit -f test/unit/math/rev/
  fwd:
    name: fwd tests
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '2.x'
    - name: Download RTools
      run: Invoke-WebRequest -Uri https://cran.rstudio.com/bin/windows/Rtools/Rtools35.exe -OutFile ./R35.exe
    - name: Install RTools
      shell: powershell
      run: Start-Process -FilePath ./R35.exe -ArgumentList /VERYSILENT -NoNewWindow -Wait
    - name: PATH Setup
      shell: powershell
      run: echo "::add-path::C:/Rtools/bin"
    - name: PATH Setup
      shell: powershell
      run: echo "::add-path::C:/Rtools/mingw_64/bin"
    - name: Check g++ version
      shell: powershell
      run: g++ --version
    - name: Check g++ path
      shell: powershell
      run: Get-Command gcc | Select-Object -ExpandProperty Definition
    - name: Check mingw32-make version
      shell: powershell
      run: mingw32-make --version
    - name: Check mingw32-make path
      shell: powershell
      run: Get-Command mingw32-make | Select-Object -ExpandProperty Definition
      run: mingw32-make -f make/standalone math-libs
    - name: PATH Setup
      shell: powershell
      run: echo "::add-path::D:/a/math/math/lib/tbb"
    - name: Run tests
      shell: powershell
      run: python.exe runTests.py -j2 test/unit -f test/unit/math/fwd/
  mix:
    name: mix tests
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '2.x'
    - name: Download RTools
      run: Invoke-WebRequest -Uri https://cran.rstudio.com/bin/windows/Rtools/Rtools35.exe -OutFile ./R35.exe
    - name: Install RTools
      shell: powershell
      run: Start-Process -FilePath ./R35.exe -ArgumentList /VERYSILENT -NoNewWindow -Wait
    - name: PATH Setup
      shell: powershell
      run: echo "::add-path::C:/Rtools/bin"
    - name: PATH Setup
      shell: powershell
      run: echo "::add-path::C:/Rtools/mingw_64/bin"
    - name: Check g++ version
      shell: powershell
      run: g++ --version
    - name: Check g++ path
      shell: powershell
      run: Get-Command gcc | Select-Object -ExpandProperty Definition
    - name: Check mingw32-make version
      shell: powershell
      run: mingw32-make --version
    - name: Check mingw32-make path
      shell: powershell
      run: Get-Command mingw32-make | Select-Object -ExpandProperty Definition
    - name: Build libs
      shell: powershell
      run: mingw32-make -f make/standalone math-libs
    - name: PATH Setup
      shell: powershell
      run: echo "::add-path::D:/a/math/math/lib/tbb"
    - name: Run tests
      shell: powershell
      run: python.exe runTests.py -j2 test/unit -f test/unit/math/mix/

