name: Windows RTools 3.5

on:
  push:
    branches: [ develop ]
    paths-ignore:
      - 'doygen/**'
      - 'hooks/**'
      - 'licenses/**'
      - 'LICENSE.md'
      - 'README.md'
      - 'RELEASE-NOTES.txt'
jobs:
  prim-rev:
    name: prim and rev unit tests
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '2.x'
    - name: Download RTools
      run: Invoke-WebRequest -Uri https://cran.rstudio.com/bin/windows/Rtools/Rtools35.exe -OutFile ./R35.exe
    - name: Install RTools
      shell: powershell
      run: Start-Process -FilePath ./R35.exe -ArgumentList /VERYSILENT -NoNewWindow -Wait
    - name: PATH Setup
      shell: powershell
      run: echo "C:/Rtools/bin;C:/Rtools/mingw_64/bin" | Out-File -Append -FilePath $env:GITHUB_PATH -Encoding utf8
    - name: Print g++ & make version and path
      shell: powershell
      run: |
        g++ --version
        Get-Command g++ | Select-Object -ExpandProperty Definition
        mingw32-make --version
        Get-Command mingw32-make | Select-Object -ExpandProperty Definition
    - name: Build Math libs
      shell: powershell
      run: mingw32-make -f make/standalone math-libs
    - name: Add TBB to PATH
      shell: powershell
      run: echo "D:/a/math/math/lib/tbb" | Out-File -Append -FilePath $env:GITHUB_PATH -Encoding utf8
    - name: Run prim and rev unit tests
      shell: powershell
      run: 
        python.exe runTests.py -j2 test/unit/*_test.cpp
        python.exe runTests.py -j2 test/unit/math/*_test.cpp
        python.exe runTests.py -j2 test/unit/prim
        python.exe runTests.py -j2 test/unit/rev
        python.exe runTests.py -j2 test/unit/memory
        
    - name: Upload gtest_output xml
      uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: gtest_outputs_xml
        path: '**/*_test.xml'
  fwd-mix:
    name: fwd and mix unit tests
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '2.x'
    - name: Download RTools
      run: Invoke-WebRequest -Uri https://cran.rstudio.com/bin/windows/Rtools/Rtools35.exe -OutFile ./R35.exe
    - name: Install RTools
      shell: powershell
      run: Start-Process -FilePath ./R35.exe -ArgumentList /VERYSILENT -NoNewWindow -Wait
    - name: PATH Setup
      shell: powershell
      run: echo "C:/Rtools/bin;C:/Rtools/mingw_64/bin" | Out-File -Append -FilePath $env:GITHUB_PATH -Encoding utf8
    - name: Print g++ & make version and path
      shell: powershell
      run: |
        g++ --version
        Get-Command g++ | Select-Object -ExpandProperty Definition
        mingw32-make --version
        Get-Command mingw32-make | Select-Object -ExpandProperty Definition
    - name: Build Math libs
      shell: powershell
      run: mingw32-make -f make/standalone math-libs
    - name: Add TBB to PATH
      shell: powershell
      run: echo "D:/a/math/math/lib/tbb" | Out-File -Append -FilePath $env:GITHUB_PATH -Encoding utf8
    - name: Run prim and rev unit tests
      shell: powershell
      run: 
        python.exe runTests.py -j2 test/unit/fwd
        python.exe runTests.py -j2 test/unit/mix
        
    - name: Upload gtest_output xml
      uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: gtest_outputs_xml
        path: '**/*_test.xml'