#ifndef STAN_MATH_PRIM_MAT_HPP
#define STAN_MATH_PRIM_MAT_HPP

#include <stan/math/prim/fun/Eigen.hpp>

#include <stan/math/prim/core.hpp>
#include <stan/math/prim/meta.hpp>

#include <stan/math/prim/err/check_cholesky_factor.hpp>
#include <stan/math/prim/err/check_cholesky_factor_corr.hpp>
#include <stan/math/prim/err/check_column_index.hpp>
#include <stan/math/prim/err/check_consistent_size_mvt.hpp>
#include <stan/math/prim/err/check_consistent_sizes_mvt.hpp>
#include <stan/math/prim/err/check_corr_matrix.hpp>
#include <stan/math/prim/err/check_cov_matrix.hpp>
#include <stan/math/prim/err/check_finite.hpp>
#include <stan/math/prim/err/check_ldlt_factor.hpp>
#include <stan/math/prim/err/check_lower_triangular.hpp>
#include <stan/math/prim/err/check_matching_dims.hpp>
#include <stan/math/prim/err/check_multiplicable.hpp>
#include <stan/math/prim/err/check_nonempty.hpp>
#include <stan/math/prim/err/check_ordered.hpp>
#include <stan/math/prim/err/check_pos_definite.hpp>
#include <stan/math/prim/err/check_pos_semidefinite.hpp>
#include <stan/math/prim/err/check_positive_ordered.hpp>
#include <stan/math/prim/err/check_range.hpp>
#include <stan/math/prim/err/check_row_index.hpp>
#include <stan/math/prim/err/check_simplex.hpp>
#include <stan/math/prim/err/check_square.hpp>
#include <stan/math/prim/err/check_std_vector_index.hpp>
#include <stan/math/prim/err/check_symmetric.hpp>
#include <stan/math/prim/err/check_unit_vector.hpp>
#include <stan/math/prim/err/check_vector.hpp>
#include <stan/math/prim/err/constraint_tolerance.hpp>
#include <stan/math/prim/err/is_cholesky_factor_corr.hpp>
#include <stan/math/prim/err/is_cholesky_factor.hpp>
#include <stan/math/prim/err/is_column_index.hpp>
#include <stan/math/prim/err/is_corr_matrix.hpp>
#include <stan/math/prim/err/is_ldlt_factor.hpp>
#include <stan/math/prim/err/is_lower_triangular.hpp>
#include <stan/math/prim/err/is_mat_finite.hpp>
#include <stan/math/prim/err/is_matching_dims.hpp>
#include <stan/math/prim/err/is_pos_definite.hpp>
#include <stan/math/prim/err/is_square.hpp>
#include <stan/math/prim/err/is_symmetric.hpp>
#include <stan/math/prim/err/is_unit_vector.hpp>
#include <stan/math/prim/err/validate_non_negative_index.hpp>

#include <stan/math/prim/fun/LDLT_factor.hpp>
#include <stan/math/prim/fun/Phi.hpp>
#include <stan/math/prim/fun/Phi_approx.hpp>
#include <stan/math/prim/fun/accumulator.hpp>
#include <stan/math/prim/fun/acos.hpp>
#include <stan/math/prim/fun/acosh.hpp>
#include <stan/math/prim/fun/add.hpp>
#include <stan/math/prim/fun/add_diag.hpp>
#include <stan/math/prim/fun/append_array.hpp>
#include <stan/math/prim/fun/append_col.hpp>
#include <stan/math/prim/fun/append_row.hpp>
#include <stan/math/prim/fun/asin.hpp>
#include <stan/math/prim/fun/asinh.hpp>
#include <stan/math/prim/fun/assign.hpp>
#include <stan/math/prim/fun/atan.hpp>
#include <stan/math/prim/fun/atanh.hpp>
#include <stan/math/prim/fun/autocorrelation.hpp>
#include <stan/math/prim/fun/autocovariance.hpp>
#include <stan/math/prim/fun/block.hpp>
#include <stan/math/prim/fun/cbrt.hpp>
#include <stan/math/prim/fun/ceil.hpp>
#include <stan/math/prim/fun/chol2inv.hpp>
#include <stan/math/prim/fun/cholesky_corr_constrain.hpp>
#include <stan/math/prim/fun/cholesky_corr_free.hpp>
#include <stan/math/prim/fun/cholesky_decompose.hpp>
#include <stan/math/prim/fun/cholesky_factor_constrain.hpp>
#include <stan/math/prim/fun/cholesky_factor_free.hpp>
#include <stan/math/prim/fun/col.hpp>
#include <stan/math/prim/fun/cols.hpp>
#include <stan/math/prim/fun/columns_dot_product.hpp>
#include <stan/math/prim/fun/columns_dot_self.hpp>
#include <stan/math/prim/fun/common_type.hpp>
#include <stan/math/prim/fun/corr_matrix_constrain.hpp>
#include <stan/math/prim/fun/corr_matrix_free.hpp>
#include <stan/math/prim/fun/cos.hpp>
#include <stan/math/prim/fun/cosh.hpp>
#include <stan/math/prim/fun/cov_exp_quad.hpp>
#include <stan/math/prim/fun/cov_matrix_constrain.hpp>
#include <stan/math/prim/fun/cov_matrix_constrain_lkj.hpp>
#include <stan/math/prim/fun/cov_matrix_free.hpp>
#include <stan/math/prim/fun/cov_matrix_free_lkj.hpp>
#include <stan/math/prim/fun/crossprod.hpp>
#include <stan/math/prim/fun/csr_extract_u.hpp>
#include <stan/math/prim/fun/csr_extract_v.hpp>
#include <stan/math/prim/fun/csr_extract_w.hpp>
#include <stan/math/prim/fun/csr_matrix_times_vector.hpp>
#include <stan/math/prim/fun/csr_to_dense_matrix.hpp>
#include <stan/math/prim/fun/csr_u_to_z.hpp>
#include <stan/math/prim/fun/cumulative_sum.hpp>
#include <stan/math/prim/fun/determinant.hpp>
#include <stan/math/prim/fun/diag_matrix.hpp>
#include <stan/math/prim/fun/diag_post_multiply.hpp>
#include <stan/math/prim/fun/diag_pre_multiply.hpp>
#include <stan/math/prim/fun/diagonal.hpp>
#include <stan/math/prim/fun/digamma.hpp>
#include <stan/math/prim/fun/dims.hpp>
#include <stan/math/prim/fun/distance.hpp>
#include <stan/math/prim/fun/divide.hpp>
#include <stan/math/prim/fun/dot_product.hpp>
#include <stan/math/prim/fun/dot_self.hpp>
#include <stan/math/prim/fun/eigenvalues_sym.hpp>
#include <stan/math/prim/fun/eigenvectors_sym.hpp>
#include <stan/math/prim/fun/elt_divide.hpp>
#include <stan/math/prim/fun/elt_multiply.hpp>
#include <stan/math/prim/fun/erf.hpp>
#include <stan/math/prim/fun/erfc.hpp>
#include <stan/math/prim/fun/exp.hpp>
#include <stan/math/prim/fun/exp2.hpp>
#include <stan/math/prim/fun/expm1.hpp>
#include <stan/math/prim/fun/fabs.hpp>
#include <stan/math/prim/fun/factor_U.hpp>
#include <stan/math/prim/fun/factor_cov_matrix.hpp>
#include <stan/math/prim/fun/fill.hpp>
#include <stan/math/prim/fun/floor.hpp>
#include <stan/math/prim/fun/get_base1.hpp>
#include <stan/math/prim/fun/get_base1_lhs.hpp>
#include <stan/math/prim/fun/get_lp.hpp>
#include <stan/math/prim/fun/gp_dot_prod_cov.hpp>
#include <stan/math/prim/fun/gp_exponential_cov.hpp>
#include <stan/math/prim/fun/gp_matern32_cov.hpp>
#include <stan/math/prim/fun/gp_matern52_cov.hpp>
#include <stan/math/prim/fun/gp_periodic_cov.hpp>
#include <stan/math/prim/fun/head.hpp>
#include <stan/math/prim/fun/initialize.hpp>
#include <stan/math/prim/fun/inv.hpp>
#include <stan/math/prim/fun/inv_Phi.hpp>
#include <stan/math/prim/fun/inv_cloglog.hpp>
#include <stan/math/prim/fun/inv_logit.hpp>
#include <stan/math/prim/fun/inv_sqrt.hpp>
#include <stan/math/prim/fun/inv_square.hpp>
#include <stan/math/prim/fun/inverse.hpp>
#include <stan/math/prim/fun/inverse_spd.hpp>
#include <stan/math/prim/fun/lgamma.hpp>
#include <stan/math/prim/fun/log.hpp>
#include <stan/math/prim/fun/log10.hpp>
#include <stan/math/prim/fun/log1m.hpp>
#include <stan/math/prim/fun/log1m_exp.hpp>
#include <stan/math/prim/fun/log1m_inv_logit.hpp>
#include <stan/math/prim/fun/log1p.hpp>
#include <stan/math/prim/fun/log1p_exp.hpp>
#include <stan/math/prim/fun/log2.hpp>
#include <stan/math/prim/fun/log_determinant.hpp>
#include <stan/math/prim/fun/log_determinant_ldlt.hpp>
#include <stan/math/prim/fun/log_determinant_spd.hpp>
#include <stan/math/prim/fun/log_inv_logit.hpp>
#include <stan/math/prim/fun/log_mix.hpp>
#include <stan/math/prim/fun/log_softmax.hpp>
#include <stan/math/prim/fun/log_sum_exp.hpp>
#include <stan/math/prim/fun/logit.hpp>
#include <stan/math/prim/fun/make_nu.hpp>
#include <stan/math/prim/fun/matrix_exp.hpp>
#include <stan/math/prim/fun/matrix_exp_multiply.hpp>
#include <stan/math/prim/fun/matrix_power.hpp>
#include <stan/math/prim/fun/max.hpp>
#include <stan/math/prim/fun/mdivide_left.hpp>
#include <stan/math/prim/fun/mdivide_left_ldlt.hpp>
#include <stan/math/prim/fun/mdivide_left_spd.hpp>
#include <stan/math/prim/fun/mdivide_left_tri.hpp>
#include <stan/math/prim/fun/mdivide_left_tri_low.hpp>
#include <stan/math/prim/fun/mdivide_right.hpp>
#include <stan/math/prim/fun/mdivide_right_ldlt.hpp>
#include <stan/math/prim/fun/mdivide_right_spd.hpp>
#include <stan/math/prim/fun/mdivide_right_tri.hpp>
#include <stan/math/prim/fun/mdivide_right_tri_low.hpp>
#include <stan/math/prim/fun/mean.hpp>
#include <stan/math/prim/fun/min.hpp>
#include <stan/math/prim/fun/minus.hpp>
#include <stan/math/prim/fun/multiply.hpp>
#include <stan/math/prim/fun/multiply_lower_tri_self_transpose.hpp>
#include <stan/math/prim/fun/num_elements.hpp>
#include <stan/math/prim/fun/ordered_constrain.hpp>
#include <stan/math/prim/fun/ordered_free.hpp>
#include <stan/math/prim/fun/positive_ordered_constrain.hpp>
#include <stan/math/prim/fun/positive_ordered_free.hpp>
#include <stan/math/prim/fun/prod.hpp>
#include <stan/math/prim/fun/promote_common.hpp>
#include <stan/math/prim/fun/promote_elements.hpp>
#include <stan/math/prim/fun/promote_scalar.hpp>
#include <stan/math/prim/fun/qr_Q.hpp>
#include <stan/math/prim/fun/qr_R.hpp>
#include <stan/math/prim/fun/qr_thin_Q.hpp>
#include <stan/math/prim/fun/qr_thin_R.hpp>
#include <stan/math/prim/fun/quad_form.hpp>
#include <stan/math/prim/fun/quad_form_diag.hpp>
#include <stan/math/prim/fun/quad_form_sym.hpp>
#include <stan/math/prim/fun/rank.hpp>
#include <stan/math/prim/fun/read_corr_L.hpp>
#include <stan/math/prim/fun/read_corr_matrix.hpp>
#include <stan/math/prim/fun/read_cov_L.hpp>
#include <stan/math/prim/fun/read_cov_matrix.hpp>
#include <stan/math/prim/fun/rep_matrix.hpp>
#include <stan/math/prim/fun/rep_row_vector.hpp>
#include <stan/math/prim/fun/rep_vector.hpp>
#include <stan/math/prim/fun/resize.hpp>
#include <stan/math/prim/fun/round.hpp>
#include <stan/math/prim/fun/row.hpp>
#include <stan/math/prim/fun/rows.hpp>
#include <stan/math/prim/fun/rows_dot_product.hpp>
#include <stan/math/prim/fun/rows_dot_self.hpp>
#include <stan/math/prim/fun/scale_matrix_exp_multiply.hpp>
#include <stan/math/prim/fun/sd.hpp>
#include <stan/math/prim/fun/segment.hpp>
#include <stan/math/prim/fun/simplex_constrain.hpp>
#include <stan/math/prim/fun/simplex_free.hpp>
#include <stan/math/prim/fun/sin.hpp>
#include <stan/math/prim/fun/singular_values.hpp>
#include <stan/math/prim/fun/sinh.hpp>
#include <stan/math/prim/fun/softmax.hpp>
#include <stan/math/prim/fun/sort_asc.hpp>
#include <stan/math/prim/fun/sort_desc.hpp>
#include <stan/math/prim/fun/sort_indices.hpp>
#include <stan/math/prim/fun/sort_indices_asc.hpp>
#include <stan/math/prim/fun/sort_indices_desc.hpp>
#include <stan/math/prim/fun/sqrt.hpp>
#include <stan/math/prim/fun/square.hpp>
#include <stan/math/prim/fun/squared_distance.hpp>
#include <stan/math/prim/fun/stan_print.hpp>
#include <stan/math/prim/fun/sub_col.hpp>
#include <stan/math/prim/fun/sub_row.hpp>
#include <stan/math/prim/fun/subtract.hpp>
#include <stan/math/prim/fun/sum.hpp>
#include <stan/math/prim/fun/tail.hpp>
#include <stan/math/prim/fun/tan.hpp>
#include <stan/math/prim/fun/tanh.hpp>
#include <stan/math/prim/fun/tcrossprod.hpp>
#include <stan/math/prim/fun/tgamma.hpp>
#include <stan/math/prim/fun/to_array_1d.hpp>
#include <stan/math/prim/fun/to_array_2d.hpp>
#include <stan/math/prim/fun/to_matrix.hpp>
#include <stan/math/prim/fun/to_row_vector.hpp>
#include <stan/math/prim/fun/to_vector.hpp>
#include <stan/math/prim/fun/trace.hpp>
#include <stan/math/prim/fun/trace_gen_inv_quad_form_ldlt.hpp>
#include <stan/math/prim/fun/trace_gen_quad_form.hpp>
#include <stan/math/prim/fun/trace_inv_quad_form_ldlt.hpp>
#include <stan/math/prim/fun/trace_quad_form.hpp>
#include <stan/math/prim/fun/transpose.hpp>
#include <stan/math/prim/fun/trigamma.hpp>
#include <stan/math/prim/fun/trunc.hpp>
#include <stan/math/prim/fun/typedefs.hpp>
#include <stan/math/prim/fun/unit_vector_constrain.hpp>
#include <stan/math/prim/fun/unit_vector_free.hpp>
#include <stan/math/prim/fun/value_of.hpp>
#include <stan/math/prim/fun/value_of_rec.hpp>
#include <stan/math/prim/fun/variance.hpp>
#include <stan/math/prim/fun/welford_covar_estimator.hpp>
#include <stan/math/prim/fun/welford_var_estimator.hpp>

#include <stan/math/prim/functor/finite_diff_gradient.hpp>
#include <stan/math/prim/functor/finite_diff_gradient_auto.hpp>
#include <stan/math/prim/functor/finite_diff_hessian.hpp>
#include <stan/math/prim/functor/finite_diff_hessian_auto.hpp>
#include <stan/math/prim/functor/finite_diff_hessian_helper.hpp>
#include <stan/math/prim/functor/map_rect.hpp>
#include <stan/math/prim/functor/map_rect_combine.hpp>
#include <stan/math/prim/functor/map_rect_concurrent.hpp>
#include <stan/math/prim/functor/map_rect_reduce.hpp>
#include <stan/math/prim/prob/bernoulli_logit_glm_log.hpp>
#include <stan/math/prim/prob/bernoulli_logit_glm_lpmf.hpp>
#include <stan/math/prim/prob/bernoulli_logit_glm_rng.hpp>
#include <stan/math/prim/prob/categorical_log.hpp>
#include <stan/math/prim/prob/categorical_logit_glm_lpmf.hpp>
#include <stan/math/prim/prob/categorical_logit_log.hpp>
#include <stan/math/prim/prob/categorical_logit_lpmf.hpp>
#include <stan/math/prim/prob/categorical_logit_rng.hpp>
#include <stan/math/prim/prob/categorical_lpmf.hpp>
#include <stan/math/prim/prob/categorical_rng.hpp>
#include <stan/math/prim/prob/dirichlet_log.hpp>
#include <stan/math/prim/prob/dirichlet_lpdf.hpp>
#include <stan/math/prim/prob/dirichlet_lpmf.hpp>
#include <stan/math/prim/prob/dirichlet_rng.hpp>
#include <stan/math/prim/prob/gaussian_dlm_obs_log.hpp>
#include <stan/math/prim/prob/gaussian_dlm_obs_lpdf.hpp>
#include <stan/math/prim/prob/gaussian_dlm_obs_rng.hpp>
#include <stan/math/prim/prob/inv_wishart_log.hpp>
#include <stan/math/prim/prob/inv_wishart_lpdf.hpp>
#include <stan/math/prim/prob/inv_wishart_rng.hpp>
#include <stan/math/prim/prob/lkj_corr_cholesky_log.hpp>
#include <stan/math/prim/prob/lkj_corr_cholesky_lpdf.hpp>
#include <stan/math/prim/prob/lkj_corr_cholesky_rng.hpp>
#include <stan/math/prim/prob/lkj_corr_log.hpp>
#include <stan/math/prim/prob/lkj_corr_lpdf.hpp>
#include <stan/math/prim/prob/lkj_corr_rng.hpp>
#include <stan/math/prim/prob/lkj_cov_log.hpp>
#include <stan/math/prim/prob/lkj_cov_lpdf.hpp>
#include <stan/math/prim/prob/matrix_normal_prec_log.hpp>
#include <stan/math/prim/prob/matrix_normal_prec_lpdf.hpp>
#include <stan/math/prim/prob/matrix_normal_prec_rng.hpp>
#include <stan/math/prim/prob/multi_gp_cholesky_log.hpp>
#include <stan/math/prim/prob/multi_gp_cholesky_lpdf.hpp>
#include <stan/math/prim/prob/multi_gp_log.hpp>
#include <stan/math/prim/prob/multi_gp_lpdf.hpp>
#include <stan/math/prim/prob/multi_normal_cholesky_log.hpp>
#include <stan/math/prim/prob/multi_normal_cholesky_lpdf.hpp>
#include <stan/math/prim/prob/multi_normal_cholesky_rng.hpp>
#include <stan/math/prim/prob/multi_normal_log.hpp>
#include <stan/math/prim/prob/multi_normal_lpdf.hpp>
#include <stan/math/prim/prob/multi_normal_prec_log.hpp>
#include <stan/math/prim/prob/multi_normal_prec_lpdf.hpp>
#include <stan/math/prim/prob/multi_normal_prec_rng.hpp>
#include <stan/math/prim/prob/multi_normal_rng.hpp>
#include <stan/math/prim/prob/multi_student_t_log.hpp>
#include <stan/math/prim/prob/multi_student_t_lpdf.hpp>
#include <stan/math/prim/prob/multi_student_t_rng.hpp>
#include <stan/math/prim/prob/multinomial_log.hpp>
#include <stan/math/prim/prob/multinomial_lpmf.hpp>
#include <stan/math/prim/prob/multinomial_rng.hpp>
#include <stan/math/prim/prob/neg_binomial_2_log_glm_log.hpp>
#include <stan/math/prim/prob/neg_binomial_2_log_glm_lpmf.hpp>
#include <stan/math/prim/prob/normal_id_glm_log.hpp>
#include <stan/math/prim/prob/normal_id_glm_lpdf.hpp>
#include <stan/math/prim/prob/ordered_logistic_log.hpp>
#include <stan/math/prim/prob/ordered_logistic_glm_lpmf.hpp>
#include <stan/math/prim/prob/ordered_logistic_lpmf.hpp>
#include <stan/math/prim/prob/ordered_logistic_rng.hpp>
#include <stan/math/prim/prob/ordered_probit_log.hpp>
#include <stan/math/prim/prob/ordered_probit_lpmf.hpp>
#include <stan/math/prim/prob/ordered_probit_rng.hpp>
#include <stan/math/prim/prob/poisson_log_glm_log.hpp>
#include <stan/math/prim/prob/poisson_log_glm_lpmf.hpp>
#include <stan/math/prim/prob/wishart_log.hpp>
#include <stan/math/prim/prob/wishart_lpdf.hpp>
#include <stan/math/prim/prob/wishart_rng.hpp>

#include <stan/math/prim/vectorize/apply_scalar_unary.hpp>

#include <stan/math/prim/arr.hpp>

#endif
